<center>

# Web Intelligence

# Who will win the Tennis Australian Open 2020?

## 02 Adding New Variables

### Riccardo Spolaor (864877)

</center>

### Creazione Variabili aggiuntive

In [494]:
## Prova a usare le medie per i tornei!


import pandas as pd
import numpy as np

In [495]:
dataframe = pd.read_csv('./datasets/dataframe02.csv', low_memory = False)

In [496]:
dataframe.head()

,csvID,ATP,Location,Tournament,Date,Series,Round,Best of,Winner,Loser,...,Kohlschreiber P.A,Kohlschreiber P.B,Simon G.A,Simon G.B,Bautista Agut R.A,Bautista Agut R.B,Verdasco F.A,Verdasco F.B,OtherA,OtherB
0,0,1.0,13,0,2010-01-04,0,0,3.0,Gasquet R.,Nieminen J.,...,0,0,0,0,0,0,0,0,0,1
1,0,1.0,13,0,2010-01-04,0,0,3.0,Odesnik W.,Clement A.,...,0,0,0,0,0,0,0,0,1,1
2,0,1.0,13,0,2010-01-04,0,0,3.0,Gicquel M.,Petzschner P.,...,0,0,0,0,0,0,0,0,1,1
3,0,1.0,13,0,2010-01-04,0,0,3.0,Falla A.,Chardy J.,...,0,0,0,0,0,0,0,0,1,1
4,0,1.0,13,0,2010-01-04,0,0,3.0,Levy H.,Llodra M.,...,0,0,0,0,0,0,0,0,1,1

In [497]:
'''
def sortMatchesByDate ():
    dataframe['Index'] = dataframe.index
    dataframe.sort_values(['Date','Index'],inplace = True)
    dataframe.drop('Index', axis=1, inplace = True)
    
sortMatchesByDate()
'''

"\ndef sortMatchesByDate ():\n    dataframe['Index'] = dataframe.index\n    dataframe.sort_values(['Date','Index'],inplace = True)\n    dataframe.drop('Index', axis=1, inplace = True)\n    \nsortMatchesByDate()\n"

In [498]:
dataframe['RankA>RankB'] = dataframe.apply(lambda x : int(x['WRank'] > x['LRank']), axis = 1)

In [499]:
dataframe[['WRank', 'LRank', 'RankA>RankB']]

       WRank  LRank  RankA>RankB
0       52.0   88.0            0
1      105.0   63.0            1
2       58.0   80.0            0
3       81.0   32.0            1
4      119.0   67.0            1
5       36.0   73.0            0
6       12.0  306.0            0
7        7.0   77.0            0
8      131.0  286.0            0
9       20.0  251.0            0
10      42.0   55.0            0
11     134.0   78.0            1
12      44.0   25.0            1
13     285.0   28.0            1
14      65.0  173.0            0
15      13.0   76.0            0
16      44.0   58.0            0
17      12.0  131.0            0
18     105.0   81.0            1
19       7.0  134.0            0
20      52.0  285.0            0
21      36.0  119.0            0
22      13.0   65.0            0
23      20.0   42.0            0
24      12.0  105.0            0
25      13.0   44.0            0
26      20.0   36.0            0
27       7.0   52.0            0
28      12.0   13.0            0
29       7.0   20.0            0
...      ...    ...          ...
26242   42.0   65.0            0
26243   27.0    5.0            1
26244    7.0   18.0            0
26245    1.0   75.0            0
26246   35.0   36.0            0
26247   28.0    6.0            1
26248    2.0   16.0            0
26249   13.0   50.0            0
26250   27.0   42.0            0
26251    1.0    7.0            0
26252   28.0   13.0            1
26253    2.0   35.0            0
26254    1.0   27.0            0
26255   28.0    2.0            1
26256    1.0   28.0            0
26257    2.0    8.0            0
26258    5.0    3.0            1
26259    6.0    4.0            1
26260    7.0    1.0            1
26261    3.0    8.0            0
26262    5.0    2.0            1
26263    1.0    4.0            0
26264    6.0    7.0            0
26265    8.0    5.0            1
26266    3.0    2.0            1
26267    1.0    6.0            0
26268    7.0    4.0            1
26269    6.0    3.0            1
26270    5.0    7.0            0
26271    6.0    5.0            1

[26272 rows x 3 columns]

In [500]:
import itertools

def set_playerA_vs_playerB_statistics():
    
    def get_sorted_tuple(t):
        return tuple(e for e in sorted(t))
    
    ##dataframe.insert(dataframe.columns.get_loc('Loser') + 1, column = 'OpponentsPlayed', value = np.nan)
    #dataframe.insert(dataframe.columns.get_loc('OpponentsPlayed') + 1, column = 'OpponentsWRatioA', value = np.nan)
    #dataframe.insert(dataframe.columns.get_loc('OpponentsWRatioA') + 1, column = 'OpponentsWRatioB', value = np.nan)
    
    opponents_played = []
    opponents_wratioA = []
    opponents_wratioB = []
    
    players_played = {tuple(e for e in sorted(pair)):0 for pair in itertools.combinations(
        dataframe['Winner'].append(dataframe['Loser']).unique(), 2)}
    
    players_won = {pair:0 for pair in itertools.permutations(dataframe['Winner'].append(dataframe['Loser']).unique(), 2)}
    

    for item in dataframe.itertuples():

        opponents_played += [players_played[tuple(e for e in sorted([item.Winner,item.Loser]))]]
        
        try:
            opponents_wratioA += [players_won[(item.Winner,item.Loser)]/players_played[
                tuple(e for e in sorted([item.Winner,item.Loser]))]]
        except:
            opponents_wratioA += [0]
            
        try:
            opponents_wratioB += [players_won[(item.Loser,item.Winner)]/players_played[
                tuple(e for e in sorted([item.Winner,item.Loser]))]]
        except:
            opponents_wratioB += [0]

        players_played[tuple(e for e in sorted([item.Winner,item.Loser]))] += 1
        players_won[(item.Winner,item.Loser)] += 1

    dataframe['OpponentsPlayed'] = opponents_played
    dataframe['OpponentsWRatioA'] = opponents_wratioA
    dataframe['OpponentsWRatioB'] = opponents_wratioB

In [501]:
set_playerA_vs_playerB_statistics()

dataframe['OpponentsWRatioA>OpponentsWRatioB'] = dataframe.apply(lambda x : int(x['OpponentsWRatioA'] > x['OpponentsWRatioB']), axis = 1)

In [502]:
'''
(dataframe[dataframe['Winner'] == 'Nadal R.'].merge(
    dataframe[dataframe['Loser'] == 'Federer R.'])).append(
    dataframe[dataframe['Winner'] == 'Federer R.'].merge(
    dataframe[dataframe['Loser'] == 'Nadal R.'])).head(30).sort_values(by = 'OpponentsPlayed')[['Winner', 'Loser', 
                                                                                                'OpponentsPlayed',
                                                                                                'OpponentsWRatioA', 
                                                                                                'OpponentsWRatioB']]
                                                                                                '''

"\n(dataframe[dataframe['Winner'] == 'Nadal R.'].merge(\n    dataframe[dataframe['Loser'] == 'Federer R.'])).append(\n    dataframe[dataframe['Winner'] == 'Federer R.'].merge(\n    dataframe[dataframe['Loser'] == 'Nadal R.'])).head(30).sort_values(by = 'OpponentsPlayed')[['Winner', 'Loser', \n                                                                                                'OpponentsPlayed',\n                                                                                                'OpponentsWRatioA', \n                                                                                                'OpponentsWRatioB']]\n                                                                                                "

In [503]:
'''
def setTournamentStatistics():
    
    dataframe.insert(dataframe.columns.get_loc('Loser') + 1, column = 'setsTournA', value = np.nan)
    dataframe.insert(dataframe.columns.get_loc('setsTournA') + 1, column = 'setsTournB', value = np.nan)
    dataframe.insert(dataframe.columns.get_loc('setsTournB') + 1, column = 'setsWRatioTournA', value = np.nan)
    dataframe.insert(dataframe.columns.get_loc('setsWRatioTournA') + 1, column = 'setsWRatioTournB', value = np.nan)
    dataframe.insert(dataframe.columns.get_loc('setsWRatioTournB') + 1, column = 'gamesTournA', value = np.nan)
    dataframe.insert(dataframe.columns.get_loc('gamesTournA') + 1, column = 'gamesTournB', value = np.nan)
    dataframe.insert(dataframe.columns.get_loc('gamesTournB') + 1, column = 'gamesWRatioTournA', value = np.nan)
    dataframe.insert(dataframe.columns.get_loc('gamesWRatioTournA') + 1, column = 'gamesWRatioTournB', value = np.nan)
    
    setsTournA = []
    setsTournB = []
    setsWRatioTournA = []
    setsWRatioTournB = []
    gamesTournA = []
    gamesTournB = []
    gamesWRatioTournA = []
    gamesWRatioTournB = []
    
    for _, group in dataframe.groupby(['csvID','ATP'], sort = False):
        players_played_sets = {p:0 for p in dataframe['Winner'].append(dataframe['Loser']).unique()}
        players_won_sets = {p:0 for p in dataframe['Winner'].append(dataframe['Loser']).unique()}
        
        players_played_games = {p:0 for p in dataframe['Winner'].append(dataframe['Loser']).unique()}
        players_won_games = {p:0 for p in dataframe['Winner'].append(dataframe['Loser']).unique()}

        for r in group.itertuples():
            setsTournA += [players_played_sets[r.Winner]]
            gamesTournA += [players_played_games[r.Winner]]
            
            try:
                setsWRatioTournA += [players_won_sets[r.Winner]/players_played_sets[r.Winner]]
            except:
                setsWRatioTournA += [0]
                
            try:
                gamesWRatioTournA += [players_won_games[r.Winner]/players_played_games[r.Winner]]
            except:
                gamesWRatioTournA += [0]
                
            players_played_sets[r.Winner] += (r.Lsets + r.Wsets)
            players_won_sets[r.Winner] += r.Wsets 
            
            players_played_games[r.Winner] += (r.W1 + r.W2 + r.W3 + r.W4 + r.W5 + r.L1 + r.L2 + r.L3 + r.L4 + r.L5)
            players_won_games[r.Winner] += (r.W1 + r.W2 + r.W3 + r.W4 + r.W5)


            setsTournB += [players_played_sets[r.Loser]]
            gamesTournB += [players_played_games[r.Loser]]
            try:
                setsWRatioTournB += [players_won_sets[r.Loser]/players_played_sets[r.Loser]]
            except:
                setsWRatioTournB += [0]
                
            try:
                gamesWRatioTournB += [players_won_games[r.Loser]/players_played_games[r.Loser]]
            except:
                gamesWRatioTournB += [0]
                
            players_played_sets[r.Loser] += (r.Lsets + r.Wsets)
            players_won_sets[r.Loser] += r.Lsets 
            
            players_played_games[r.Loser] += (r.W1 + r.W2 + r.W3 + r.W4 + r.W5 + r.L1 + r.L2 + r.L3 + r.L4 + r.L5)
            players_won_games[r.Loser] += (r.L1 + r.L2 + r.L3 + r.L4 + r.L5)
                                    
    dataframe['setsTournA'] = setsTournA
    dataframe['setsTournB'] = setsTournB
    dataframe['setsWRatioTournA'] = setsWRatioTournA
    dataframe['setsWRatioTournB'] = setsWRatioTournB
    dataframe['gamesTournA'] = gamesTournA
    dataframe['gamesTournB'] = gamesTournB
    dataframe['gamesWRatioTournA'] = gamesWRatioTournA
    dataframe['gamesWRatioTournB'] = gamesWRatioTournB
            
            
setTournamentStatistics()
'''

"\ndef setTournamentStatistics():\n    \n    dataframe.insert(dataframe.columns.get_loc('Loser') + 1, column = 'setsTournA', value = np.nan)\n    dataframe.insert(dataframe.columns.get_loc('setsTournA') + 1, column = 'setsTournB', value = np.nan)\n    dataframe.insert(dataframe.columns.get_loc('setsTournB') + 1, column = 'setsWRatioTournA', value = np.nan)\n    dataframe.insert(dataframe.columns.get_loc('setsWRatioTournA') + 1, column = 'setsWRatioTournB', value = np.nan)\n    dataframe.insert(dataframe.columns.get_loc('setsWRatioTournB') + 1, column = 'gamesTournA', value = np.nan)\n    dataframe.insert(dataframe.columns.get_loc('gamesTournA') + 1, column = 'gamesTournB', value = np.nan)\n    dataframe.insert(dataframe.columns.get_loc('gamesTournB') + 1, column = 'gamesWRatioTournA', value = np.nan)\n    dataframe.insert(dataframe.columns.get_loc('gamesWRatioTournA') + 1, column = 'gamesWRatioTournB', value = np.nan)\n    \n    setsTournA = []\n    setsTournB = []\n    setsWRatioTournA = []\n    setsWRatioTournB = []\n    gamesTournA = []\n    gamesTournB = []\n    gamesWRatioTournA = []\n    gamesWRatioTournB = []\n    \n    for _, group in dataframe.groupby(['csvID','ATP'], sort = False):\n        players_played_sets = {p:0 for p in dataframe['Winner'].append(dataframe['Loser']).unique()}\n        players_won_sets = {p:0 for p in dataframe['Winner'].append(dataframe['Loser']).unique()}\n        \n        players_played_games = {p:0 for p in dataframe['Winner'].append(dataframe['Loser']).unique()}\n        players_won_games = {p:0 for p in dataframe['Winner'].append(dataframe['Loser']).unique()}\n\n        for r in group.itertuples():\n            setsTournA += [players_played_sets[r.Winner]]\n            gamesTournA += [players_played_games[r.Winner]]\n            \n            try:\n                setsWRatioTournA += [players_won_sets[r.Winner]/players_played_sets[r.Winner]]\n            except:\n                setsWRatioTournA += [0]\n                \n            try:\n                gamesWRatioTournA += [players_won_games[r.Winner]/players_played_games[r.Winner]]\n            except:\n                gamesWRatioTournA += [0]\n                \n            players_played_sets[r.Winner] += (r.Lsets + r.Wsets)\n            players_won_sets[r.Winner] += r.Wsets \n            \n            players_played_games[r.Winner] += (r.W1 + r.W2 + r.W3 + r.W4 + r.W5 + r.L1 + r.L2 + r.L3 + r.L4 + r.L5)\n            players_won_games[r.Winner] += (r.W1 + r.W2 + r.W3 + r.W4 + r.W5)\n\n\n            setsTournB += [players_played_sets[r.Loser]]\n            gamesTournB += [players_played_games[r.Loser]]\n            try:\n                setsWRatioTournB += [players_won_sets[r.Loser]/players_played_sets[r.Loser]]\n            except:\n                setsWRatioTournB += [0]\n                \n            try:\n                gamesWRatioTournB += [players_won_games[r.Loser]/players_played_games[r.Loser]]\n            except:\n                gamesWRatioTournB += [0]\n                \n            players_played_sets[r.Loser] += (r.Lsets + r.Wsets)\n            players_won_sets[r.Loser] += r.Lsets \n            \n            players_played_games[r.Loser] += (r.W1 + r.W2 + r.W3 + r.W4 + r.W5 + r.L1 + r.L2 + r.L3 + r.L4 + r.L5)\n            players_won_games[r.Loser] += (r.L1 + r.L2 + r.L3 + r.L4 + r.L5)\n                                    \n    dataframe['setsTournA'] = setsTournA\n    dataframe['setsTournB'] = setsTournB\n    dataframe['setsWRatioTournA'] = setsWRatioTournA\n    dataframe['setsWRatioTournB'] = setsWRatioTournB\n    dataframe['gamesTournA'] = gamesTournA\n    dataframe['gamesTournB'] = gamesTournB\n    dataframe['gamesWRatioTournA'] = gamesWRatioTournA\n    dataframe['gamesWRatioTournB'] = gamesWRatioTournB\n            \n            \nsetTournamentStatistics()\n"

In [504]:
def setTournamentStatistics():

    dataframe.insert(dataframe.columns.get_loc('Lsets') + 1, column = 'Last1A', value = np.nan)
    dataframe.insert(dataframe.columns.get_loc('Last1A') + 1, column = 'Last2A', value = np.nan)
    dataframe.insert(dataframe.columns.get_loc('Last2A') + 1, column = 'Last3A', value = np.nan)
    dataframe.insert(dataframe.columns.get_loc('Last3A') + 1, column = 'Last4A', value = np.nan)
    dataframe.insert(dataframe.columns.get_loc('Last4A') + 1, column = 'Last5A', value = np.nan)
    dataframe.insert(dataframe.columns.get_loc('Last5A') + 1, column = 'LastSetsA', value = np.nan)
    
    dataframe.insert(dataframe.columns.get_loc('LastSetsA') + 1, column = 'Last1B', value = np.nan)
    dataframe.insert(dataframe.columns.get_loc('Last1B') + 1, column = 'Last2B', value = np.nan)
    dataframe.insert(dataframe.columns.get_loc('Last2B') + 1, column = 'Last3B', value = np.nan)
    dataframe.insert(dataframe.columns.get_loc('Last3B') + 1, column = 'Last4B', value = np.nan)
    dataframe.insert(dataframe.columns.get_loc('Last4B') + 1, column = 'Last5B', value = np.nan)
    dataframe.insert(dataframe.columns.get_loc('Last5B') + 1, column = 'LastSetsB', value = np.nan)
      
    values = {'1A': [], '1B': [], '2A': [], '2B': [], '3A': [], '3B': [], '4A': [], '4B': [], '5A': [], '5B': [],
              'setsA': [], 'setsB': []}

    players_last = {p : {'1': 0, '2':0,'3':0,'4':0,'5':0,'sets':0} 
                    for p in dataframe['Winner'].append(dataframe['Loser']).unique()}

    for _, group in dataframe.groupby(['csvID','ATP'], sort = False):

        for r in group.itertuples():
            for i in '12345':
                values[i+'A'] += [players_last[r.Winner][i]]
                values[i+'B'] += [players_last[r.Loser][i]]
            values['setsA'] += [players_last[r.Winner]['sets']]
            values['setsB'] += [players_last[r.Loser]['sets']]

            players_last[r.Winner].update({'1': r.W1, '2':r.W2,'3':r.W3,'4':r.W4,'5':r.W5,'sets':r.Wsets}) 
            players_last[r.Loser].update({'1': r.L1, '2':r.L2,'3':r.L3,'4':r.L4,'5':r.L5,'sets':r.Lsets})

    for i in '12345':
        dataframe['Last'+i+'A'] = values[i+'A']
        dataframe['Last'+i+'B'] = values[i+'B']
    dataframe['LastSetsA'] = values['setsA']
    dataframe['LastSetsB'] = values['setsB']
                     
            
            
setTournamentStatistics()

In [505]:
dataframe[['Winner', 'Loser','Tournament','Round','W1','W2','W3', 'Wsets', 'L1','L2','L3', 'Lsets', 'Last1A', 'Last2A', 'Last3A', 'LastSetsA', 'Last1B', 'Last2B', 'Last3B', 'LastSetsB']].head(30)

,Winner,Loser,Tournament,Round,W1,W2,W3,Wsets,L1,L2,L3,Lsets,Last1A,Last2A,Last3A,LastSetsA,Last1B,Last2B,Last3B,LastSetsB
0,Gasquet R.,Nieminen J.,0,0,6.0,4.0,6.0,2.0,3.0,6.0,4.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Odesnik W.,Clement A.,0,0,6.0,7.0,0.0,2.0,4.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Gicquel M.,Petzschner P.,0,0,6.0,6.0,0.0,2.0,3.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Falla A.,Chardy J.,0,0,6.0,6.0,0.0,2.0,4.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Levy H.,Llodra M.,0,0,6.0,6.0,0.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,Bellucci T.,Chela J.I.,0,0,6.0,3.0,6.0,2.0,3.0,6.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,Stepanek R.,Millman J.,0,0,6.0,6.0,0.0,2.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,Roddick A.,Luczak P.,0,0,7.0,6.0,0.0,2.0,6.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,Dolgopolov O.,Tomic B.,0,0,6.0,6.0,0.0,2.0,4.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,Berdych T.,Lindahl N.,0,0,6.0,6.0,0.0,2.0,2.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,Baghdatis M.,Fish M.,0,0,7.0,7.0,0.0,2.0,5.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,Ball C.,Zverev M.,0,0,7.0,6.0,0.0,2.0,5.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,Blake J.,Querrey S.,0,0,4.0,6.0,6.0,2.0,6.0,3.0,4.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,Ebden M.,Melzer J.,0,0,7.0,6.0,0.0,2.0,5.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,Serra F.,Reister J.,0,0,6.0,7.0,7.0,2.0,7.0,6.0,5.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,Monfils G.,Dent T.,0,0,7.0,6.0,6.0,2.0,6.0,7.0,2.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,Blake J.,Gicquel M.,0,1,6.0,3.0,7.0,2.0,3.0,6.0,6.0,1.0,4.0,6.0,6.0,2.0,6.0,6.0,0.0,2.0
17,Stepanek R.,Dolgopolov O.,0,1,5.0,7.0,6.0,2.0,7.0,6.0,2.0,1.0,6.0,6.0,0.0,2.0,6.0,6.0,0.0,2.0
18,Odesnik W.,Falla A.,0,1,6.0,6.0,6.0,2.0,7.0,2.0,1.0,1.0,6.0,7.0,0.0,2.0,6.0,6.0,0.0,2.0
19,Roddick A.,Ball C.,0,1,7.0,6.0,0.0,2.0,6.0,3.0,0.0,0.0,7.0,6.0,0.0,2.0,7.0,6.0,0.0,2.0
20,Gasquet R.,Ebden M.,0,1,6.0,6.0,0.0,2.0,3.0,4.0,0.0,0.0,6.0,4.0,6.0,2.0,7.0,6.0,0.0,2.0
21,Bellucci T.,Levy H.,0,1,6.0,4.0,6.0,2.0,4.0,6.0,4.0,1.0,6.0,3.0,6.0,2.0,6.0,6.0,0.0,2.0
22,Monfils G.,Serra F.,0,1,6.0,7.0,6.0,2.0,7.0,6.0,1.0,1.0,7.0,6.0,6.0,2.0,6.0,7.0,7.0,2.0
23,Berdych T.,Baghdatis M.,0,1,6.0,6.0,0.0,2.0,0.0,1.0,0.0,0.0,6.0,6.0,0.0,2.0,7.0,7.0,0.0,2.0
24,Stepanek R.,Odesnik W.,0,5,7.0,6.0,0.0,2.0,6.0,1.0,0.0,0.0,5.0,7.0,6.0,2.0,6.0,6.0,6.0,2.0
25,Monfils G.,Blake J.,0,5,3.0,6.0,6.0,2.0,6.0,3.0,4.0,1.0,6.0,7.0,6.0,2.0,6.0,3.0,7.0,2.0
26,Berdych T.,Bellucci T.,0,5,7.0,2.0,7.0,2.0,6.0,6.0,6.0,1.0,6.0,6.0,0.0,2.0,6.0,4.0,6.0,2.0
27,Roddick A.,Gasquet R.,0,5,6.0,7.0,0.0,2.0,3.0,6.0,0.0,0.0,7.0,6.0,0.0,2.0,6.0,6.0,0.0,2.0
28,Stepanek R.,Monfils G.,0,6,6.0,6.0,0.0,2.0,2.0,1.0,0.0,0.0,7.0,6.0,0.0,2.0,3.0,6.0,6.0,2.0
29,Roddick A.,Berdych T.,0,6,1.0,6.0,6.0,2.0,6.0,3.0,4.0,1.0,6.0,7.0,0.0,2.0,7.0,2.0,7.0,2.0

In [506]:
# Itero una volta aggiungendo la feature delle partite giocate da perdente e vincitore finora

def setPlayedMatches ():
    
    dataframe.insert(dataframe.columns.get_loc('Loser') + 1, column = 'PlayedA', value = np.nan)
    dataframe.insert(dataframe.columns.get_loc('PlayedA') + 1, column = 'PlayedB', value = np.nan)
    
    playersDictionary = {p:0 for p in dataframe['Winner'].append(dataframe['Loser']).unique()}
    wPlayed = []
    lPlayed = []
    for item in dataframe.itertuples():
        wPlayed += [playersDictionary[item.Winner]]
        lPlayed += [playersDictionary[item.Loser]]
        playersDictionary[item.Loser] += 1
        playersDictionary[item.Winner] += 1
    dataframe['PlayedA'] = wPlayed
    dataframe['PlayedB'] = lPlayed
    
def setPlayedMatchesByCourt ():
    
    dataframe.insert(dataframe.columns.get_loc('MinL') + 1, column = 'PlayedCourtA', value = np.nan)
    dataframe.insert(dataframe.columns.get_loc('PlayedCourtA') + 1, column = 'PlayedCourtB', value = np.nan)
    
    dataframe.insert(dataframe.columns.get_loc('PlayedCourtB') + 1, column = 'WonRatioCourtA', value = np.nan)
    dataframe.insert(dataframe.columns.get_loc('WonRatioCourtA') + 1, column = 'WonRatioCourtB', value = np.nan)
    
    played_court_A = []
    played_court_B = []
    won_court_A = []
    won_court_B = []
    
    players_played = {p:{'Clay':0,'Hard':0,'Grass':0} for p in dataframe['Winner'].append(dataframe['Loser']).unique()}
    players_won = {p:{'Clay':0,'Hard':0,'Grass':0} for p in dataframe['Winner'].append(dataframe['Loser']).unique()}

    for item in dataframe.itertuples():

        if item.Hard != 0:
            court = 'Hard'
        elif item.Grass != 0:
            court = 'Grass'
        elif item.Clay != 0:
            court = 'Clay'

        played_court_A += [players_played[item.Winner][court]]
        played_court_B += [players_played[item.Loser][court]]

        try:
            won_court_A += [players_won[item.Winner][court]/players_played[item.Winner][court]]
        except:
            won_court_A += [0]
        try:
            won_court_B += [players_won[item.Loser][court]/players_played[item.Loser][court]]
        except:
            won_court_B += [0]

        players_played[item.Winner][court] += 1
        players_played[item.Loser][court] += 1

        players_won[item.Winner][court] += 1

    dataframe['PlayedCourtA'] = played_court_A
    dataframe['PlayedCourtB'] = played_court_B
    dataframe['WonRatioCourtA'] = won_court_A 
    dataframe['WonRatioCourtB'] = won_court_B

In [507]:
setPlayedMatches()

In [508]:
setPlayedMatchesByCourt ()

In [509]:
dataframe['WonRatioCourtA>WonRatioCourtB'] = dataframe.apply(lambda x : int(x['WonRatioCourtA'] > x['WonRatioCourtB']), axis = 1)

In [510]:
dataframe.head(20)[['Winner','Loser','PlayedA','PlayedB']]

           Winner          Loser  PlayedA  PlayedB
0      Gasquet R.    Nieminen J.        0        0
1      Odesnik W.     Clement A.        0        0
2      Gicquel M.  Petzschner P.        0        0
3        Falla A.      Chardy J.        0        0
4         Levy H.      Llodra M.        0        0
5     Bellucci T.     Chela J.I.        0        0
6     Stepanek R.     Millman J.        0        0
7      Roddick A.      Luczak P.        0        0
8   Dolgopolov O.       Tomic B.        0        0
9      Berdych T.     Lindahl N.        0        0
10   Baghdatis M.        Fish M.        0        0
11        Ball C.      Zverev M.        0        0
12       Blake J.     Querrey S.        0        0
13       Ebden M.      Melzer J.        0        0
14       Serra F.     Reister J.        0        0
15     Monfils G.        Dent T.        0        0
16       Blake J.     Gicquel M.        1        1
17    Stepanek R.  Dolgopolov O.        1        1
18     Odesnik W.       Falla A.        1        1
19     Roddick A.        Ball C.        1        1

In [511]:
dataframe[dataframe['Winner'] == 'Nadal R.'].head(50)[['Tournament','Winner','Loser','PlayedA','PlayedB', 'PlayedCourtA', 'PlayedCourtB', 'WonRatioCourtA', 'WonRatioCourtB', 'Hard', 'Clay', 'Grass']]

,Tournament,Winner,Loser,PlayedA,PlayedB,PlayedCourtA,PlayedCourtB,WonRatioCourtA,WonRatioCourtB,Hard,Clay,Grass
73,0,Nadal R.,Bolelli S.,0,0,0,0,0.000000,0.000000,1,0,0
80,0,Nadal R.,Starace P.,1,1,1,1,1.000000,1.000000,1,0,0
84,0,Nadal R.,Darcis S.,2,1,2,1,1.000000,1.000000,1,0,0
87,0,Nadal R.,Troicki V.,3,3,3,3,1.000000,1.000000,1,0,0
153,22,Nadal R.,Luczak P.,5,4,5,4,0.800000,0.500000,1,0,0
212,22,Nadal R.,Lacko L.,6,4,6,4,0.833333,0.750000,1,0,0
245,22,Nadal R.,Kohlschreiber P.,7,6,7,6,0.857143,0.833333,1,0,0
256,22,Nadal R.,Karlovic I.,8,6,8,6,0.875000,0.833333,1,0,0
675,11,Nadal R.,Schuettler R.,10,6,10,6,0.800000,0.333333,1,0,0
702,11,Nadal R.,Ancic M.,11,2,11,2,0.818182,1.000000,1,0,0
717,11,Nadal R.,Isner J.,12,17,12,16,0.833333,0.875000,1,0,0
724,11,Nadal R.,Berdych T.,13,16,13,16,0.846154,0.687500,1,0,0
771,15,Nadal R.,Dent T.,15,9,15,9,0.800000,0.333333,1,0,0
795,15,Nadal R.,Nalbandian D.,16,7,16,4,0.812500,0.750000,1,0,0
815,15,Nadal R.,Ferrer D.,17,20,17,10,0.823529,0.600000,1,0,0
819,15,Nadal R.,Tsonga J.W.,18,17,18,17,0.833333,0.764706,1,0,0
914,17,Nadal R.,De Bakker T.,20,12,0,1,0.000000,1.000000,0,1,0
921,17,Nadal R.,Berrer M.,21,20,1,2,1.000000,1.000000,0,1,0
927,17,Nadal R.,Ferrero J.C.,22,25,2,18,1.000000,0.944444,0,1,0
930,17,Nadal R.,Ferrer D.,23,25,3,14,1.000000,0.928571,0,1,0
932,17,Nadal R.,Verdasco F.,24,23,4,7,1.000000,0.857143,0,1,0
1021,12,Nadal R.,Kohlschreiber P.,25,20,5,5,1.000000,0.800000,0,1,0
1035,12,Nadal R.,Hanescu V.,26,20,6,15,1.000000,0.600000,0,1,0
1038,12,Nadal R.,Wawrinka S.,27,20,7,10,1.000000,0.900000,0,1,0
1041,12,Nadal R.,Gulbis E.,28,26,8,10,1.000000,0.800000,0,1,0
1042,12,Nadal R.,Ferrer D.,29,35,9,24,1.000000,0.875000,0,1,0
1162,13,Nadal R.,Dolgopolov O.,30,8,10,5,1.000000,0.200000,0,1,0
1170,13,Nadal R.,Isner J.,31,29,11,10,1.000000,0.600000,0,1,0
1177,13,Nadal R.,Monfils G.,32,20,12,3,1.000000,1.000000,0,1,0
1180,13,Nadal R.,Almagro N.,33,31,13,18,1.000000,0.666667,0,1,0
1182,13,Nadal R.,Federer R.,34,24,14,8,1.000000,0.750000,0,1,0
1269,23,Nadal R.,Mina G.,35,1,15,1,1.000000,0.000000,0,1,0
1293,23,Nadal R.,Zeballos H.,36,22,16,16,1.000000,0.437500,0,1,0
1320,23,Nadal R.,Hewitt L.,37,14,17,8,1.000000,0.625000,0,1,0
1327,23,Nadal R.,Bellucci T.,38,36,18,24,1.000000,0.708333,0,1,0
1332,23,Nadal R.,Almagro N.,39,36,19,23,1.000000,0.695652,0,1,0
1334,23,Nadal R.,Melzer J.,40,36,20,15,1.000000,0.733333,0,1,0
1335,23,Nadal R.,Soderling R.,41,34,21,15,1.000000,0.733333,0,1,0
1400,0,Nadal R.,Daniel M.,42,10,0,1,0.000000,1.000000,0,0,1
1411,0,Nadal R.,Istomin D.,43,18,1,2,1.000000,1.000000,0,0,1
1526,25,Nadal R.,Nishikori K.,45,5,3,2,0.666667,0.000000,0,0,1
1570,25,Nadal R.,Haase R.,46,10,4,2,0.750000,0.500000,0,0,1
1585,25,Nadal R.,Petzschner P.,47,32,5,6,0.800000,0.833333,0,0,1
1597,25,Nadal R.,Mathieu P.H.,48,11,6,3,0.833333,1.000000,0,0,1
1600,25,Nadal R.,Soderling R.,49,39,7,4,0.857143,1.000000,0,0,1
1603,25,Nadal R.,Murray A.,50,31,8,7,0.875000,0.857143,0,0,1
1604,25,Nadal R.,Berdych T.,51,43,9,6,0.888889,1.000000,0,0,1
1932,20,Nadal R.,Wawrinka S.,52,34,20,12,0.800000,0.666667,1,0,0
1940,20,Nadal R.,Anderson K.,53,25,21,15,0.809524,0.533333,1,0,0
1942,20,Nadal R.,Kohlschreiber P.,54,40,22,18,0.818182,0.666667,1,0,0

In [512]:
def getPlayerWinLossRatio ():
    
    dataframe.insert(dataframe.columns.get_loc('PlayedB') + 1, column = 'WinRatioA', value = np.nan)
    dataframe.insert(dataframe.columns.get_loc('WinRatioA') + 1, column = 'WinRatioB', value = np.nan)
    
    wWinRatio = [] 
    lWinRatio = [] 
    
    winnersDictionary = {p:0 for p in dataframe['Winner'].append(dataframe['Loser']).unique()}
    
    for r in dataframe.itertuples():
        if r.PlayedA == 0:
            wPlayed = 1
        else:
            wPlayed = r.PlayedA
            
        if r.PlayedB == 0:
            lPlayed = 1
        else:
            lPlayed = r.PlayedB
            
        
        wWinRatio += [winnersDictionary[r.Winner]/wPlayed]
        lWinRatio += [winnersDictionary[r.Loser]/lPlayed]
        
        winnersDictionary[r.Winner] += 1
        
    dataframe['WinRatioA'] = wWinRatio
    dataframe['WinRatioB'] = lWinRatio

In [513]:
getPlayerWinLossRatio()

In [514]:
dataframe['WinRatioA>WinRatioB'] = dataframe.apply(lambda x : int(x['WinRatioA'] > x['WinRatioB']), axis = 1)

In [515]:
dataframe.head(20)[['Winner','Loser','PlayedA','PlayedB', 'WinRatioA', 'WinRatioB']]

           Winner          Loser  PlayedA  PlayedB  WinRatioA  WinRatioB
0      Gasquet R.    Nieminen J.        0        0        0.0        0.0
1      Odesnik W.     Clement A.        0        0        0.0        0.0
2      Gicquel M.  Petzschner P.        0        0        0.0        0.0
3        Falla A.      Chardy J.        0        0        0.0        0.0
4         Levy H.      Llodra M.        0        0        0.0        0.0
5     Bellucci T.     Chela J.I.        0        0        0.0        0.0
6     Stepanek R.     Millman J.        0        0        0.0        0.0
7      Roddick A.      Luczak P.        0        0        0.0        0.0
8   Dolgopolov O.       Tomic B.        0        0        0.0        0.0
9      Berdych T.     Lindahl N.        0        0        0.0        0.0
10   Baghdatis M.        Fish M.        0        0        0.0        0.0
11        Ball C.      Zverev M.        0        0        0.0        0.0
12       Blake J.     Querrey S.        0        0        0.0        0.0
13       Ebden M.      Melzer J.        0        0        0.0        0.0
14       Serra F.     Reister J.        0        0        0.0        0.0
15     Monfils G.        Dent T.        0        0        0.0        0.0
16       Blake J.     Gicquel M.        1        1        1.0        1.0
17    Stepanek R.  Dolgopolov O.        1        1        1.0        1.0
18     Odesnik W.       Falla A.        1        1        1.0        1.0
19     Roddick A.        Ball C.        1        1        1.0        1.0

In [516]:
'''
def setLastMatchesMean ():
    w1mean_5 = []
    l1mean_5 = []
    playersDictionary = {p:0 for p in dataframe['Winner'].append(dataframe['Loser']).unique()}
    for i,r in dataframe.iterrows():
        dataframe.iloc[i,w1mean_5] = playersDictionary[r['Winner']]
        dataframe.iloc[i,l1mean_5] = playersDictionary[r['Loser']]
        playersDictionary[r['Loser']] = r['L1']
        playersDictionary[r['Winner']] = r['W1']
        
'''

"\ndef setLastMatchesMean ():\n    w1mean_5 = []\n    l1mean_5 = []\n    playersDictionary = {p:0 for p in dataframe['Winner'].append(dataframe['Loser']).unique()}\n    for i,r in dataframe.iterrows():\n        dataframe.iloc[i,w1mean_5] = playersDictionary[r['Winner']]\n        dataframe.iloc[i,l1mean_5] = playersDictionary[r['Loser']]\n        playersDictionary[r['Loser']] = r['L1']\n        playersDictionary[r['Winner']] = r['W1']\n        \n"

In [517]:
def getPlayerLastStats(p, w):
    if len(p['1'])==0:
        w['10_1Mean'] += [0]
        w['10_2Mean'] += [0]
        w['10_3Mean'] += [0]
        w['10_4Mean'] += [0]
        w['10_5Mean'] += [0]
        w['10_setsMean'] += [0]
    else:
        w['10_1Mean'] += [np.mean(p['1'])]
        w['10_2Mean'] += [np.mean(p['2'])]
        w['10_3Mean'] += [np.mean(p['3'])]
        w['10_4Mean'] += [np.mean(p['4'])]
        w['10_5Mean'] += [np.mean(p['5'])]
        w['10_setsMean'] += [np.mean(p['sets'])]


def setPlayersStatistics():
    
    w5 = {'10_1Mean' : [],
          '10_2Mean' : [],
          '10_3Mean' : [],
          '10_4Mean' : [],
          '10_5Mean' : [],
          '10_setsMean' : []}
    
    l5 = {'10_1Mean' : [],
          '10_2Mean' : [],
          '10_3Mean' : [],
          '10_4Mean' : [],
          '10_5Mean' : [],
          '10_setsMean' : []}
    
    playersDictionary = {p: {'1': [], '2': [], '3': [], '4': [], '5': [], 'sets': []} for p in dataframe['Winner'].append(dataframe['Loser']).unique()}
    
    for r in dataframe.itertuples():
        
        getPlayerLastStats(playersDictionary[r.Winner], w5)
        
        getPlayerLastStats(playersDictionary[r.Loser], l5)
        
        playersDictionary[r.Winner]['1'] =  (playersDictionary[r.Winner]['1'] + [r.W1])[-10:]
        playersDictionary[r.Winner]['2'] = (playersDictionary[r.Winner]['2'] + [r.W2])[-10:]
        playersDictionary[r.Winner]['3'] = (playersDictionary[r.Winner]['3'] + [r.W3])[-10:]
        playersDictionary[r.Winner]['4'] = (playersDictionary[r.Winner]['4'] + [r.W4])[-10:]
        playersDictionary[r.Winner]['5'] = (playersDictionary[r.Winner]['5'] + [r.W5])[-10:]
        playersDictionary[r.Winner]['sets'] = (playersDictionary[r.Winner]['sets'] + [r.Wsets])[-10:]
        
        playersDictionary[r.Loser]['1'] = (playersDictionary[r.Loser]['1'] + [r.L1])[-10:]
        playersDictionary[r.Loser]['2'] = (playersDictionary[r.Loser]['2'] + [r.L2])[-10:]
        playersDictionary[r.Loser]['3'] = (playersDictionary[r.Loser]['3'] + [r.L3])[-10:]
        playersDictionary[r.Loser]['4'] = (playersDictionary[r.Loser]['4'] + [r.L4])[-10:]
        playersDictionary[r.Loser]['5'] = (playersDictionary[r.Loser]['5'] + [r.L5])[-10:]
        playersDictionary[r.Loser]['sets'] = (playersDictionary[r.Loser]['sets'] + [r.Lsets])[-10:]
                
    dataframe['10_1MeanA'] = w5['10_1Mean']
    dataframe['10_2MeanA'] = w5['10_2Mean']
    dataframe['10_3MeanA'] = w5['10_3Mean']
    dataframe['10_4MeanA'] = w5['10_4Mean']
    dataframe['10_5MeanA'] = w5['10_5Mean']
    dataframe['10_setsMeanA'] = w5['10_setsMean']
    dataframe['10_1MeanB'] = l5['10_1Mean']
    dataframe['10_2MeanB'] = l5['10_2Mean']
    dataframe['10_3MeanB'] = l5['10_3Mean']
    dataframe['10_4MeanB'] = l5['10_4Mean']
    dataframe['10_5MeanB'] = l5['10_5Mean']
    dataframe['10_setsMeanB'] = l5['10_setsMean']

In [518]:

%%time

dataframe = dataframe.append(pd.DataFrame(
    columns = ['10_1MeanA', '10_2MeanA', '10_3MeanA', '10_4MeanA',
               '10_5MeanA','10_setsMeanA','10_1MeanB', '10_2MeanB', '10_3MeanB', '10_4MeanB',
               '10_5MeanB','10_setsMeanB',]), sort=False)

setPlayersStatistics()

Wall time: 5.25 s

In [519]:
dataframe.to_csv('./datasets/dataframe05.csv', index = False)