<center>

# Web Intelligence

# Who will win the Tennis Australian Open 2020?

## 03 Data Cleaning - Categorical Data Transformation

### Riccardo Spolaor (864877)

</center>

### Trasformazione Variabili Categoriali
Controllo solo le feature categoriali (Tipo = *Object*) e procedo alla loro trasformazione in variabili numeriche.

In [14]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [15]:
dataframe = pd.read_csv('./datasets/dataframe01.csv', low_memory = False)
dataframe.head()

,csvID,ATP,Location,Tournament,Date,Series,Court,Surface,Round,Best of,...,MaxW,MaxWAdded,MaxL,MaxLAdded,AvgW,AvgWAdded,AvgL,AvgLAdded,MinW,MinL
0,0,1.0,Brisbane,Brisbane International,2010-01-04,ATP250,Outdoor,Hard,1st Round,3.0,...,1.533,1,2.740,1,1.4958,1,2.5530,1,1.44,2.375
1,0,1.0,Brisbane,Brisbane International,2010-01-04,ATP250,Outdoor,Hard,1st Round,3.0,...,2.250,1,1.813,1,2.2180,1,1.6350,1,2.14,1.570
2,0,1.0,Brisbane,Brisbane International,2010-01-04,ATP250,Outdoor,Hard,1st Round,3.0,...,1.676,1,2.360,1,1.6436,1,2.2120,1,1.61,2.100
3,0,1.0,Brisbane,Brisbane International,2010-01-04,ATP250,Outdoor,Hard,1st Round,3.0,...,2.620,1,1.581,1,2.5560,1,1.4962,1,2.50,1.440
4,0,1.0,Brisbane,Brisbane International,2010-01-04,ATP250,Outdoor,Hard,1st Round,3.0,...,3.000,1,1.787,1,2.6790,1,1.4768,1,2.17,1.333

In [16]:
print ("Variabili Categoriali:")
print(dataframe.dtypes[dataframe.dtypes == object].index.values)

for value in dataframe.dtypes[dataframe.dtypes == object].index.values:
    print('\n', value, 'values length: ', len(dataframe[value].unique()))
    print('\t', dataframe[value].unique()[:20])

Variabili Categoriali:
['Location' 'Tournament' 'Date' 'Series' 'Court' 'Surface' 'Round'
 'Winner' 'Loser' 'Comment']

 Location values length:  89
	 ['Brisbane' 'Chennai' 'Doha' 'Auckland' 'Sydney' 'Melbourne'
 'Johannesburg ' 'Santiago' 'Zagreb' 'Costa Do Sauipe' 'Rotterdam'
 'San Jose' 'Buenos Aires' 'Marseille' 'Memphis' 'Acapulco' 'Delray Beach'
 'Dubai ' 'Indian Wells' 'Miami']

 Tournament values length:  124
	 ['Brisbane International' 'Chennai Open' 'Qatar Exxon Mobil Open'
 'Heineken Open' 'Medibank International' 'Australian Open'
 'SA Tennis Open' 'Movistar Open' 'PBZ Zagreb Indoors' 'Brasil Open'
 'ABN AMRO World Tennis Tournament' 'SAP Open' 'Copa Telmex' 'Open 13'
 'Regions Morgan Keegan Championships' 'Abierto Mexicano'
 'International Championships' 'Dubai Tennis Championships'
 'BNP Paribas Open' 'Sony Ericsson Open']

 Date values length:  2839
	 ['2010-01-04' '2010-01-05' '2010-01-06' '2010-01-07' '2010-01-08'
 '2010-01-09' '2010-01-10' '2010-01-11' '2010-01-12' '2010-01-13'
 '2010-01-14' '2010-01-15' '2010-01-16' '2010-01-18' '2010-01-19'
 '2010-01-20' '2010-01-21' '2010-01-22' '2010-01-23' '2010-01-24']

 Series values length:  5
	 ['ATP250' 'Grand Slam' 'ATP500' 'Masters 1000' 'Masters Cup']

 Court values length:  2
	 ['Outdoor' 'Indoor']

 Surface values length:  3
	 ['Hard' 'Clay' 'Grass']

 Round values length:  8
	 ['1st Round' '2nd Round' 'Quarterfinals' 'Semifinals' 'The Final'
 '3rd Round' '4th Round' 'Round Robin']

 Winner values length:  530
	 ['Gasquet R.' 'Odesnik W.' 'Gicquel M.' 'Falla A.' 'Levy H.' 'Bellucci T.'
 'Stepanek R.' 'Roddick A.' 'Dolgopolov O.' 'Berdych T.' 'Baghdatis M.'
 'Ball C.' 'Blake J.' 'Ebden M.' 'Serra F.' 'Monfils G.' 'Cilic M.'
 'Hajek J.' 'Giraldo S.' 'Tipsarevic J.']

 Loser values length:  810
	 ['Nieminen J.' 'Clement A.' 'Petzschner P.' 'Chardy J.' 'Llodra M.'
 'Chela J.I.' 'Millman J.' 'Luczak P.' 'Tomic B.' 'Lindahl N.' 'Fish M.'
 'Zverev M.' 'Querrey S.' 'Melzer J.' 'Reister J.' 'Dent T.' 'Gicquel M.'
 'Dolgopolov O.' 'Falla A.' 'Ball C.']

 Comment values length:  6
	 ['Completed' 'Retired' 'Walkover' 'Disqualified' 'Sched' 'Awarded']

Uso la tecnica dello ***one-hot-encoding*** per trasformare le feature con un numero limitato di label e che non presentano nessun tipo di struttura gerarchica (***Court***, ***Surface***, ***Comment***).

In [17]:
dataframe = pd.get_dummies(dataframe, prefix = ['', '', ''],
                   prefix_sep = '', columns = ['Court', 'Surface', 'Comment'])

dataframe.columns

Index(['csvID', 'ATP', 'Location', 'Tournament', 'Date', 'Series', 'Round',
       'Best of', 'Winner', 'Loser', 'WRank', 'WRankAdded', 'LRank',
       'LRankAdded', 'WPts', 'WPtsAdded', 'LPts', 'LPtsAdded', 'W1', 'L1',
       'W2', 'L2', 'W3', 'L3', 'W4', 'L4', 'W5', 'L5', 'Wsets', 'Lsets',
       'MaxW', 'MaxWAdded', 'MaxL', 'MaxLAdded', 'AvgW', 'AvgWAdded', 'AvgL',
       'AvgLAdded', 'MinW', 'MinL', 'Indoor', 'Outdoor', 'Clay', 'Grass',
       'Hard', 'Awarded', 'Completed', 'Disqualified', 'Retired', 'Sched',
       'Walkover'],
      dtype='object')

In [18]:
for col in ['Indoor', 'Outdoor','Clay', 'Grass', 'Hard', 'Awarded', 'Completed', 'Disqualified','Retired', 'Sched', 'Walkover']:
    print (col,'number of entries:', dataframe[dataframe[col]==1].shape[0])

Indoor number of entries: 4562
Outdoor number of entries: 21730
Clay number of entries: 8214
Grass number of entries: 3108
Hard number of entries: 14970
Awarded number of entries: 1
Completed number of entries: 25280
Disqualified number of entries: 1
Retired number of entries: 846
Sched number of entries: 2
Walkover number of entries: 162

Per quanto riguarda i ***Round***:
* Posso assegnare alle feature un valore numerico crescente in base all'importanza del Round:
    * *1st Round* < *2nd Round* < *3rd Round* < *4th Round* < *Round Robin* < *Quarterfinals* < *Semifinals* < *The Final*;

In [19]:
print('Tipi di Round:')

print(dataframe['Round'].unique())

roundsOrdered = {'1st Round': 0, '2nd Round': 1, 'Quarterfinals': 5, 'The Final': 7, 'Semifinals': 6,
 '3rd Round': 2, '4th Round': 3, 'Round Robin': 4}

dataframe['Round'] = dataframe['Round'].apply(lambda x : roundsOrdered[x])

Tipi di Round:
['1st Round' '2nd Round' 'Quarterfinals' 'Semifinals' 'The Final'
 '3rd Round' '4th Round' 'Round Robin']

Per quanto riguarda la colonna ***Series***:

* Posso assegnare alle feature un valore numerico crescente in base all'importanza del tipo di torneo:
    * *ATP 250* < *ATP 500* < *Masters 1000* < *Masters Cup* < *Grand Slam*

In [20]:
print('Tipi di Tornei:')

print(dataframe['Series'].unique())

pd.DataFrame(columns = ['Series','WPts'], data = [
    ['Grand Slam', 2000],
    ['Masters Cup', 1500],
    ['ATP250', 250],
    ['ATP500', 500],
    ['Masters 1000', 1000]
]).sort_values(by = 'WPts')

Tipi di Tornei:
['ATP250' 'Grand Slam' 'ATP500' 'Masters 1000' 'Masters Cup']

         Series  WPts
2        ATP250   250
3        ATP500   500
4  Masters 1000  1000
1   Masters Cup  1500
0    Grand Slam  2000

In [21]:
seriesOrdered = {'ATP250': 0, 'ATP500': 1, 'Masters 1000': 2,
                'Masters Cup': 3, 'Grand Slam': 4}
dataframe['Series'] = dataframe['Series'].apply(lambda x : seriesOrdered[x])

La feature ***Tournament*** presenta troppi label distinti.
Per non allargare troppo il Dataframe con lo ***one-hot-encoding*** su tutti i label:
* Seleziono i primi 25 Tornei piÃ¹ prestigiosi e li categorizzo in ordine crescente partendo da 1;
* Gli altri li categorizzo con 0.

In [22]:
print('Grand Slam: ', dataframe[dataframe['Series']==4]['Tournament'].unique(), '\n')
print('Masters Cup: ', dataframe[dataframe['Series']==3]['Tournament'].unique(), '\n')
print('Masters 1000: ', dataframe[dataframe['Series']==2]['Tournament'].unique()[:20], '\n')
print('ATP500: ', dataframe[dataframe['Series']==1]['Tournament'].unique()[:20], '\n')
print('ATP250: ', dataframe[dataframe['Series']==0]['Tournament'].unique()[:20], '\n')

Grand Slam:  ['Australian Open' 'French Open' 'Wimbledon' 'US Open']

Masters Cup:  ['Masters Cup']

Masters 1000:  ['BNP Paribas Open' 'Sony Ericsson Open' 'Monte Carlo Masters'
 "Internazionali BNL d'Italia" 'Mutua MadrileÃ±a Madrid Open'
 'Rogers Masters' 'Western & Southern Financial Group Masters'
 'Shanghai Masters' 'BNP Paribas Masters' 'Mutua Madrid Open']

ATP500:  ['ABN AMRO World Tennis Tournament' 'Regions Morgan Keegan Championships'
 'Abierto Mexicano' 'Dubai Tennis Championships' 'Open Banco Sabadell'
 'German Open Tennis Championships' 'Legg Mason Classic' 'China Open'
 'Rakuten Japan Open Tennis Championships' 'Swiss Indoors'
 'Valencia Open 500' 'Citi Open'
 'U.S. National Indoor Tennis Championships' 'Rio Open'
 'Open Banco Sabadell ' 'bet-at-home Open' 'Gerry Weber Open'
 'AEGON Championships' 'AEGON Open' 'German Tennis Championships']

ATP250:  ['Brisbane International' 'Chennai Open' 'Qatar Exxon Mobil Open'
 'Heineken Open' 'Medibank International' 'SA Tennis Open' 'Movistar Open'
 'PBZ Zagreb Indoors' 'Brasil Open' 'SAP Open' 'Copa Telmex' 'Open 13'
 'International Championships' 'Grand Prix Hassan II'
 "U.S. Men's Clay Court Championships" 'Serbia Open' 'Estoril Open'
 'BMW Open' 'Open de Nice CÃ´te dâ€™Azur' 'Gerry Weber Open']

Includo tutti i tipi di *Grand Slam*, il torneo *Masters Cup*, tutti i tornei del tipo *Masters 1000* e i primi 10 tornei dell'*ATP500* classificati secondo **Tennis365**

Fonti: <br>
* https://www.tennis365.com/tennis-top-10/top-10-atp-tour-500-series-events-where-does-queens-club-rank/
* https://www.tennis365.com/tennis-top-10/top-10-biggest-non-grand-slam-tournaments-on-the-tennis-tour/
* https://www.forbes.com/sites/monteburke/2012/05/30/what-is-the-most-prestigious-grand-slam-tennis-tournament/#2370e5097696

In [23]:
def encodeTournaments():
    grandSlams = ['Wimbledon', 'US Open', 'French Open', 'Australian Open']
    mastersCup = ['Masters Cup']
    masters1000 = ['Rogers Masters','BNP Paribas Masters', 'Shanghai Masters', 'Monte Carlo Masters', 
                   'Western & Southern Financial Group Masters', 
                   'Sony Ericsson Open', 'Mutua Madrid Open', 'Mutua MadrileÃ±a Madrid Open', 
                   'Internazionali BNL d\'Italia', 'BNP Paribas Open']
    atp500best = ['Citi Open','Halle Open', 'Dubai Tennis Championships', 'China Open', 'ABN AMRO World Tennis Tournament', 
              'Swiss Indoors', 'Rakuten Japan Open Tennis Championships','German Open Tennis Championships',
              'Open Banco Sabadell', 'Queen\'s Club Championships']
    
    tournamentsDict = {t:i+1 for i,t in enumerate(atp500best[::-1] + masters1000[::-1] + mastersCup +
                                                  grandSlams[::-1])}
    
    dataframe['TournamentEnc'] = dataframe['Tournament'].apply(lambda x : 
                                                               tournamentsDict[x] if x in tournamentsDict
                                                               else 0)

encodeTournaments()

Trasformare le feature ***Winner*** e ***Loser*** con lo **one-hot-encoding** allargherebbe troppo il dataframe:
* Ordino i giocatori in base alla differenza tra il numero delle loro vittorie e quello delle loro sconfitte;
* Creo delle colonne per i migliori 25 giocatori per il giocatore A e il giocatore B che assumono i valori:
    * 1 se il giocatore Ã¨ il giocatore indicato nella colonna;
    * 0 altrimenti

In [24]:
def setBest25Players():
    players = dataframe['Winner'].value_counts().subtract(dataframe['Loser'].value_counts(), fill_value = 0).sort_values(ascending = False).index

    for p in players[:25]:
        dataframe[p+'A'] = dataframe['Winner'].apply(lambda x: int(x == p))
        dataframe[p+'B'] = dataframe['Loser'].apply(lambda x: int(x == p))
        
    dataframe['OtherA'] = dataframe['Winner'].apply(lambda x: int(x not in players[:25]))
    dataframe['OtherB'] = dataframe['Loser'].apply(lambda x: int(x not in players[:25]))

setBest25Players()

In [25]:
dataframe.head()

,csvID,ATP,Location,Tournament,Date,Series,Round,Best of,Winner,Loser,...,Kohlschreiber P.A,Kohlschreiber P.B,Simon G.A,Simon G.B,Bautista Agut R.A,Bautista Agut R.B,Verdasco F.A,Verdasco F.B,OtherA,OtherB
0,0,1.0,Brisbane,Brisbane International,2010-01-04,0,0,3.0,Gasquet R.,Nieminen J.,...,0,0,0,0,0,0,0,0,0,1
1,0,1.0,Brisbane,Brisbane International,2010-01-04,0,0,3.0,Odesnik W.,Clement A.,...,0,0,0,0,0,0,0,0,1,1
2,0,1.0,Brisbane,Brisbane International,2010-01-04,0,0,3.0,Gicquel M.,Petzschner P.,...,0,0,0,0,0,0,0,0,1,1
3,0,1.0,Brisbane,Brisbane International,2010-01-04,0,0,3.0,Falla A.,Chardy J.,...,0,0,0,0,0,0,0,0,1,1
4,0,1.0,Brisbane,Brisbane International,2010-01-04,0,0,3.0,Levy H.,Llodra M.,...,0,0,0,0,0,0,0,0,1,1

In [26]:
dataframe.to_csv('./datasets/dataframe02.csv', index = False)