<center>

# Web Intelligence

# Who will win the Tennis Australian Open 2020?

## 02 Adding New Variables

### Riccardo Spolaor (864877)

</center>

### Creazione Variabili aggiuntive

In [702]:
## Prova a usare le medie per i tornei!


import pandas as pd
import python_files.FeaturesOperations as featop

In [703]:
dataframe = pd.read_csv('./datasets/dataframe02.csv', low_memory = False)
dataframe = dataframe.reset_index(drop = True)

In [704]:
dataframe.head()

,csvID,ATP,Location,Tournament,Date,Series,Court,Round,Best of,Winner,...,ISNER J.A,ISNER J.B,MOYA C.A,MOYA C.B,DAVYDENKO N.A,DAVYDENKO N.B,GONZALEZ F.A,GONZALEZ F.B,OtherA,OtherB
0,0,1.0,2,0,2001-01-01,0,1,0,3.0,CLEMENT A.,...,0,0,0,0,0,0,0,0,1,1
1,0,1.0,2,0,2001-01-01,0,1,0,3.0,GOLDSTEIN P.,...,0,0,0,0,0,0,0,0,1,1
2,0,1.0,2,0,2001-01-01,0,1,0,3.0,HAAS T.,...,0,0,0,0,0,0,0,0,0,1
3,0,1.0,2,0,2001-01-01,0,1,0,3.0,HENMAN T.,...,0,0,0,0,0,0,0,0,1,1
4,0,1.0,2,0,2001-01-01,0,1,0,3.0,HEWITT L.,...,0,0,0,0,0,0,0,0,0,1

In [705]:
'''
def sortMatchesByDate ():
    dataframe['Index'] = dataframe.index
    dataframe.sort_values(['Date','Index'],inplace = True)
    dataframe.drop('Index', axis=1, inplace = True)
    
sortMatchesByDate()
'''

"\ndef sortMatchesByDate ():\n    dataframe['Index'] = dataframe.index\n    dataframe.sort_values(['Date','Index'],inplace = True)\n    dataframe.drop('Index', axis=1, inplace = True)\n    \nsortMatchesByDate()\n"

In [706]:
# Feature che indicano il rapporto tra due feature dei giocatori

dataframe['RankA>RankB'] = dataframe.apply(lambda x : int(x['WRank'] > x['LRank']), axis = 1)
dataframe['MaxA>MaxB'] = dataframe.apply(lambda x : int(x['MaxW'] > x['MaxL']), axis = 1)
dataframe['AvgA>AvgB'] = dataframe.apply(lambda x : int(x['AvgW'] > x['AvgL']), axis = 1)

In [707]:
#dataframe[['WRank', 'LRank', 'RankA>RankB']]

In [708]:
featop.set_player_a_vs_player_b_statistics(dataframe)

# informazione che indica se Vittorie/(Partite Giocate Tot) tra i 2 giocatori è maggiore per A o per B

In [709]:
(dataframe[dataframe['Winner'] == 'Nadal R.'].merge(
    dataframe[dataframe['Loser'] == 'Federer R.'])).append(
    dataframe[dataframe['Winner'] == 'Federer R.'].merge(
    dataframe[dataframe['Loser'] == 'Nadal R.'])).sort_values(by = 'OpponentsPlayed')[['Winner', 'Loser', 'OpponentsPlayed',
                                                                                       'OpponentsWRatioA', 'OpponentsWRatioB', 
                                                                                       'OpponentsWRatioA>OpponentsWRatioB', 
                                                                                       'Date']]

Empty DataFrame
Columns: [Winner, Loser, OpponentsPlayed, OpponentsWRatioA, OpponentsWRatioB, OpponentsWRatioA>OpponentsWRatioB, Date]
Index: []

In [710]:
'''
def setTournamentStatistics():
    
    dataframe.insert(dataframe.columns.get_loc('Loser') + 1, column = 'setsTournA', value = np.nan)
    dataframe.insert(dataframe.columns.get_loc('setsTournA') + 1, column = 'setsTournB', value = np.nan)
    dataframe.insert(dataframe.columns.get_loc('setsTournB') + 1, column = 'setsWRatioTournA', value = np.nan)
    dataframe.insert(dataframe.columns.get_loc('setsWRatioTournA') + 1, column = 'setsWRatioTournB', value = np.nan)
    dataframe.insert(dataframe.columns.get_loc('setsWRatioTournB') + 1, column = 'gamesTournA', value = np.nan)
    dataframe.insert(dataframe.columns.get_loc('gamesTournA') + 1, column = 'gamesTournB', value = np.nan)
    dataframe.insert(dataframe.columns.get_loc('gamesTournB') + 1, column = 'gamesWRatioTournA', value = np.nan)
    dataframe.insert(dataframe.columns.get_loc('gamesWRatioTournA') + 1, column = 'gamesWRatioTournB', value = np.nan)
    
    setsTournA = []
    setsTournB = []
    setsWRatioTournA = []
    setsWRatioTournB = []
    gamesTournA = []
    gamesTournB = []
    gamesWRatioTournA = []
    gamesWRatioTournB = []
    
    for _, group in dataframe.groupby(['csvID','ATP'], sort = False):
        players_played_sets = {p:0 for p in dataframe['Winner'].append(dataframe['Loser']).unique()}
        players_won_sets = {p:0 for p in dataframe['Winner'].append(dataframe['Loser']).unique()}
        
        players_played_games = {p:0 for p in dataframe['Winner'].append(dataframe['Loser']).unique()}
        players_won_games = {p:0 for p in dataframe['Winner'].append(dataframe['Loser']).unique()}

        for r in group.itertuples():
            setsTournA += [players_played_sets[r.Winner]]
            gamesTournA += [players_played_games[r.Winner]]
            
            try:
                setsWRatioTournA += [players_won_sets[r.Winner]/players_played_sets[r.Winner]]
            except:
                setsWRatioTournA += [0]
                
            try:
                gamesWRatioTournA += [players_won_games[r.Winner]/players_played_games[r.Winner]]
            except:
                gamesWRatioTournA += [0]
                
            players_played_sets[r.Winner] += (r.Lsets + r.Wsets)
            players_won_sets[r.Winner] += r.Wsets 
            
            players_played_games[r.Winner] += (r.W1 + r.W2 + r.W3 + r.W4 + r.W5 + r.L1 + r.L2 + r.L3 + r.L4 + r.L5)
            players_won_games[r.Winner] += (r.W1 + r.W2 + r.W3 + r.W4 + r.W5)


            setsTournB += [players_played_sets[r.Loser]]
            gamesTournB += [players_played_games[r.Loser]]
            try:
                setsWRatioTournB += [players_won_sets[r.Loser]/players_played_sets[r.Loser]]
            except:
                setsWRatioTournB += [0]
                
            try:
                gamesWRatioTournB += [players_won_games[r.Loser]/players_played_games[r.Loser]]
            except:
                gamesWRatioTournB += [0]
                
            players_played_sets[r.Loser] += (r.Lsets + r.Wsets)
            players_won_sets[r.Loser] += r.Lsets 
            
            players_played_games[r.Loser] += (r.W1 + r.W2 + r.W3 + r.W4 + r.W5 + r.L1 + r.L2 + r.L3 + r.L4 + r.L5)
            players_won_games[r.Loser] += (r.L1 + r.L2 + r.L3 + r.L4 + r.L5)
                                    
    dataframe['setsTournA'] = setsTournA
    dataframe['setsTournB'] = setsTournB
    dataframe['setsWRatioTournA'] = setsWRatioTournA
    dataframe['setsWRatioTournB'] = setsWRatioTournB
    dataframe['gamesTournA'] = gamesTournA
    dataframe['gamesTournB'] = gamesTournB
    dataframe['gamesWRatioTournA'] = gamesWRatioTournA
    dataframe['gamesWRatioTournB'] = gamesWRatioTournB
            
            
setTournamentStatistics()
'''

"\ndef setTournamentStatistics():\n    \n    dataframe.insert(dataframe.columns.get_loc('Loser') + 1, column = 'setsTournA', value = np.nan)\n    dataframe.insert(dataframe.columns.get_loc('setsTournA') + 1, column = 'setsTournB', value = np.nan)\n    dataframe.insert(dataframe.columns.get_loc('setsTournB') + 1, column = 'setsWRatioTournA', value = np.nan)\n    dataframe.insert(dataframe.columns.get_loc('setsWRatioTournA') + 1, column = 'setsWRatioTournB', value = np.nan)\n    dataframe.insert(dataframe.columns.get_loc('setsWRatioTournB') + 1, column = 'gamesTournA', value = np.nan)\n    dataframe.insert(dataframe.columns.get_loc('gamesTournA') + 1, column = 'gamesTournB', value = np.nan)\n    dataframe.insert(dataframe.columns.get_loc('gamesTournB') + 1, column = 'gamesWRatioTournA', value = np.nan)\n    dataframe.insert(dataframe.columns.get_loc('gamesWRatioTournA') + 1, column = 'gamesWRatioTournB', value = np.nan)\n    \n    setsTournA = []\n    setsTournB = []\n    setsWRatioTournA = []\n    setsWRatioTournB = []\n    gamesTournA = []\n    gamesTournB = []\n    gamesWRatioTournA = []\n    gamesWRatioTournB = []\n    \n    for _, group in dataframe.groupby(['csvID','ATP'], sort = False):\n        players_played_sets = {p:0 for p in dataframe['Winner'].append(dataframe['Loser']).unique()}\n        players_won_sets = {p:0 for p in dataframe['Winner'].append(dataframe['Loser']).unique()}\n        \n        players_played_games = {p:0 for p in dataframe['Winner'].append(dataframe['Loser']).unique()}\n        players_won_games = {p:0 for p in dataframe['Winner'].append(dataframe['Loser']).unique()}\n\n        for r in group.itertuples():\n            setsTournA += [players_played_sets[r.Winner]]\n            gamesTournA += [players_played_games[r.Winner]]\n            \n            try:\n                setsWRatioTournA += [players_won_sets[r.Winner]/players_played_sets[r.Winner]]\n            except:\n                setsWRatioTournA += [0]\n                \n            try:\n                gamesWRatioTournA += [players_won_games[r.Winner]/players_played_games[r.Winner]]\n            except:\n                gamesWRatioTournA += [0]\n                \n            players_played_sets[r.Winner] += (r.Lsets + r.Wsets)\n            players_won_sets[r.Winner] += r.Wsets \n            \n            players_played_games[r.Winner] += (r.W1 + r.W2 + r.W3 + r.W4 + r.W5 + r.L1 + r.L2 + r.L3 + r.L4 + r.L5)\n            players_won_games[r.Winner] += (r.W1 + r.W2 + r.W3 + r.W4 + r.W5)\n\n\n            setsTournB += [players_played_sets[r.Loser]]\n            gamesTournB += [players_played_games[r.Loser]]\n            try:\n                setsWRatioTournB += [players_won_sets[r.Loser]/players_played_sets[r.Loser]]\n            except:\n                setsWRatioTournB += [0]\n                \n            try:\n                gamesWRatioTournB += [players_won_games[r.Loser]/players_played_games[r.Loser]]\n            except:\n                gamesWRatioTournB += [0]\n                \n            players_played_sets[r.Loser] += (r.Lsets + r.Wsets)\n            players_won_sets[r.Loser] += r.Lsets \n            \n            players_played_games[r.Loser] += (r.W1 + r.W2 + r.W3 + r.W4 + r.W5 + r.L1 + r.L2 + r.L3 + r.L4 + r.L5)\n            players_won_games[r.Loser] += (r.L1 + r.L2 + r.L3 + r.L4 + r.L5)\n                                    \n    dataframe['setsTournA'] = setsTournA\n    dataframe['setsTournB'] = setsTournB\n    dataframe['setsWRatioTournA'] = setsWRatioTournA\n    dataframe['setsWRatioTournB'] = setsWRatioTournB\n    dataframe['gamesTournA'] = gamesTournA\n    dataframe['gamesTournB'] = gamesTournB\n    dataframe['gamesWRatioTournA'] = gamesWRatioTournA\n    dataframe['gamesWRatioTournB'] = gamesWRatioTournB\n            \n            \nsetTournamentStatistics()\n"

In [711]:
featop.set_fatigue(dataframe)

In [712]:
dataframe[dataframe['csvID'] == 3].merge(
    dataframe[dataframe['ATP'] == 5]).merge(
    dataframe[dataframe['Winner'] == 'Hewitt L.']).head(20)[['Winner','Loser', 'Round','W1', 'W2', 'W3', 'Wsets',
                                               'L1', 'L2', 'L3', 'Lsets','FadigueTournGamesA','FadigueTournGamesB',
                                               'FadigueTournGamesA>FadigueTournGamesB', 'FadigueTournSetsA','FadigueTournSetsB',
                                               'FadigueTournSetsA>FadigueTournSetsB']]

Empty DataFrame
Columns: [Winner, Loser, Round, W1, W2, W3, Wsets, L1, L2, L3, Lsets, FadigueTournGamesA, FadigueTournGamesB, FadigueTournGamesA>FadigueTournGamesB, FadigueTournSetsA, FadigueTournSetsB, FadigueTournSetsA>FadigueTournSetsB]
Index: []

In [713]:
featop.set_retired_walkover_last(dataframe)

In [714]:
first_nadal_walkover = dataframe[dataframe['Walkover'] == 1].merge(dataframe[dataframe['Loser'] == 'NADAL R.']).head(1)['Date']

dataframe[dataframe['Winner'] == 'NADAL R.'].append(
    dataframe[dataframe['Loser'] == 'NADAL R.']).merge(
    dataframe[dataframe['Date'] >= first_nadal_walkover[0]]).sort_values(by = 'Date')[['Winner','Loser','WalkoverLastA', 
                                                                                'WalkoverLastB', 'Walkover', 'Date']].head(5)

,Winner,Loser,WalkoverLastA,WalkoverLastB,Walkover,Date
916,LABADZE I.,NADAL R.,0,0,1,2004-04-16
0,NADAL R.,VANEK J.,1,0,0,2004-07-06
1,NADAL R.,VENTURA S.,0,0,0,2004-07-08
917,GAUDIO G.,NADAL R.,0,0,0,2004-07-09
2,NADAL R.,VASSALLO-ARGUELLO M.,0,0,0,2004-07-14

In [715]:
'''
def setTournamentStatistics():

    dataframe.insert(dataframe.columns.get_loc('Lsets') + 1, column = 'Last1A', value = np.nan)
    dataframe.insert(dataframe.columns.get_loc('Last1A') + 1, column = 'Last2A', value = np.nan)
    dataframe.insert(dataframe.columns.get_loc('Last2A') + 1, column = 'Last3A', value = np.nan)
    dataframe.insert(dataframe.columns.get_loc('Last3A') + 1, column = 'Last4A', value = np.nan)
    dataframe.insert(dataframe.columns.get_loc('Last4A') + 1, column = 'Last5A', value = np.nan)
    dataframe.insert(dataframe.columns.get_loc('Last5A') + 1, column = 'LastSetsA', value = np.nan)
    
    dataframe.insert(dataframe.columns.get_loc('LastSetsA') + 1, column = 'Last1B', value = np.nan)
    dataframe.insert(dataframe.columns.get_loc('Last1B') + 1, column = 'Last2B', value = np.nan)
    dataframe.insert(dataframe.columns.get_loc('Last2B') + 1, column = 'Last3B', value = np.nan)
    dataframe.insert(dataframe.columns.get_loc('Last3B') + 1, column = 'Last4B', value = np.nan)
    dataframe.insert(dataframe.columns.get_loc('Last4B') + 1, column = 'Last5B', value = np.nan)
    dataframe.insert(dataframe.columns.get_loc('Last5B') + 1, column = 'LastSetsB', value = np.nan)
      
    values = {'1A': [], '1B': [], '2A': [], '2B': [], '3A': [], '3B': [], '4A': [], '4B': [], '5A': [], '5B': [],
              'setsA': [], 'setsB': []}

    players_last = {p : {'1': 0, '2':0,'3':0,'4':0,'5':0,'sets':0} 
                    for p in dataframe['Winner'].append(dataframe['Loser']).unique()}

    for _, group in dataframe.groupby(['csvID','ATP'], sort = False):

        for r in group.itertuples():
            for i in '12345':
                values[i+'A'] += [players_last[r.Winner][i]]
                values[i+'B'] += [players_last[r.Loser][i]]
            values['setsA'] += [players_last[r.Winner]['sets']]
            values['setsB'] += [players_last[r.Loser]['sets']]

            players_last[r.Winner].update({'1': r.W1, '2':r.W2,'3':r.W3,'4':r.W4,'5':r.W5,'sets':r.Wsets}) 
            players_last[r.Loser].update({'1': r.L1, '2':r.L2,'3':r.L3,'4':r.L4,'5':r.L5,'sets':r.Lsets})

    for i in '12345':
        dataframe['Last'+i+'A'] = values[i+'A']
        dataframe['Last'+i+'B'] = values[i+'B']
    dataframe['LastSetsA'] = values['setsA']
    dataframe['LastSetsB'] = values['setsB']
                     
            
            
setTournamentStatistics()
'''

"\ndef setTournamentStatistics():\n\n    dataframe.insert(dataframe.columns.get_loc('Lsets') + 1, column = 'Last1A', value = np.nan)\n    dataframe.insert(dataframe.columns.get_loc('Last1A') + 1, column = 'Last2A', value = np.nan)\n    dataframe.insert(dataframe.columns.get_loc('Last2A') + 1, column = 'Last3A', value = np.nan)\n    dataframe.insert(dataframe.columns.get_loc('Last3A') + 1, column = 'Last4A', value = np.nan)\n    dataframe.insert(dataframe.columns.get_loc('Last4A') + 1, column = 'Last5A', value = np.nan)\n    dataframe.insert(dataframe.columns.get_loc('Last5A') + 1, column = 'LastSetsA', value = np.nan)\n    \n    dataframe.insert(dataframe.columns.get_loc('LastSetsA') + 1, column = 'Last1B', value = np.nan)\n    dataframe.insert(dataframe.columns.get_loc('Last1B') + 1, column = 'Last2B', value = np.nan)\n    dataframe.insert(dataframe.columns.get_loc('Last2B') + 1, column = 'Last3B', value = np.nan)\n    dataframe.insert(dataframe.columns.get_loc('Last3B') + 1, column = 'Last4B', value = np.nan)\n    dataframe.insert(dataframe.columns.get_loc('Last4B') + 1, column = 'Last5B', value = np.nan)\n    dataframe.insert(dataframe.columns.get_loc('Last5B') + 1, column = 'LastSetsB', value = np.nan)\n      \n    values = {'1A': [], '1B': [], '2A': [], '2B': [], '3A': [], '3B': [], '4A': [], '4B': [], '5A': [], '5B': [],\n              'setsA': [], 'setsB': []}\n\n    players_last = {p : {'1': 0, '2':0,'3':0,'4':0,'5':0,'sets':0} \n                    for p in dataframe['Winner'].append(dataframe['Loser']).unique()}\n\n    for _, group in dataframe.groupby(['csvID','ATP'], sort = False):\n\n        for r in group.itertuples():\n            for i in '12345':\n                values[i+'A'] += [players_last[r.Winner][i]]\n                values[i+'B'] += [players_last[r.Loser][i]]\n            values['setsA'] += [players_last[r.Winner]['sets']]\n            values['setsB'] += [players_last[r.Loser]['sets']]\n\n            players_last[r.Winner].update({'1': r.W1, '2':r.W2,'3':r.W3,'4':r.W4,'5':r.W5,'sets':r.Wsets}) \n            players_last[r.Loser].update({'1': r.L1, '2':r.L2,'3':r.L3,'4':r.L4,'5':r.L5,'sets':r.Lsets})\n\n    for i in '12345':\n        dataframe['Last'+i+'A'] = values[i+'A']\n        dataframe['Last'+i+'B'] = values[i+'B']\n    dataframe['LastSetsA'] = values['setsA']\n    dataframe['LastSetsB'] = values['setsB']\n                     \n            \n            \nsetTournamentStatistics()\n"

In [716]:
#dataframe[['Winner', 'Loser','Tournament','Round','W1','W2','W3', 'Wsets', 'L1','L2','L3', 'Lsets', 'Last1A', 'Last2A', 'Last3A', 'LastSetsA', 'Last1B', 'Last2B', 'Last3B', 'LastSetsB']].head(30)

In [717]:
featop.set_played_matches(dataframe)

In [718]:
dataframe[dataframe['Winner'] == 'NADAL R.'].append(
    dataframe[dataframe['Loser'] == 'NADAL R.']).sort_values(by='Date').head(20)[['Winner', 'Loser', 'PlayedA', 'PlayedB', 
                                                                                  'Date','WonRatioA','WonRatioB']]

,Winner,Loser,PlayedA,PlayedB,Date,WonRatioA,WonRatioB
3994,NADAL R.,DELGADO R.,0,26,2002-04-29,0.000000,0.384615
4007,ROCHUS O.,NADAL R.,42,1,2002-04-29,0.380952,1.000000
6717,NADAL R.,KUCERA K.,2,75,2003-04-15,0.500000,0.560000
6731,NADAL R.,COSTA A.,3,118,2003-04-16,0.666667,0.576271
6741,CORIA G.,NADAL R.,100,4,2003-04-17,0.630000,0.750000
6775,NADAL R.,MARIN J.A.,5,25,2003-04-22,0.600000,0.440000
6790,CORRETJA A.,NADAL R.,111,6,2003-04-23,0.612613,0.666667
6973,NADAL R.,MATHIEU P.H.,7,44,2003-05-12,0.571429,0.545455
7002,NADAL R.,MOYA C.,8,172,2003-05-14,0.625000,0.703488
7016,GAUDIO G.,NADAL R.,133,9,2003-05-15,0.616541,0.666667
7337,NADAL R.,ANCIC M.,10,29,2003-06-23,0.600000,0.413793
7401,NADAL R.,CHILDS L.,11,4,2003-06-25,0.636364,0.250000
7432,SRICHAPHAN P.,NADAL R.,122,12,2003-06-27,0.573770,0.666667
7469,NADAL R.,EL AYNAOUI Y.,13,161,2003-07-08,0.615385,0.602484
7478,NADAL R.,PORTAS A.,14,112,2003-07-09,0.642857,0.428571
7486,LAPENTTI N.,NADAL R.,134,15,2003-07-11,0.544776,0.666667
7595,NADAL R.,PETZSCHNER P.,16,1,2003-07-15,0.625000,0.000000
7616,GONZALEZ F.,NADAL R.,102,17,2003-07-16,0.578431,0.647059
7736,NADAL R.,VOINEA A.,18,85,2003-07-22,0.611111,0.435294
7743,NADAL R.,PUERTA M.,19,30,2003-07-23,0.631579,0.200000

In [719]:
print(dataframe[dataframe['Winner'] == 'NADAL R.'].append(dataframe[dataframe['Loser'] == 'NADAL R.']).shape[0])

dataframe[dataframe['Winner'] == 'NADAL R.'].append(
    dataframe[dataframe['Loser'] == 'NADAL R.']).sort_values(by='Date').tail(1)[['Winner', 'Loser', 'PlayedA', 'PlayedB', 'Date',
                                                                               'WonRatioA','WonRatioB']]

1145

,Winner,Loser,PlayedA,PlayedB,Date,WonRatioA,WonRatioB
51940,NADAL R.,TSITSIPAS S.,1144,158,2019-11-15,0.826049,0.613924

In [720]:
featop.set_played_matches_by_court(dataframe)

In [721]:
dataframe[dataframe['Winner'] == 'NADAL R.'].append(
    dataframe[dataframe['Loser'] == 'NADAL R.']).merge(
    dataframe[dataframe['Hard'] == 1]).sort_values(by='Date').head(10)[['Winner', 'Loser', 'PlayedCourtA', 'PlayedCourtB', 'Date',
                                                                               'WonRatioCourtA','WonRatioCourtB']]

,Winner,Loser,PlayedCourtA,PlayedCourtB,Date,WonRatioCourtA,WonRatioCourtB
0,NADAL R.,VICENTE F.,0,53,2003-08-27,0.000000,0.452830
447,EL AYNAOUI Y.,NADAL R.,70,1,2003-08-29,0.571429,1.000000
448,CORRETJA A.,NADAL R.,53,2,2003-10-13,0.490566,0.500000
449,ASCIONE T.,NADAL R.,3,3,2004-01-06,0.333333,0.333333
1,NADAL R.,SCHALKEN S.,4,99,2004-01-13,0.250000,0.545455
2,NADAL R.,ANCIC M.,5,31,2004-01-14,0.400000,0.387097
3,NADAL R.,CARRAZ G.,6,22,2004-01-15,0.500000,0.500000
4,NADAL R.,NOVAK J.,7,100,2004-01-16,0.571429,0.620000
450,HRBATY D.,NADAL R.,92,8,2004-01-17,0.543478,0.625000
5,NADAL R.,TABARA M.,9,24,2004-01-20,0.555556,0.458333

In [722]:
print(dataframe[dataframe['Winner'] == 'NADAL R.'].append(dataframe[dataframe['Loser'] == 'NADAL R.']).merge(
    dataframe[dataframe['Hard'] == 1]).shape[0])

dataframe[dataframe['Winner'] == 'NADAL R.'].append(
    dataframe[dataframe['Loser'] == 'NADAL R.']).merge(
    dataframe[dataframe['Hard'] == 1]).sort_values(
        by='Date').tail(1)[['Winner', 'Loser', 'PlayedCourtA', 'PlayedCourtB', 'Date', 'WonRatioCourtA','WonRatioCourtB']]

578

,Winner,Loser,PlayedCourtA,PlayedCourtB,Date,WonRatioCourtA,WonRatioCourtB
446,NADAL R.,TSITSIPAS S.,577,103,2019-11-15,0.772964,0.601942

In [723]:
featop.set_players_last_5_statistics(dataframe)

In [724]:
with pd.option_context('display.max_columns',None):
    display(
        dataframe[dataframe['Winner'] == 'NADAL R.'].append(
            dataframe[dataframe['Loser'] == 'NADAL R.']).sort_values(by='Date').head(10)[['Winner', 'Loser',
                                                                                  'W1', 'W2', 'W3', 'W4', 'W5', 'Wsets',
                                                                                  '5_1MeanA', '5_2MeanA',
                                                                                  '5_3MeanA', '5_4MeanA', '5_5MeanA',
                                                                                  '5_setsMeanA',
                                                                                  'L1', 'L2', 'L3', 'L4', 'L5', 'Lsets',
                                                                                  '5_1MeanB', '5_2MeanB',
                                                                                  '5_3MeanB', '5_4MeanB', '5_5MeanB',
                                                                                  '5_setsMeanB']])

,Winner,Loser,W1,W2,W3,W4,W5,Wsets,5_1MeanA,5_2MeanA,5_3MeanA,5_4MeanA,5_5MeanA,5_setsMeanA,L1,L2,L3,L4,L5,Lsets,5_1MeanB,5_2MeanB,5_3MeanB,5_4MeanB,5_5MeanB,5_setsMeanB
3994,NADAL R.,DELGADO R.,6.0,6.0,0.0,0.0,0.0,2.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,4.0,4.0,0.0,0.0,0.0,0.0,4.000000,3.600000,2.200000,1.0,0.6,0.900000
4007,ROCHUS O.,NADAL R.,6.0,6.0,0.0,0.0,0.0,2.0,4.300000,4.400000,2.600000,0.0,0.0,1.200000,2.0,2.0,0.0,0.0,0.0,0.0,6.000000,6.000000,0.000000,0.0,0.0,2.000000
6717,NADAL R.,KUCERA K.,6.0,6.0,0.0,0.0,0.0,2.0,4.000000,4.000000,0.000000,0.0,0.0,1.000000,1.0,2.0,0.0,0.0,0.0,0.0,5.700000,5.100000,0.400000,0.0,0.0,1.500000
6731,NADAL R.,COSTA A.,7.0,6.0,0.0,0.0,0.0,2.0,4.666667,4.666667,0.000000,0.0,0.0,1.333333,5.0,3.0,0.0,0.0,0.0,0.0,5.800000,4.600000,2.300000,0.1,0.3,1.500000
6741,CORIA G.,NADAL R.,7.0,6.0,0.0,0.0,0.0,2.0,5.600000,5.100000,2.200000,0.0,0.0,1.500000,6.0,2.0,0.0,0.0,0.0,0.0,5.250000,5.000000,0.000000,0.0,0.0,1.500000
6775,NADAL R.,MARIN J.A.,6.0,0.0,0.0,0.0,0.0,1.0,5.400000,4.400000,0.000000,0.0,0.0,1.200000,0.0,0.0,0.0,0.0,0.0,0.0,4.300000,3.400000,1.200000,0.0,0.0,0.800000
6790,CORRETJA A.,NADAL R.,3.0,6.0,6.0,0.0,0.0,2.0,5.300000,4.100000,1.500000,0.3,0.0,0.900000,6.0,2.0,1.0,0.0,0.0,1.0,5.500000,3.666667,0.000000,0.0,0.0,1.166667
6973,NADAL R.,MATHIEU P.H.,7.0,6.0,0.0,0.0,0.0,2.0,5.571429,3.428571,0.142857,0.0,0.0,1.142857,5.0,4.0,0.0,0.0,0.0,0.0,4.500000,5.200000,1.900000,0.0,0.0,1.200000
7002,NADAL R.,MOYA C.,7.0,6.0,0.0,0.0,0.0,2.0,5.750000,3.750000,0.125000,0.0,0.0,1.250000,5.0,4.0,0.0,0.0,0.0,0.0,5.900000,5.500000,1.800000,0.3,0.0,1.600000
7016,GAUDIO G.,NADAL R.,6.0,6.0,0.0,0.0,0.0,2.0,5.700000,4.800000,4.000000,0.0,0.0,1.700000,2.0,2.0,0.0,0.0,0.0,0.0,5.888889,4.000000,0.111111,0.0,0.0,1.333333

In [725]:
dataframe.columns.values

array(['csvID', 'ATP', 'Location', 'Tournament', 'Date', 'Series',
       'Court', 'Round', 'Best of', 'Winner', 'Loser', 'PlayedA',
       'PlayedB', 'WonRatioA', 'WonRatioB', 'WRank', 'WRankAdded',
       'LRank', 'LRankAdded', 'W1', 'L1', 'W2', 'L2', 'W3', 'L3', 'W4',
       'L4', 'W5', 'L5', 'Wsets', 'Lsets', 'FadigueTournGamesA',
       'FadigueTournGamesB', 'FadigueTournSetsA', 'FadigueTournSetsB',
       'WPts', 'WPtsAdded', 'LPts', 'LPtsAdded', 'MaxW', 'MaxWAdded',
       'MaxL', 'PlayedCourtA', 'PlayedCourtB', 'WonRatioCourtA',
       'WonRatioCourtB', 'MaxLAdded', 'AvgW', 'AvgWAdded', 'AvgL',
       'AvgLAdded', 'Carpet', 'Clay', 'Grass', 'Hard', 'Awarded',
       'Completed', 'Disqualified', 'Retired', 'Sched', 'Walkover',
       'FEDERER R.A', 'FEDERER R.B', 'NADAL R.A', 'NADAL R.B',
       'DJOKOVIC N.A', 'DJOKOVIC N.B', 'MURRAY A.A', 'MURRAY A.B',
       'RODDICK A.A', 'RODDICK A.B', 'FERRER D.A', 'FERRER D.B',
       'BERDYCH T.A', 'BERDYCH T.B', 'HEWITT L.A', 'HEWITT L.B',
       'DEL POTRO J. M.A', 'DEL POTRO J. M.B', 'TSONGA J.W.A',
       'TSONGA J.W.B', 'CILIC M.A', 'CILIC M.B', 'WAWRINKA S.A',
       'WAWRINKA S.B', 'GASQUET R.A', 'GASQUET R.B', 'NISHIKORI K.A',
       'NISHIKORI K.B', 'MONFILS G.A', 'MONFILS G.B', 'FERRERO J.C.A',
       'FERRERO J.C.B', 'ROBREDO T.A', 'ROBREDO T.B', 'NALBANDIAN D.A',
       'NALBANDIAN D.B', 'RAONIC M.A', 'RAONIC M.B', 'AGASSI A.A',
       'AGASSI A.B', 'HAAS T.A', 'HAAS T.B', 'ISNER J.A', 'ISNER J.B',
       'MOYA C.A', 'MOYA C.B', 'DAVYDENKO N.A', 'DAVYDENKO N.B',
       'GONZALEZ F.A', 'GONZALEZ F.B', 'OtherA', 'OtherB', 'RankA>RankB',
       'MaxA>MaxB', 'AvgA>AvgB', 'OpponentsPlayed', 'OpponentsWRatioA',
       'OpponentsWRatioB', 'OpponentsWRatioA>OpponentsWRatioB',
       'FadigueTournGamesA>FadigueTournGamesB',
       'FadigueTournSetsA>FadigueTournSetsB', 'WalkoverLastA',
       'WalkoverLastB', 'RetiredLastA', 'RetiredLastB',
       'WonRatioA>WonRatioB', 'WonRatioCourtA>WonRatioCourtB', '5_1MeanA',
       '5_2MeanA', '5_3MeanA', '5_4MeanA', '5_5MeanA', '5_setsMeanA',
       '5_1MeanB', '5_2MeanB', '5_3MeanB', '5_4MeanB', '5_5MeanB',
       '5_setsMeanB'], dtype=object)

In [726]:
dataframe.to_csv('./datasets/dataframe05.csv', index = False)

In [727]:
extradf = pd.read_csv('./datasets/ATP.csv', low_memory = False)

In [728]:
extradf.drop(extradf[extradf['loser_name'] == ' '].index, inplace = True, axis = 0)

In [729]:
def give_new_name(p):
    splitted = p.split(' ')
    newstring = splitted[-1] + ' ' + ' '.join([n[0] + '.' for n in splitted[:-1]])
    return newstring.upper()

def give_new_name_2(p):
    splitted = p.split(' ')
    if (len(splitted)>2):
        newstring = splitted[-2] + ' ' + splitted[-1] + ' ' + ' '.join([n[0] + '.' for n in splitted[:-2]])
        return newstring.upper()
    else:
        return np.nan

def give_new_name_3(p):
    splitted = p.split(' ')
    newstring = splitted[-1] + ' ' + ''.join([n[0] + '.' for n in splitted[:-1]])
    return newstring.upper()

def give_new_name_4(p):
    splitted = p.split(' ')
    if (len(splitted)>2):
        newstring = splitted[-2] + '-' + splitted[-1] + ' ' + ' '.join([n[0] + '.' for n in splitted[:-2]])
        return newstring.upper()
    else:
        return np.nan
    
def give_new_name_5(p):
    splitted = p.split(' ')
    if (len(splitted)>2):
        newstring = splitted[-2] + ' ' + splitted[-1] + ' ' + ''.join([n[0] + '.' for n in splitted[:-2]])
        return newstring.upper()
    else:
        return np.nan
    
def give_new_name_5(p):
    splitted = p.split(' ')
    if (len(splitted)>2):
        newstring = splitted[-2] + ' ' + splitted[-1] + ' ' + ''.join([n[0] + '.' for n in splitted[:-2]])
        return newstring.upper()
    else:
        return np.nan
    
extradf['winner_name1'] = extradf['winner_name'].apply(give_new_name)
extradf['loser_name1'] = extradf['loser_name'].apply(give_new_name)

extradf['winner_name2'] = extradf['winner_name'].apply(give_new_name_2)
extradf['loser_name2'] = extradf['loser_name'].apply(give_new_name_2)
    
extradf['winner_name3'] = extradf['winner_name'].apply(give_new_name_3)
extradf['loser_name3'] = extradf['loser_name'].apply(give_new_name_3)

extradf['winner_name4'] = extradf['winner_name'].apply(give_new_name_4)
extradf['loser_name4'] = extradf['loser_name'].apply(give_new_name_4)

extradf['winner_name5'] = extradf['winner_name'].apply(give_new_name_5)
extradf['loser_name5'] = extradf['loser_name'].apply(give_new_name_5)

In [730]:
extradf['winner_name3']

0           COULTHARD R.
1               BROWN J.
2                CASE R.
3               STONE A.
4             JACQUES W.
5             PETTMAN M.
6              BELKIN M.
7             MOORE B.P.
8             COGHLAN W.
9             POLLARD G.
10         KAMIWAZUMI J.
11              LLOYD B.
12             FRASER N.
13               GUSE M.
14            ORANTES M.
15            RUFFELS R.
16              SMITH D.
17             WILSON R.
18           SUGIARTO S.
19               DENT P.
20              STUBS C.
21             FRASER J.
22           STILWELL G.
23             CREALY D.
24           FLETCHER I.
25            ADDISON T.
26              SAKAI T.
27             KELDIE R.
28           GERAGHTY B.
29              BRENT R.
               ...
169660        FEDERER R.
169661      TSITSIPAS S.
169662        FEDERER R.
169663          DJERE L.
169664          RAMOS A.
169665    ALIASSIME F.A.
169666        BAENA R.C.
169667         WILD T.S.
169668    TRUNGELLITI M.
169669          MUNAR J.
169670          GARIN C.
169671         SONEGO L.
169672      LONDERO J.I.
169673        DELLIEN H.
169674           RUUD C.
169675          DJERE L.
169676    ALIASSIME F.A.
169677          PELLA G.
169678    TRUNGELLITI M.
169679          GARIN C.
169680          MAYER L.
169681        DELLIEN H.
169682           RUUD C.
169683          DJERE L.
169684          PELLA G.
169685          GARIN C.
169686           RUUD C.
169687          PELLA G.
169688          GARIN C.
169689          PELLA G.
Name: winner_name3, Length: 169689, dtype: object

In [731]:
players_hands = extradf[['winner_name1','winner_hand']].drop_duplicates().append(
    extradf[['loser_name1','loser_hand']].rename(columns = {'loser_name1': 'winner_name1',
                                                                             'loser_hand': 'winner_hand'}), 
    ignore_index = True).drop_duplicates()

In [732]:
import numpy as np
players_hands['winner_hand'] = players_hands['winner_hand'].apply(lambda x:np.nan if x == 'U' else x)
players_hands['winner_hand'].dropna(inplace = True, axis = 0)

In [733]:
players_hands_dict = {p:np.nan for p in players_hands['winner_name1']}
for i in players_hands.itertuples():
    players_hands_dict[i.winner_name1] = i.winner_hand

In [734]:
players_hands_dict

{'COULTHARD R.': 'R',
 'BROWN J.': 'R',
 'CASE R.': 'R',
 'STONE A.': 'R',
 'JACQUES W.': 'R',
 'PETTMAN M.': 'R',
 'BELKIN M.': 'R',
 'MOORE B. P.': 'R',
 'COGHLAN W.': 'R',
 'POLLARD G.': 'R',
 'KAMIWAZUMI J.': 'R',
 'LLOYD B.': 'R',
 'FRASER N.': 'L',
 'GUSE M.': 'R',
 'ORANTES M.': 'L',
 'RUFFELS R.': 'R',
 'SMITH D.': 'R',
 'WILSON R.': 'R',
 'SUGIARTO S.': 'R',
 'DENT P.': 'R',
 'STUBS C.': 'R',
 'FRASER J.': 'R',
 'STILWELL G.': 'R',
 'CREALY D.': 'R',
 'FLETCHER I.': 'R',
 'ADDISON T.': 'R',
 'SAKAI T.': 'L',
 'KELDIE R.': 'R',
 'GERAGHTY B.': nan,
 'BRENT R.': 'R',
 'BOWREY B.': 'R',
 'GISBERT J.': 'R',
 'LAVER R.': 'R',
 'LUTZ R.': 'R',
 'DRYSDALE C.': 'R',
 'OSBORNE J.': 'R',
 'GRAEBNER C.': 'R',
 'ANDERSON M.': 'R',
 'ROCHE T.': 'L',
 'OKKER T.': 'R',
 'RIESSEN M.': 'R',
 'STOLLE F.': 'R',
 'SEGURA P.': 'R',
 'OLMEDO A.': 'R',
 'GIMENO A.': 'R',
 'MOORE R.': 'R',
 'GORMAN T.': 'R',
 'BUCHHOLZ E. B.': 'R',
 'DELL D.': 'R',
 'GONZALES R. P.': 'R',
 'TAYLOR R.': nan,
 'PASARELL C.': 'R',
 'MCMANUS J.': nan,
 'ROSEWALL K.': 'R',
 'TAYLOR G.': 'R',
 'EMERSON R.': 'R',
 'LEONARD T.': 'R',
 'NEWCOMBE J.': 'R',
 'TIDBALL S.': 'R',
 'PILIC N.': 'L',
 'BARTHES P.': 'R',
 'ASHE A.': 'R',
 'MOZUR T.': 'R',
 'HARRIS W.': 'R',
 'FILLOL J.': 'R',
 'MARCIAL A.': 'R',
 'BUDING I.': 'R',
 'GUERRERO G.': 'L',
 'MANDARINO J.': 'R',
 'UNKNOWN U.': nan,
 'PENA A.': 'R',
 'HICKEY M.': 'R',
 'MUNOZ A.': 'R',
 'KOCH T.': 'L',
 'BRUGUERA L.': 'R',
 'ELSCHENBROICH H.': 'R',
 'JAUFFRET F.': 'R',
 'CASTIGLIANO E.': 'R',
 'FLETCHER K.': 'R',
 'VELASCO J.': 'R',
 'CARMICHAEL B.': 'R',
 'CRUZ E.': 'R',
 'MUKHERJEA J.': 'R',
 'ARILLLA J. L.': 'R',
 'CHI P. R.': 'R',
 'KRISHNAN R.': 'R',
 'MATTEO E. D.': 'R',
 'MULLIGAN M.': 'R',
 'BARRETT J.': 'L',
 'WARD J.': 'R',
 'COX M.': 'L',
 'LLOYD D.': 'R',
 'WOOLDRIDGE K.': 'R',
 'AYALA L.': 'R',
 'HOWE B.': 'R',
 'DAVIDSON O.': 'L',
 'GARNER G.': 'R',
 'SEIXAS E. V.': 'R',
 'MCKINLEY C.': 'R',
 'ULRICH T.': 'L',
 'MCKINLEY R.': 'R',
 'OBRYANT D.': 'R',
 'GERKEN P.': 'R',
 'CORNEJO P.': 'R',
 'SCOTT G.': 'R',
 'EDLEFSEN T.': 'R',
 'MAYO J. L.': 'R',
 'SHARPE J.': 'R',
 'RUSSELL D. R.': 'R',
 'RALSTON D.': 'R',
 'HOLMBERG R.': 'R',
 'LARA M.': 'R',
 'STOCKTON D.': 'R',
 'PALAFOX A.': 'R',
 'HUTCHINS P.': 'R',
 'BOROWIAK J.': 'R',
 'CURTIS P.': 'R',
 'BILLINGTON A.': 'R',
 'DILLEN E. V.': 'R',
 'ROBBINS F.': 'R',
 'LEACH R.': 'L',
 'KUKI J.': 'R',
 'COLLINS W.': 'R',
 'NEELY A.': 'R',
 'ESTEP M.': 'R',
 'HEWITT B.': 'R',
 'KNIGHT D.': 'R',
 'COLSON B.': 'R',
 'BARTH R.': 'R',
 'PASARELL S.': 'R',
 'FISHBACH P.': 'R',
 'KELLY P.': 'R',
 'VAZQUEZ M. T.': 'R',
 'WALTZ J.': 'R',
 'RICHEY C.': 'R',
 'GOLDMAN R.': 'R',
 'GOELTZ B.': 'R',
 'HOSE H.': 'R',
 'SMITH S.': 'R',
 'BLECKINGER D.': 'R',
 'BULL A.': 'R',
 'SEEWAGEN B.': 'R',
 'LALL P.': 'R',
 'III C. S.': 'R',
 'BARANYI S.': 'R',
 'LIKHACHEV S.': 'R',
 'HOLECEK M.': nan,
 'MARMUREANU P.': 'R',
 'AGUIRRE E.': nan,
 'BARCLAY J. C.': 'R',
 'METREVELI A.': 'R',
 'MONTRENAUD B.': 'R',
 'SZOKE P.': 'R',
 'LECLERCQ M.': 'R',
 'SZIKSZAI A.': nan,
 'KAKOULIA T.': 'R',
 'BATTRICK G.': 'R',
 'COURCOL J.': 'R',
 'LEJUS T.': 'R',
 'POHMANN H. J.': 'R',
 'CONTET D.': 'R',
 'GOVEN G.': 'R',
 'MOLINA I.': 'L',
 'GASIOREK W.': 'R',
 'EGOROV V.': 'R',
 'HOMBERGEN P.': 'R',
 'BEUST P.': 'R',
 'ROUYER J. L.': 'R',
 'DROSSART E.': 'R',
 'PIETRANGELI N.': 'R',
 'ALEXANDER J.': 'R',
 'KURUCZ A.': 'R',
 'WERREN M.': 'R',
 'KUKAL J.': 'R',
 'KODES J.': 'R',
 'MCMILLAN F.': 'R',
 'WATANABE K.': 'R',
 'KUBE B.': nan,
 'FASSBENDER J.': 'R',
 'GULYAS I.': 'R',
 'MAUD R.': 'R',
 'BUNGERT W.': 'R',
 'PLOTZ H. J.': 'R',
 'PANATTA A.': 'R',
 'FITZGIBBON H.': 'R',
 'FOX A.': 'R',
 'FAIRLIE B.': 'R',
 'MERLO G.': 'R',
 'CHANFREAU J. B.': 'R',
 'SAYA R.': nan,
 'MASO G. D.': 'R',
 'DOMENICO M. D.': 'R',
 'MAIOLI G.': 'R',
 'KALOGEROPOULOS N.': 'R',
 'TOCI P.': 'R',
 'NASTASE I.': 'R',
 'BRAVO J. P.': 'R',
 'VARGA G.': 'R',
 'CROTTA V.': 'R',
 'GILTINAN B.': 'R',
 'TIRIAC I.': 'R',
 'JOVANOVIC B.': 'R',
 'OLIVIER J. P.': 'R',
 'WEATHERLEY K.': 'R',
 'DOMINGUEZ P.': 'L',
 'CLIFTON J.': 'R',
 'DUXIN C.': 'R',
 'JOLY P.': 'R',
 'MATHEU F.': 'R',
 'DERASSE E.': nan,
 'MEYER J. P.': 'R',
 'GROZDANOVITCH D.': nan,
 'PAISH J.': 'L',
 'PALA F.': 'L',
 'SHAFEI I. E.': 'R',
 'MCCABE E.': nan,
 'LUNDQUIST J. E.': 'R',
 'HERDY D.': 'R',
 'LAUDIN M.': 'R',
 'PARUN O.': 'R',
 'ULRICH J.': 'R',
 'DARMON P.': 'R',
 'LESCHLY J.': 'L',
 'SANTANA M.': 'R',
 'SHERMAN R.': nan,
 'IRVINE H. H.': 'R',
 'STROBL P.': 'R',
 'WATANABE I.': 'R',
 'SPEAR N.': 'R',
 'PAWLIK L.': nan,
 'KORPAS A.': 'R',
 'FRANULOVIC Z.': 'R',
 'RYAN T.': 'R',
 'BENGTSON O. N.': 'R',
 'SANGSTER M.': 'R',
 'KOROTKOV V.': 'R',
 'BLUETT G.': 'R',
 'GUZMAN P.': 'R',
 'HOAD L.': 'R',
 'ILES C.': 'R',
 'GENTIL F.': 'R',
 'PROISY P.': 'R',
 'CHRISTENSEN T.': 'R',
 'PILET G.': 'R',
 'DRON S.': 'R',
 'STURDZA D.': 'R',
 'ZULETA E.': nan,
 'GRONCKEL C. D.': 'R',
 'LEWANDOWSKI M.': 'L',
 'SEGAL A.': 'L',
 'COOPER A.': nan,
 'OLANDER L.': 'R',
 'ANDREW J.': 'R',
 'VAZQUEZ T.': nan,
 'MANDARINO E.': 'R',
 'YASHMAKOV K.': nan,
 'VELEV S.': nan,
 'GENOV L.': nan,
 'OSUNA R.': 'R',
 'OLVERA M.': 'R',
 'PABST O.': nan,
 'DYGGVE P. P.': nan,
 'JOKINEN T.': nan,
 'PINTO A. V.': nan,
 'AMPON F.': nan,
 'MINOTRA S.': nan,
 'MUKERJEA J.': nan,
 'FERDINANDS R.': nan,
 'KUMARA S.': nan,
 'AKBARI H.': nan,
 'AKBARI T.': 'R',
 'DAVIDMAN E.': nan,
 'LANDAU P.': nan,
 'KONISHI I.': nan,
 'PRYDZ F.': nan,
 'BADEN F.': nan,
 'ELVIK N.': nan,
 'AZMAN S. A.': nan,
 'PINTO B.': nan,
 'SALOMAN F.': nan,
 'NERELL H.': 'R',
 'MARZANO P.': 'R',
 'MISRA G.': 'R',
 'AMRITRAJ A.': 'R',
 'MISRA S. P.': nan,
 'DAWOUDI A. E.': 'R',
 'SONBOL M. E.': nan,
 'DEYRO R.': nan,
 'LUU H. D.': nan,
 'VO V. T.': nan,
 'KIM D. H.': 'R',
 'CHUNG Y. H.': nan,
 'NGODRELLA W.': 'R',
 'MATTHEWS S.': 'R',
 'LICIS A.': 'R',
 'KUHNKE C.': 'R',
 'GARDINER A.': 'R',
 'YANAGI K.': 'R',
 'TATE D.': nan,
 'ZARAZUA V.': nan,
 'ALVAREZ W.': 'R',
 'GISBERT J. M.': nan,
 'BERNER G.': 'R',
 'JACKSON P.': nan,
 'HORDIJK J.': 'R',
 'FLEURY N.': nan,
 'BLANKE E.': nan,
 'RYBARCZYK M.': 'R',
 'STABHOLZ J.': 'R',
 'KOUDELKA S.': nan,
 'POKORNY P.': 'R',
 'COOPER J.': nan,
 'PAUL B.': 'R',
 'ZEDNIK V.': 'R',
 'NOWICKI T.': 'R',
 'BARTLETT J.': 'R',
 'PALMIERI S.': 'R',
 'GUERRY Z.': 'R',
 'MCDONALD J.': 'R',
 'SACK L.': nan,
 'OCHOA A.': nan,
 'MCNAIR F.': 'R',
 'LANGRE P.': nan,
 'KROG R.': 'R',
 'HOWARD G. T.': 'R',
 'HARMON D.': nan,
 'HAINLINE J.': 'R',
 'CORNEJO A.': 'R',
 'BURWASH P.': 'R',
 'SCHLOSS L.': 'R',
 'STALDER T.': nan,
 'GANZABAL J.': 'R',
 'TAJENAR M.': nan,
 'FAUQUIER H.': 'R',
 'CARPENTER K.': 'R',
 'FLOOD B.': nan,
 'SPRENGLEMEYER M.': 'R',
 'MONAN B.': nan,
 'BROWN D.': 'R',
 'BINNS K.': 'R',
 'HERNANDO R.': 'R',
 'TUTVIN F.': 'R',
 'POSPISIL T.': nan,
 'NITSCHE B.': nan,
 'SINGH J.': 'R',
 'COURCOL J. P.': nan,
 'BLOCHER W.': 'R',
 'YEOMANS J.': nan,
 'TYM W.': 'R',
 'TAVARES L. F.': 'R',
 'MORENO J.': 'R',
 'MOREAU B.': nan,
 'MASTERS G.': 'R',
 'GUERRERO J.': 'R',
 'GARDNER J.': 'R',
 'ZAHR H.': 'R',
 'JEMSBY P.': 'R',
 'VILAS G.': 'L',
 'STUART K.': 'R',
 'SEDGMAN F.': 'R',
 'NEELY N.': 'R',
 'RAHIM H.': 'R',
 'KOBAYASHI I.': nan,
 'IQBAL M.': 'R',
 'NGUYEN V. T.': nan,
 'VO V. B.': nan,
 'BETANCUR A.': 'R',
 'MEILER K.': 'R',
 'AMRITRAJ V.': 'R',
 'MENON S.': nan,
 'BROWN W.': 'R',
 'PERALTA R.': 'R',
 'TRUCHI F.': nan,
 'KARY H.': 'L',
 'MACKAY B.': 'R',
 'FREER B.': 'R',
 'SCHRODER D.': 'R',
 'HEDELUND C. E.': nan,
 'GAVRILIDIS P.': nan,
 'MARCU V.': nan,
 'MURESAN S.': 'R',
 'SAILA P.': 'R',
 'PATTISON A.': 'R',
 'DIEPRAAM K.': 'R',
 'SAUL J.': 'R',
 'BERTRAM B.': 'R',
 'BURGENER M.': 'R',
 'FROEHLING F.': 'R',
 'CRAMER P.': 'R',
 'ALVAREZ L.': 'R',
 'KREISS M.': 'R',
 'WARWICK K.': 'R',
 'SOETERS P.': nan,
 'SCHMITZ F.': 'R',
 'HEMMES F.': 'R',
 'SCHULTHEISS D.': nan,
 'MEYER C.': 'R',
 'LOIZEAU J. P.': nan,
 'LOCKINGTON U.': nan,
 'HOSKOWETZ R.': 'R',
 'ELZER H.': nan,
 'HREBEC J.': 'R',
 'GOTTSCHALK U.': nan,
 'RUSSELL R.': 'L',
 'ILAHI M.': 'R',
 'HIGGINS W.': 'R',
 'RAMIREZ R.': nan,
 'CONNORS J.': 'L',
 'COUDER J.': 'R',
 'HOLMSTROM B.': 'R',
 'DOERNER P.': 'R',
 'DIBLEY C.': 'R',
 'ROSE M.': 'L',
 'BALL S.': 'R',
 'KERCKHOVEN J. V.': nan,
 'CANO R.': 'R',
 'KHAN M. M.': nan,
 'MEYER R.': 'R',
 'WIJONO A.': 'R',
 'WIDJOJO G.': 'R',
 'BARTONI F.': 'R',
 'SOLOMON H.': 'R',
 'ZUGARELLI A.': 'R',
 'BRASSEUR T.': nan,
 'VILELA J.': nan,
 'AYDIN R.': nan,
 'FRANCHITTI V.': 'R',
 'SHALEM Y.': nan,
 'SIMPSON J.': 'R',
 'VOLKOV A.': 'L',
 'MCDONALD A.': 'R',
 'MIGNOT B.': 'R',
 'MOTTRAM B. C.': 'R',
 'JOHANSSON L.': 'R',
 'JOHANSSON K.': 'R',
 'WARBOYS S.': 'R',
 'GOTTFRIED B.': 'R',
 'TANNER R.': 'L',
 'MAYER S.': 'R',
 'FAULK S.': 'R',
 'DIBBS E.': 'R',
 'AUSTIN J.': nan,
 'KREISS R.': 'R',
 'HIRAI K.': 'R',
 'MARCUS B.': 'R',
 'FISHER R.': 'R',
 'REID G. R.': 'R',
 'KRULEVITZ S.': 'R',
 'HOLMES N.': 'R',
 'RAY R.': nan,
 'VASQUEZ T.': nan,
 'REED W.': nan,
 'BROWN T.': 'R',
 'SVENSSON T.': 'R',
 'LYNCH T.': nan,
 'AUBONE R.': nan,
 'STEPHENS J.': 'R',
 'TANABE K.': nan,
 'JAMES J.': 'R',
 'LETCHER C.': 'R',
 'DELANEY J.': 'R',
 'CROOKENDEN I.': 'R',
 'OSBORNE G.': 'R',
 'PRAJOUX B.': 'R',
 'VELASCO S.': nan,
 'LY A. A.': nan,
 'TAROCZY B.': 'R',
 'BORG B.': 'R',
 'BARAZZUTTI C.': 'R',
 'BERTOLUCCI P.': 'R',
 'LAIMINA O.': 'R',
 'OMAR A. B.': nan,
 'ACHRAOUI M. C. E.': nan,
 'REID K.': nan,
 'OVICI T.': 'R',
 'MACHAN R.': 'R',
 'ENGERT H.': 'R',
 'HEWITT I.': 'R',
 'KAKULIA T.': nan,
 'MENDOZA J. D.': 'R',
 'FEAVER J.': 'R',
 'SCHROEDER F. T.': 'R',
 'STEWART S.': 'R',
 'CORN J.': nan,
 'BOHRNSTEDT R.': nan,
 'OWENS C.': 'R',
 'ROBINS B.': 'R',
 'WALTHALL P.': 'R',
 'BIRCHMORE D.': 'R',
 'MATTHEWS D.': nan,
 'MIN P. V.': 'R',
 'PHILLIPS M.': 'R',
 'RICHEY T.': 'R',
 'ANDERSSON B.': 'R',
 'HAGEY J. C.': 'R',
 'NEWTON G.': nan,
 'GERULAITIS V.': 'R',
 'MACHETTE M.': 'R',
 'WALTKE T.': 'R',
 'LINGE J. V.': 'R',
 'MITCHELL D.': nan,
 'KAMAKANA H. H.': 'R',
 'CRAWFORD D.': 'R',
 'MUSALEM P.': 'R',
 'RUIZ R.': 'R',
 'NORBERG R.': 'R',
 'BOUCHAIB H.': nan,
 'DRYSDALE R.': 'R',
 'ROMANI H.': nan,
 'NOONAN T.': 'R',
 'PERKINS G.': 'R',
 'THOROUGHOOD G.': 'R',
 'HAILLET J. L.': 'R',
 'BERNASCONI T.': 'R',
 'CAUJOLLE J. F.': 'L',
 'GEBERT F.': 'R',
 'SENIOR M.': 'R',
 'KACHEL C.': 'R',
 'THOMSON G.': nan,
 'DUPRE P.': 'R',
 'MAYER A.': nan,
 'BARDSLEY T.': 'R',
 'KIM S. B.': nan,
 'MEER S.': 'R',
 'TARIK J.': 'R',
 'SANGITAN S.': nan,
 'THAMIN J.': 'R',
 'MACDONALD A.': 'R',
 'KANDERAL P.': 'R',
 'TIMONEN M.': 'R',
 'MELANDER E.': nan,
 'HEGNA P.': 'R',
 'JAGGE F. D.': nan,
 'DEBLICKER E.': 'R',
 'PAMPOULOV B.': 'R',
 'MAHMOUD I.': 'R',
 'HASSAN A.': nan,
 'HERRERA J.': 'R',
 'RODRIQUEZ P.': nan,
 'KRONK P.': 'R',
 'FIBAK W.': 'R',
 'ELVSTROM L.': 'R',
 'DOWDESWELL C.': 'R',
 'MITTON B.': 'R',
 'LLOYD J.': 'R',
 'TARPISCHEV S.': 'R',
 'PINNER U.': 'R',
 'FALDERBAUM F.': 'R',
 'BENYIK J.': 'R',
 'COOPER G.': 'R',
 'MUKHERJEA C.': 'R',
 'CASTANON J.': 'R',
 'CHAVEZ R.': 'R',
 'DURHAM W.': 'R',
 'SIMPSON R.': 'R',
 'JOUBERT D.': 'L',
 'MARTIN B.': 'R',
 'HANCOCK K.': 'R',
 'EWERT E.': 'R',
 'BUWALDA R.': 'R',
 'YUILL J.': 'R',
 'SMITH J.': nan,
 'P071 T. P.': 'R',
 'LYNDON U.': nan,
 'LEWIS R.': 'L',
 'FARRELL M.': 'R',
 'DAVIES W.': 'R',
 'BOHRNSTEDT D. R.': 'R',
 'MOOR T.': 'L',
 'CSOKNYAI B.': 'R',
 'TEACHER B.': 'R',
 'WHITLINGER J.': 'R',
 'MUNOZ C.': 'R',
 'MANSON B.': 'L',
 'FLEMING P.': 'R',
 'AMAYA V.': 'L',
 'HARDIE G.': 'L',
 'KOCAK A.': nan,
 'HASSOUN N. A.': nan,
 'ISSA K.': nan,
 'YCAZA R.': 'R',
 'KOURA T.': 'R',
 'RHEINBERGER R.': 'R',
 'HIGUERAS J.': 'R',
 'MCCORMICK D.': 'R',
 'ANDERSSON K.': nan,
 'PONTE F.': 'R',
 'MUKERJEA C.': nan,
 'SIMBERA J.': 'R',
 'PISECKY J.': 'R',
 'AKBARI M. H.': 'R',
 'MURDONO D.': nan,
 'HADIMAN H.': nan,
 'PALMER O.': 'R',
 'GENOIS R.': 'R',
 'AGUDELO O.': 'R',
 'ONIBOKUN T.': nan,
 'AWOPEGBA L.': 'R',
 'NAEGELEN D.': 'R',
 'GURSOY T.': nan,
 'OZDEMIR H.': nan,
 'HOLMES G.': 'R',
 'SANTEIU I.': 'R',
 'MOORE2 R.': nan,
 'THUNG R.': 'L',
 'KAPLAN F.': nan,
 'MAJEED I.': nan,
 'CHOW W. W.': nan,
 'RAFON R.': 'R',
 'DIMALANTA B.': nan,
 'BALLERET B.': 'R',
 'BORFIGA L.': 'R',
 'MOE T.': nan,
 'MUNOZ E.': 'R',
 'ROBINSON M.': 'L',
 'DOWDESWELL R.': 'R',
 'MERWE F. V. D.': 'R',
 'TURVILLE L.': 'R',
 'TRICKEY J.': 'R',
 'LITTLE T.': 'R',
 'NZL C. L.': 'R',
 'C100 R. C.': 'R',
 'MYERS S.': 'R',
 'SEEGERS R.': 'R',
 'COLLINS M.': 'R',
 'LOVERA J.': 'R',
 'PALM D.': 'R',
 'WUNSCHIG M.': 'R',
 'SANDERS L.': 'R',
 'CAHILL M.': 'R',
 'ANDREWS J.': nan,
 'BUNIS H.': 'R',
 'POWERS M.': 'R',
 'MADANI A.': nan,
 'SALEH H.': nan,
 'DERAFSHIDJAVAN K.': nan,
 'WERTHEIMER M.': nan,
 'ALTINKAYA B.': nan,
 'MENTON K.': nan,
 'TURNER S.': 'R',
 'TAYGAN F.': 'R',
 'SAVIANO N.': 'L',
 'HASSALL T.': nan,
 'FORT J.': 'R',
 'AMAYA G.': 'R',
 'KREISS T.': 'R',
 'ALLAN Y.': nan,
 'AJAYI K.': 'R',
 'NIEDZWIEDZKI J.': 'R',
 'DRZYMALSKI H.': nan,
 'BROWN B.': 'R',
 'PAMPOULOV M.': nan,
 'PETROV L.': 'R',
 'POL E. V. D.': nan,
 'CABEZA S.': 'R',
 'MOTOI M.': 'R',
 'TEZUKA Y.': 'R',
 'MACHIDORI A.': 'R',
 'KIM M. I.': nan,
 'KATO S.': nan,
 'TANAKA S.': 'R',
 'WIMMER I.': 'R',
 'TA D. B.': nan,
 'COOMBES K.': 'R',
 'ROYAPPA J.': 'R',
 'GEHRING R.': 'R',
 'PECCI V.': 'R',
 'KIRMAYR C.': 'R',
 'BENAVIDES R.': 'R',
 'FERNANDO A.': 'R',
 'DOMINGUEZ M.': nan,
 'MCNAMARA P.': 'R',
 'WIMMER G.': 'R',
 'OLIVER G.': nan,
 'CARNAHAN S.': 'R',
 'DOCHERTY S.': 'R',
 'MAYER G.': 'R',
 'SEGURA S.': 'R',
 'HOLLADAY J.': nan,
 'CRAWFORD R.': 'R',
 'STURDZA T.': nan,
 'GOTTFRIED L.': 'R',
 'WINITSKY V.': 'L',
 'SLOZIL P.': 'R',
 'MOTT T.': 'R',
 'MCMILLAN K.': 'R',
 'MARTORELL A.': 'R',
 'HARADAU D.': 'R',
 'DAWSON T.': 'R',
 'ZABRODSKY J.': 'R',
 'MUNTANOLA J. I.': 'R',
 'PRINSLOO W.': 'R',
 'HUTKA P.': 'R',
 'ROBINSON C.': nan,
 'MARTEN U.': 'R',
 'EDMONDSON M.': 'R',
 'GIMENEZ A.': 'R',
 'DAS Y.': nan,
 'MOORE J.': 'R',
 'CENTER U.': nan,
 'ATAS C.': nan,
 'GULLIKSON T.': 'L',
 'MINCEK Z.': nan,
 'LAGOS J.': nan,
 'SOEAR N.': 'R',
 'FILLOL A.': 'R',
 'KELAIDIS N.': 'R',
 'BARRIOLA F.': nan,
 'MAURTUA M.': nan,
 'STAPF G.': nan,
 'FEIGL P.': 'R',
 'IFTIKHAR T.': nan,
 'FISHBACH M.': 'R',
 'ZIRNGIBL W.': 'R',
 'POWER D.': 'R',
 'BAHRAMI M.': 'R',
 'BARALDI L.': 'R',
 'AVIS P.': 'R',
 'CAMPBELL P.': 'R',
 'CARTER D.': 'R',
 'HAGELAUER P.': 'R',
 'BRITTAIN H.': 'R',
 'MARKS J.': 'R',
 'SOARES J.': 'R',
 'DREWETT B.': 'L',
 'CAVIGLIA E.': 'R',
 'HAWKES R.': 'R',
 'MILLS J.': nan,
 'MOHAMMED A. G.': nan,
 'MONTONA U.': 'R',
 'LUNDSTEDT B.': 'R',
 'WALTS B.': 'R',
 'SMID T.': 'R',
 'SCANLON B.': 'R',
 'WAYMAN M.': 'R',
 'MARCU G.': 'R',
 'JONES G.': 'R',
 'GAUVAIN H.': 'R',
 'MOORE P.': 'R',
 'SOLER J.': 'L',
 'OCLEPPO G.': 'R',
 'ROBINSON J.': 'R',
 'MCKEE R.': 'R',
 'JOHANSSON S.': 'R',
 'TURNER D.': 'R',
 'ZERNGIBL U.': 'R',
 'BORISOV V.': 'R',
 'PUGAEV K.': nan,
 'LOMBARDI R.': 'R',
 'GUNTHARDT H.': 'R',
 'COLLINGS D.': 'R',
 'HEGNA S.': 'R',
 'WEBB B.': 'R',
 'MEYERS M.': 'R',
 'MONTANO E.': 'R',
 'JR J. R.': 'R',
 'SCHNEIDER D.': 'R',
 'PFISTER H.': 'R',
 'RICHARDSON K.': 'R',
 'HALDER G.': 'R',
 'MCENROE J.': 'L',
 'KHODAI M. A.': nan,
 'NEMATI E.': nan,
 'PALIN L.': 'R',
 'GLICKSTEIN S.': 'R',
 'MALIN G. S.': 'R',
 'MCARDLE J.': nan,
 'SORENSEN S.': 'R',
 'HURLIMANN M.': 'R',
 'TELTSCHER E.': 'R',
 'JAVAN K.': nan,
 'WINCKELMANN F.': nan,
 'CHAMPISRI S.': nan,
 'CHIEW F. C.': nan,
 'KAIMAN P.': nan,
 'TORRALBO J.': 'R',
 'PIEROLA A.': 'R',
 'DAMIANI J. L.': 'R',
 'ROVERANO H.': 'R',
 'BOYCE J.': nan,
 'MAYNETTO F.': 'R',
 'SARAVIA R. G. B.': nan,
 'ALVARADO C.': 'R',
 'MCNAMEE P.': 'R',
 'ERIKSSON U.': 'R',
 'NORBACK J.': 'R',
 'FONTANA F. D.': 'R',
 'CLERC J. L.': 'R',
 'GOES J.': 'R',
 'CHOI B. K.': nan,
 'JU C. N.': nan,
 'FRIEDLER E.': 'R',
 'GILDEMEISTER H.': 'R',
 'CASA C.': 'R',
 'MULLER J.': 'R',
 'CHAPPELL R.': 'R',
 'SULLIVAN S.': nan,
 'WIJONO L.': nan,
 'FRAWLEY R.': 'R',
 'FANCUTT C.': 'R',
 'LOFGREN B.': 'R',
 'LANGSFORD P.': 'R',
 'WILKISON T.': 'L',
 'SIMMONDS D.': nan,
 'GRANAT J.': 'R',
 'LAIMINA M.': nan,
 'EBERHARD K.': 'R',
 'ELTER P.': 'R',
 'VASSELIN C. R.': 'R',
 'BEDEL D.': 'R',
 'FAGEL R.': 'R',
 'FREYSS C.': 'L',
 'MITCHELL M.': nan,
 'SYLVAN C.': 'R',
 'GIAMMALVA T.': 'R',
 'FRITZ B.': 'R',
 'STRODE C. B.': 'R',
 'FOXWORTH B.': 'R',
 'SCHOENFIELD H.': 'R',
 'MAHMOUDI A. A.': 'R',
 'DISLAM M.': nan,
 'SABER H.': 'R',
 'DLIMI M.': 'R',
 'GONZALEZ F.': 'R',
 'VERDIECK D.': nan,
 'BOILEAU B.': 'R',
 'STEVAUX T.': 'R',
 'CRUZ S.': nan,
 'SHER I.': 'R',
 'FOK W.': 'R',
 'PETROVIC G.': 'R',
 'DUNK C.': 'R',
 'FUKUI T.': 'R',
 'YAMAMOTO T.': 'R',
 'NISHIO S.': 'R',
 'HUSSAIN A.': nan,
 'MORETTON G.': 'R',
 'GABRIEL O.': nan,
 'SMYLIE P.': 'R',
 'LANDO C.': 'R',
 'OROPEZ G.': 'R',
 'TOULON G.': 'R',
 'HOYT H.': 'R',
 'LUNA F.': 'R',
 'VIZCAINO R.': 'R',
 'KRIEK J.': 'R',
 'MARTINEZ M.': 'R',
 'RUDMAN G.': 'R',
 'SULLIVAN D.': nan,
 'CLEMENTS T.': 'R',
 'ROCAVERT T.': 'R',
 'PHILLIPS N.': 'R',
 'LEVAI L.': 'R',
 'BORTULAN R.': nan,
 'PROBST R.': 'R',
 'BORGENER M.': nan,
 'MEYERS J.': 'R',
 'PEARSON P.': 'R',
 'FRITZ H.': 'R',
 'SAVIC D.': 'R',
 'ILIN Z.': 'R',
 'DOBROWOLSKI C.': nan,
 'ZIETSMANN A.': 'R',
 'PORTES P.': 'R',
 'NOAH Y.': 'R',
 'NEWMAN B.': nan,
 'BIRNER S.': 'R',
 'BEVEN R.': 'R',
 'MAURER A.': 'R',
 'ISKERSKY E.': 'R',
 'HJERTQUIST P.': 'R',
 'PRUCHA J.': 'R',
 'KELLY R.': 'R',
 'GARCIA T.': 'R',
 'DENTON S.': 'R',
 'STANSBURY C.': 'R',
 'SADRI J.': 'R',
 'NICHOLS B.': 'R',
 'GRAHAM T.': 'R',
 'CURREN K.': 'R',
 'SAKKA T. E.': 'R',
 'MEHELMY A. E.': 'R',
 'CHRISTENSEN F.': nan,
 'GOMEZ A.': nan,
 'VIVER R. A.': 'L',
 'JARRETT A.': 'R',
 'LENDL I.': 'R',
 'HOF R. V.': 'R',
 'KIM B. S.': 'R',
 'KHAN N. A.': nan,
 'ANTONAS J.': 'R',
 'MOTTA C.': 'R',
 'MAESO L.': 'R',
 'VASQUEZ F.': 'R',
 'MUSTARD D.': 'L',
 'PICKEN J.': 'R',
 'NISHIWAKI T.': 'R',
 'NAGURO A.': 'R',
 'MIR M.': 'R',
 'SIMONSSON S.': 'R',
 'ROWE B.': 'R',
 'VARELA H.': 'R',
 'MAZZOCCHI F.': 'R',
 'MARCHETTI G.': 'R',
 'TIHONENKO I.': nan,
 'DILOUIE J.': 'R',
 'EKE V.': 'R',
 'LOEB L.': 'R',
 'NUNNA B.': 'R',
 'KLEEGE B.': 'R',
 'GUNTHARDT M.': 'R',
 'SVENSSON S.': 'R',
 'MOLIN J.': 'R',
 'IMONITIE D.': 'R',
 'FRITZ W.': 'R',
 'STADLER R.': nan,
 'SHORE M.': 'R',
 'CORTES A.': 'R',
 'MERLONE F.': 'R',
 'URPI G.': 'R',
 'SAUER F.': 'R',
 'PATTEN V. V.': 'R',
 'MAHER W.': 'R',
 'GUEDES R.': 'R',
 'TROGOLO R.': 'R',
 'RENNERT P.': 'L',
 'BUSHMAN J.': 'R',
 'PURCELL M.': nan,
 'BARR M.': 'R',
 'FROMM E.': 'R',
 'GRANT M.': 'R',
 'CAIN T.': 'R',
 'LEWIS J. C.': 'R',
 'HOF E. V.': 'R',
 'HAYES J.': 'R',
 'WILLIAMS T.': 'R',
 'KERETIC D.': 'R',
 'BUEHNING F.': 'R',
 'MAZE B.': 'R',
 'LAPIDUS J.': 'L',
 'NUNEZ J.': 'R',
 'GUNNARSSON J.': 'R',
 'ISMAIL H.': 'R',
 'HARRINGTON M.': 'R',
 'BOURNE L.': 'R',
 'JILEMNICKY J.': nan,
 'STEFANKI L.': 'R',
 'JONES W.': 'R',
 'BRASH N.': 'R',
 'GUNNING C.': 'R',
 'EAGLETON J.': 'R',
 'BAILEY J.': 'R',
 'DIAZ M.': 'R',
 'BOUDJEMLINE D.': nan,
 'RANDBY T.': nan,
 'OSTOJA M.': 'R',
 'ANDRADE J.': 'R',
 'EDWARDS E.': 'R',
 'MAESO J. L.': 'R',
 'POPP W.': 'R',
 'BRABENEC J.': 'R',
 'BETTAUER R.': 'R',
 'PEREZ D.': 'R',
 'JEON C. D.': nan,
 'JEON Y. D.': 'R',
 'ARLOZOROV C.': 'R',
 'WHITECROSS G.': 'R',
 'KURAMITSU T.': 'R',
 'YONEZAWA T.': 'R',
 'SIMONSSON H.': 'R',
 'TAMURA N.': 'R',
 'TURPIN M.': 'R',
 'DELANEY C.': 'R',
 'MIONBET F.': nan,
 'POSSO M.': nan,
 'WU C. R.': 'R',
 'HSU H. J.': nan,
 'PLADCHUNIL P.': 'R',
 'ACUNA R.': 'R',
 'HOGSTEDT T.': 'R',
 'KIM C. H.': 'R',
 'STEIGLER R.': 'R',
 'KOHLBERG A.': 'L',
 'RIVAROLI M.': 'R',
 'GOSWAMI B.': 'R',
 'GATTIKER C.': 'R',
 'REBOLLEDO P.': 'R',
 'BAL N.': 'R',
 'GUAN B.': 'R',
 'FITZGERALD J.': 'R',
 'SIEGLER D.': 'R',
 'CLARKE S.': 'R',
 'MILLER C. A.': 'R',
 'COHEN J.': 'R',
 'HAMPSON W.': 'R',
 'PASCOE W.': 'R',
 'EVETT R.': 'R',
 'EVERNDEN K.': 'R',
 'LEWIS M.': 'R',
 'HAMPTON P.': 'R',
 ...}

In [735]:
def set_hand():
    def get_hand(p):
        try:
            val = players_hands_dict[p]
        except:
            val = np.nan
        return val
    
    dataframe['HandA'] = dataframe['Winner'].apply(get_hand)
    dataframe['HandB'] = dataframe['Loser'].apply(get_hand)

In [736]:
set_hand()

In [737]:
#dataframe['HandA'].fillna('U', inplace = True)

In [738]:
#dataframe['HandB'].fillna('U', inplace = True)

In [739]:
sorted(dataframe[dataframe['HandA'].isna()]['Winner'].append(dataframe[dataframe['HandB'].isna()]['Loser']).unique().tolist())

['ABDULLA M.',
 'AHOUDA A.',
 'AL GHAREEB M.',
 'AL KHULAIFI N.G.',
 'AL MUTAWA J.',
 'AL-ALAWI S.K.',
 'ALAWADHI O.',
 'ALI MUTAWA J.M.',
 'ALTMAIER D.',
 'ALVAREZ E.',
 'ANCIC I.',
 'ANDERSEN J.F.',
 'ANDERSON O.',
 'ANDREEV A.',
 'ARAGONE JC',
 'ARANGUREN J.M.',
 'ARTUNEDO MARTINAVARRO A.',
 'ASCIONE A.',
 'AUGER-ALIASSIME F.',
 'AVIDZBA A.',
 'BACHELOT J.F',
 'BAGHDATIS M.',
 'BAHROUZYAN O.',
 'BASSO A.',
 'BAUTISTA AGUT R.',
 'BAUTISTA R.',
 'BELLIER A.',
 'BENCHETRIT E.',
 'BENNETEAU A.',
 'BERRETTINI M.',
 'BOGAERTS R.',
 'BOGOMOLOV A.',
 'BOGOMOLOV JR. A.',
 'BOGOMOLOV JR.A.',
 'BONZI B.',
 'BROOKSBY J.',
 'BRUGUES-DAVI A.',
 'BRZEZICKI J.P.',
 'CABAL J.S.',
 'CARBALLES BAENA R.',
 'CARRENO BUSTA P.',
 'CARUANA L.',
 'CELIKBILEK A.',
 'CERUNDOLO F.',
 'CERVANTES I.',
 'CHAKI R.',
 'CHEKOV P.',
 'CHELA J.I.',
 'CONDOR F.',
 'CORRIE E.',
 'DAILEY Z.',
 'DASNIERES DE VEIGY J.',
 'DAVIDOVICH FOKINA A.',
 'DAVLETSHIN V.',
 'DAVYDENKO P.',
 'DE BAKKER T.',
 'DE CHAUNAC S.',
 'DE GREEF A.',
 'DE HEART R.',
 'DE LOORE J.',
 'DE MINAUR A.',
 'DE PAULA F.',
 'DE SCHEPPER K.',
 'DE VOEST R.',
 'DEEN HESHAAM A.',
 'DEL BONIS F.',
 'DEL POTRO J. M.',
 "DELL'ACQUA M.",
 'DEV VARMAN S.',
 'DI MAURO A.',
 'DI PASQUALE A.',
 'DO M.Q.',
 'DONSKI A.',
 'DUBRIVNYY A.',
 'DUCLOS P.L.',
 'DUTRA DA SILVA R.',
 'DUTRA SILVA R.',
 'EL AAREJ M.',
 'EL AMRANI R.',
 'EL AYNAOUI Y.',
 'ESTRELLA BURGOS V.',
 'FAUREL J.C.',
 'FERRERO J.C.',
 'FISH A.',
 'FLANAGAN I.',
 'FORNELL M.',
 'FRITZ T.',
 'FRUTTERO J.P.',
 'GALAN D.E.',
 'GALLARDO M.',
 'GALLARDO VALLES M.',
 'GAMBILL J.M.',
 'GAO X.',
 'GARCIA-LOPEZ G.',
 'GARCIA-SINTES J.',
 'GASTON H.',
 'GIMENO-TRAVER D.',
 'GOELLNER M.K.',
 'GOJO B.',
 'GOMEZ A.',
 'GOMEZ L.',
 'GOMEZ-HERRERA C.',
 'GONG M.X.',
 'GORANSSON T.',
 'GRANOLLERS PUJOL G.',
 'GRANOLLERS-PUJOL M.',
 'GRAY A.',
 'GROMLEY C.',
 'GRUBER K.',
 'GUCCIONE A.',
 'GUTIERREZ-FERROL S.',
 'GUZMAN J.',
 'GUZMAN J.P.',
 'HAIDER-MAURER A.',
 'HAJI A.',
 'HAJJI A.',
 'HANFMANN Y.',
 'HANK T.',
 'HANTSCHEK M.',
 'HARPER-GRIFFITH L.',
 'HARRIS L.',
 'HARSANYI P.',
 'HERBERT P-H.',
 'HERBERT P.H',
 'HERBERT P.H.',
 'HERM-ZAHLAVA J.',
 'HERNANDEZ-FERNANDEZ J.',
 'HUESLER M.A.',
 'HUTA GALUNG J.',
 'IDMBAREK Y.',
 'IM K.T.',
 'IVANOV-SMOLENSKY K.',
 'JANVIER M.',
 'JEONG S.Y.',
 'JONES G.D.',
 'JUBB P.',
 'JUN W.',
 'JUN W.S.',
 'KACHMAZOV A.',
 'KIM K',
 'KING K.',
 'KING-TURNER D.',
 'KIRKIN E.',
 'KODERISCH C.',
 'KOHLSCHREIBER P..',
 'KOLAR Z.',
 'KORDA S.',
 'KORTELING S.',
 'KUCERA V.',
 'KUNITCIN I.',
 'KUTAC R.',
 'KUZNETSOV AL.',
 'KUZNETSOV AN.',
 'KWIATKOWSKI T.S.',
 'KWON S.W.',
 'KYPSON P.',
 'LAZOV A.',
 'LEE D.H.',
 'LEE H.T.',
 'LENZ J.',
 'LESHEM E.',
 'LEVINE I.',
 'LIN J.M.',
 'LISNARD J.R.',
 'LONDERO J.I.',
 'LOPEZ VILLASENOR G.',
 'LOPEZ-JAEN M.A.',
 'LOPEZ-PEREZ E.',
 'LU Y.',
 'LU Y.H.',
 'LUNCANU P.A.',
 'LUQUE D.',
 'MADEN Y.',
 'MARCH O.',
 'MARIN J.A.',
 'MARIN L.',
 'MARRAI M.',
 'MARTINEZ P.',
 'MATHIEU P.',
 'MATHIEU P.H.',
 'MATOS-GIL I.',
 'MEISTER N.',
 'MENENDEZ-MACEIRAS A.',
 'MILOJEVIC N.',
 'MIYAO J.',
 'MOELLER M.',
 'MONTEIRO J.',
 'MORAING M.',
 'MORONI G.',
 'MOTT B.',
 'MULLER A.',
 'MUNAR J.',
 'MUNOZ DE LA NAVA D.',
 'NADER M.',
 'NAM H.W.',
 'NAVA E.',
 'NAVARRO-PASTOR I.',
 'NEDOVYESOV O.',
 'NIKI T.',
 "O'BRIEN A.",
 "O'CONNELL C.",
 "O'NEAL J.",
 'OJEDA LARA R.',
 'OLASO G.',
 'OPELKA R.',
 'ORTEGA-OLMEDO R.',
 'PASHA N.',
 'PFEIFFER K.',
 'PIROS Z.',
 'PODLIPNIK H.',
 'POLMANS M.',
 'POPYRIN A.',
 'PRASHANTH V.',
 'PRPIC A.',
 'PURCELL M.',
 'QUERRY S.',
 'QUIGLEY E.',
 'QURESHI A.',
 'QURESHI A.U.H.',
 'RAMIREZ HIDALGO R.',
 'RAMOS-VINOLAS A.',
 'RASCON T.',
 'REIX C.',
 'REYES-VARELA M.A.',
 'RIBA-MADRID P.',
 'ROBREDO R.',
 'ROCA BATALLA O.',
 'RODIONOV J.',
 'ROGER-VASSELIN E.',
 'ROUMANE R.',
 'RUEVSKI P.',
 'SAAVEDRA CORVALAN C.',
 'SABRY S.',
 'SAFIULLIN R.',
 'SAKAMOTO P.',
 'SALVA B.',
 'SAMPER-MONTANA J.',
 'SANCHEZ DE LUNA J.A.',
 'SARMIENTO R.',
 'SCHERRER J.C.',
 'SCHUTTLER P.',
 'SCHWARTZMAN D.',
 'SERDARUSIC N.',
 'SEYBOTH WILD T.',
 'SHANE R.',
 'SI Y.M.',
 'SILVA D.',
 'SILVA F.',
 'SILVA F.F.',
 'SINNER J.',
 'SMETHURST D.',
 'SMITH A.',
 'SMITH J.P.',
 'STATHAM J.',
 'STATHAM R.',
 'STEBE C.M.',
 'STEPANEK M.',
 'STRUFF J.L.',
 'SULTAN-KHALFAN A.',
 'SVAJDA Z.',
 'TAKAHASHI Y.',
 'TOPIC J.',
 'TRAVAGLIA S.',
 'TRUJILLO G.',
 'TRUSENDI W.',
 'TSENG C.H.',
 'TSONGA J.W.',
 'TYURNEV E.',
 'VAISSE M.',
 'VAN DER DIUM A.',
 'VAN DER MEER N.',
 'VAN DER MERWE I.',
 'VAN GEMERDEN M.',
 'VAN LOTTUM J.',
 'VAN RIJTHOVEN T.',
 'VAN SCHEPPINGEN D.',
 'VASSALLO-ARGUELLO M.',
 'VATUTIN A.',
 'VEGA HERNANDEZ D.',
 'VERDASCO M.',
 'VICENTE M.',
 'VILOCA J.A.',
 'VIOLA MAT.',
 'WALTER L.',
 'WANG Y.',
 'WANG Y. JR',
 'WANG Y. JR.',
 'WANG Y.T.',
 'WARD A.',
 'WATANUKI Y.',
 'WILLMAN D.',
 'XU J.C.',
 'YANG T.H.',
 'YOON Y.',
 'YOUZHNY A.',
 'YU X.Y.',
 'ZAPATA MIRALLES B.',
 'ZAYED M. S.',
 'ZEKIC M.',
 'ZENG S.X.',
 'ZHANG Z.',
 'ZHANG ZE',
 'ZHANG ZE.',
 'ZHANG ZH.',
 'ZHU B.Q.']

In [740]:
extradf['winner_name2']

0                        NaN
1                        NaN
2                        NaN
3                        NaN
4                        NaN
5                        NaN
6                        NaN
7          PHILLIPS MOORE B.
8                        NaN
9                        NaN
10                       NaN
11                       NaN
12                       NaN
13                       NaN
14                       NaN
15                       NaN
16                       NaN
17                       NaN
18                       NaN
19                       NaN
20                       NaN
21                       NaN
22                       NaN
23                       NaN
24                       NaN
25                       NaN
26                       NaN
27                       NaN
28                       NaN
29                       NaN
                 ...
169660                   NaN
169661                   NaN
169662                   NaN
169663                   NaN
169664                   NaN
169665    AUGER ALIASSIME F.
169666    CARBALLES BAENA R.
169667       SEYBOTH WILD T.
169668                   NaN
169669                   NaN
169670                   NaN
169671                   NaN
169672    IGNACIO LONDERO J.
169673                   NaN
169674                   NaN
169675                   NaN
169676    AUGER ALIASSIME F.
169677                   NaN
169678                   NaN
169679                   NaN
169680                   NaN
169681                   NaN
169682                   NaN
169683                   NaN
169684                   NaN
169685                   NaN
169686                   NaN
169687                   NaN
169688                   NaN
169689                   NaN
Name: winner_name2, Length: 169689, dtype: object

In [741]:
players_hands = extradf[['winner_name2','winner_hand']].drop_duplicates().append(
    extradf[['loser_name2','loser_hand']].rename(columns = {'loser_name2': 'winner_name2',
                                                                             'loser_hand': 'winner_hand'}), 
    ignore_index = True).drop_duplicates()

In [742]:
import numpy as np
players_hands['winner_hand'] = players_hands['winner_hand'].apply(lambda x:np.nan if x == 'U' else x)
players_hands['winner_hand'].dropna(inplace = True, axis = 0)
players_hands['winner_name2'].dropna(inplace = True, axis = 0)

In [743]:
players_hands_dict = {p:np.nan for p in players_hands['winner_name2']}
for i in players_hands.itertuples():
    players_hands_dict[i.winner_name2] = i.winner_hand

In [744]:
players_hands_dict

{'PHILLIPS MOORE B.': 'R',
 'BUTCH BUCHHOLZ E.': 'R',
 'PANCHO GONZALES R.': 'R',
 'LUIS ARILLLA J.': 'R',
 'RODRIGUEZ CHI P.': 'R',
 'DI MATTEO E.': 'R',
 'VICTOR SEIXAS E.': 'R',
 'LOYO MAYO J.': 'R',
 'RICHARD RUSSELL D.': 'R',
 'VAN DILLEN E.': 'R',
 'TITO VAZQUEZ M.': 'R',
 'STEELE III C.': 'R',
 'CLAUDE BARCLAY J.': 'R',
 'JURGEN POHMANN H.': 'R',
 'LOUP ROUYER J.': 'R',
 'JAOCHIM PLOTZ H.': 'R',
 'BAPTISTE CHANFREAU J.': 'R',
 'DI MASO G.': 'R',
 'DI DOMENICO M.': 'R',
 'PINTO BRAVO J.': 'R',
 'PIERRE OLIVIER J.': 'R',
 'PAUL MEYER J.': 'R',
 'EL SHAFEI I.': 'R',
 'ERIC LUNDQUIST J.': 'R',
 'HANK IRVINE H.': 'R',
 'NILS BENGTSON O.': 'R',
 'DE GRONCKEL C.': 'R',
 'PETERSEN DYGGVE P.': nan,
 'VAZ PINTO A.': nan,
 'AMAN AZMAN S.': nan,
 'PRAKASH MISRA S.': nan,
 'EL DAWOUDI A.': 'R',
 'EL SONBOL M.': nan,
 'DUC LUU H.': nan,
 'THANH VO V.': nan,
 'HWAN KIM D.': nan,
 'HO CHUNG Y.': nan,
 'MARIA GISBERT J.': nan,
 'TURNER HOWARD G.': 'R',
 'PIERRE COURCOL J.': nan,
 'FELIPE TAVARES L.': 'R',
 'THANH NGUYEN V.': nan,
 'BAY VO V.': nan,
 'EDVARD HEDELUND C.': nan,
 'PIERRE LOIZEAU J.': nan,
 'VAN KERCKHOVEN J.': nan,
 'MOHAMMED KHAN M.': nan,
 'C MOTTRAM B.': 'R',
 'RAZ REID G.': 'R',
 'AN LY A.': nan,
 'BEN OMAR A.': nan,
 'EL ACHRAOUI M. C.': nan,
 'DE MENDOZA J.': 'R',
 'TED SCHROEDER F.': 'R',
 'VAN MIN P.': 'R',
 'CHICO HAGEY J.': 'R',
 'VAN LINGE J.': 'R',
 'HANK KAMAKANA H.': 'R',
 'LOUIS HAILLET J.': 'R',
 'FRANCOIS CAUJOLLE J.': 'L',
 'BAE KIM S.': nan,
 'DAG JAGGE F.': nan,
 'PARUN P071 T.': 'R',
 'R BOHRNSTEDT D.': 'R',
 'ABOU HASSOUN N.': nan,
 'HOSSEIN AKBARI M.': 'R',
 'WAH CHOW W.': nan,
 'DER MERWE F. V.': 'R',
 'LEWIS NZL C.': 'R',
 'CASEY C100 R.': 'R',
 'DER POL E. V.': nan,
 'IL KIM M.': nan,
 'BAO TA D.': nan,
 'IGNACIO MUNTANOLA J.': 'R',
 'GHANI MOHAMMED A.': nan,
 'GAWAD MOHAMMED A.': nan,
 'RASGADO JR J.': 'R',
 'ALI KHODAI M.': nan,
 'STUART MALIN G.': 'R',
 'CHONG CHIEW F.': nan,
 'LUIS DAMIANI J.': 'R',
 'BENAVIDES SARAVIA R. G.': nan,
 'DALLA FONTANA F.': 'R',
 'LUIS CLERC J.': 'R',
 'KIL CHOI B.': nan,
 'NAM JU C.': nan,
 'ROGER VASSELIN C.': 'R',
 'BUZZ STRODE C.': 'R',
 'ASLAM MAHMOUDI A.': 'R',
 'EL SAKKA T.': 'R',
 'EL MEHELMY A.': 'R',
 'ANTONIO VIVER R.': 'L',
 'VANT HOF R.': 'R',
 'SUK KIM B.': nan,
 'ALI KHAN N.': nan,
 'VAN PATTEN V.': 'R',
 'CHRIS LEWIS J.': 'R',
 'VANT HOF E.': 'R',
 'LOPEZ MAESO J.': 'R',
 'DAE JEON C.': nan,
 'DAE JEON Y.': 'R',
 'RUNG WU C.': 'R',
 'JUNG HSU H.': nan,
 'HO KIM C.': 'R',
 'A MILLER C.': 'R',
 'GIAMMALVA JR S.': 'R',
 'CARLOS AYALA J.': 'R',
 'ARIANTO WIBOWO T.': nan,
 'DE JESUS F.': 'R',
 'C VILJOEN T.': 'R',
 'DER MERWE S. V.': 'R',
 'GARCIA REQUENA J.': nan,
 'SKIP STRODE M.': 'R',
 'DU PASQUIER I.': nan,
 'WEISE W055 B.': 'R',
 'DIETER BEUTEL H.': 'R',
 'PETER KANDLER H.': 'R',
 'DI LAURA C.': 'L',
 'ARTURO GONZALEZ L.': nan,
 'GARCIA G003 J.': 'R',
 'DE SOUSA M.': nan,
 'VELASCO JR J.': 'R',
 'AXEL HAGESKOG C.': 'R',
 'DE PALMER M.': 'L',
 'MARC PIACENTILE J.': 'R',
 'HUA LIU S.': nan,
 'WOOK SONG D.': 'L',
 'VAN LANGENDONCK J.': 'R',
 'VAN BOECKEL H.': 'R',
 'VAN NOSTRAND J.': 'R',
 'PEREZ PASCAL F.': 'R',
 'QIN MA K.': 'R',
 'DEL ROSARIO A.': nan,
 'UL HAQ I.': nan,
 'UL HAQ H.': nan,
 'CUNHA SILVA J.': 'R',
 'MAJID SOUDANI A.': nan,
 'LA PENA H. D.': 'L',
 'DE MIGUEL D.': 'R',
 'VAN RENSBURG C.': 'R',
 'TAIK RO G.': 'R',
 'SOO KIM B.': 'R',
 'GUIDO UTZINGER D.': 'R',
 'SUN YOO J.': 'R',
 'DE MINICIS A.': 'R',
 'ZVEREV SR A.': 'R',
 'ANTONIO RODRIGUEZ J.': 'R',
 'BUD COX C.': 'R',
 'DEN DAELE T. V.': 'R',
 'PHILIPPE FLEURIAN J.': 'R',
 'WILLEM LODDER J.': 'R',
 'PEREZ ROLDAN G.': 'R',
 'UWE STEEB C.': 'L',
 'KHALEK NADINI A.': 'R',
 'ERIK RUSTAD J.': nan,
 'ANDERS WAHLGREN L.': 'R',
 'RODRIGUEZ SANCHEZ T.': nan,
 'EL AROUSY H.': 'R',
 'YAW LIU W.': nan,
 'BIN SIDEK H.': nan,
 'OVE PEDERSEN B.': 'R',
 'RAHMAN SHEHAB A.': 'R',
 'AL ALI H.': nan,
 'AL FOUDARI K.': nan,
 'HUA ZHANG J.': 'R',
 'ARAMBURU ACUNA A.': 'R',
 'YVES JOB J.': nan,
 'JACQUES KOUASSI J.': nan,
 'VAN EMBURGH G.': 'R',
 'ANTONIO FERNANDEZ J.': 'R',
 'LUIS APARISI J.': 'R',
 'FRANCISCO ALTUR J.': 'L',
 'AURELIO GORRIZ M.': 'L',
 'CARLOS BAGUENA J.': 'R',
 'EL SAWY T.': 'R',
 'EL SALAWY K.': nan,
 'THOME BOLANOS K.': 'R',
 'VHEI KAM K.': nan,
 'HUI LIEN Y.': 'R',
 'PING XIA J.': 'R',
 'SIK KIM J.': 'R',
 'DE SILVA R.': nan,
 'EL AYNAOUI Y.': 'R',
 'KODES JR J.': 'R',
 'PEPE CONDE J. A.': 'R',
 'AVALOS BRENES R.': 'R',
 'CHAVEZ MORALES D.': nan,
 'ADRIAN MOREJON L.': 'R',
 'JONG CHANG E.': 'R',
 'HO JI S.': 'R',
 'YI KHO T.': 'R',
 'MOHAMMED ALMUQAIL B.': nan,
 'JUNG CHEN C.': 'R',
 'WAN KIM C.': 'R',
 'LAL RAHMAN H.': nan,
 'CHAO LIN B.': 'R',
 'ABOU HAMDEH E.': nan,
 'TAT LIM Y.': nan,
 'KEVIN GOELLNER M.': 'R',
 'VILOCA PUIG J. A.': 'R',
 'GISBERT JR J.': 'R',
 'YEN CHIANG J.': 'R',
 'REZA TAVAKOLI M.': nan,
 'KHALIQ SIDDIQ M.': nan,
 'IL YOON Y.': 'R',
 'CHEOL SHIN H.': 'R',
 'BENFELE ALVAREZ E.': 'R',
 'VAN HERCK J.': 'R',
 'JAN DAVIDS H.': 'L',
 'LUIS NORIEGA J.': 'R',
 'TATI RASCON J. L.': 'R',
 'YEN CHEN C.': nan,
 'HUAT KHOO K.': nan,
 'YU SU W.': 'R',
 'VAN GARSSE C.': 'R',
 'LOPEZ MORON A.': 'R',
 'TAIK LEE H.': 'R',
 'PEREZ CHETE L.': nan,
 'JU CHEN W.': 'R',
 'KOLL FRAFJORD H.': nan,
 'IMAZ RUIZ J.': 'R',
 'YEN TSAI C.': 'R',
 'VENERO MONTES A.': nan,
 'AL ANAZI O.': nan,
 'TETTEH QUAYE I.': nan,
 'VAN SCHEPPINGEN D.': 'R',
 'ARNOLD KER L.': 'R',
 'FRODE ANDERSEN J.': 'L',
 'MICHAEL GAMBILL J.': 'R',
 'NAVARRO BATLES L.': 'R',
 'ANTONIO MARIN J.': 'R',
 'LUEN WONG W.': nan,
 'NASIR SHERAZI S.': nan,
 'VAN LOTTUM J.': 'R',
 'FRANCOIS BACHELOT J.': 'R',
 'DI PASQUALE A.': 'R',
 'DE ARMAS J.': 'R',
 'EL DEEB G.': 'R',
 'WEI WANG Y.': 'R',
 'AL KHULAIFI N. G.': 'R',
 'HASSANI NAFEZ S.': 'R',
 'BAPTISTE PERLANT J.': 'R',
 'HAQ QURESHI A. U.': 'R',
 'QIANG ZHU B.': 'R',
 'TAHERI RAHAGHI S. A.': nan,
 'CARLOS FERRERO J.': 'R',
 'JEN CHENG W.': 'R',
 'MARTINEZ BREIJO S.': 'R',
 'EL AAREJ M.': 'R',
 'BRUCE LI S.': 'R',
 'RENE LISNARD J.': 'R',
 'IGNACIO CHELA J.': 'R',
 'CHILE FONTE R.': nan,
 'HENRI MATHIEU P.': 'R',
 'SUSILO PRAMONO H.': 'R',
 'ZHU YANG J.': 'R',
 'JULIEN ROJER J.': 'R',
 'BROWN B395 M.': 'R',
 'AL ASHWAK H.': nan,
 'HSUN LU Y.': 'R',
 'HYUN KIM D.': 'R',
 'MEDINA ALVAREZ J.': 'L',
 'LUNG CHANG W.': nan,
 'RAMIREZ HIDALGO R.': 'R',
 'GALLARDO VALLES M.': 'R',
 'JR WANG Y.': 'L',
 'MING SI Y.': nan,
 'BAEZ BRITEZ E. D.': 'R',
 'SEOK CHUNG H.': 'R',
 'MEDINA SOBRINO Y.': nan,
 'TUNG YU H.': 'L',
 'ADJEI DARKO H.': nan,
 'DE CHAUNAC S.': 'R',
 'DE LEON J.': 'R',
 'FELIPE NORIEGA L.': nan,
 'DE VOEST R.': 'R',
 'BOGOMOLOV JR A.': 'R',
 'HEE KWON O.': 'R',
 'DON GRUBER K.': 'R',
 'GONZALEZ GONZALEZ E.': 'R',
 'MANUEL FLORES L.': 'L',
 'XUAN ZENG S.': 'R',
 'JIMENEZ GUERRA J.': 'R',
 'GERBAUD FARRAS P.': nan,
 'JUN KIM Y.': 'R',
 'AL JAZZAF M.': nan,
 'FARAH LEBAR W.': nan,
 'TAE IM K.': 'R',
 'WOO NAM H.': 'R',
 'YUAN YU X.': 'L',
 'GONZALEZ DIAZ R.': 'R',
 'WEI LIU T.': 'L',
 'DI MAURO A.': 'L',
 'YI LI J.': nan,
 'PALLARES GONZALEZ M. R.': 'R',
 'SUN JUN W.': 'R',
 'PABLO GUZMAN J.': 'L',
 'GARCIA LOPEZ G.': 'R',
 'VASSALLO ARGUELLO M.': 'R',
 'WILFRIED TSONGA J.': 'R',
 'ROGER VASSELIN E.': 'R',
 'VAN GEMERDEN M.': 'R',
 'SEBASTIAN LANGTON J.': 'R',
 'KIM JR S. Y.': 'R',
 'SUNG AN J.': 'R',
 'RUBIN STATHAM J.': 'R',
 'CHRISTOPHE FAUREL J.': 'R',
 'GIMENO TRAVER D.': 'R',
 'DEL POTRO J. M.': 'R',
 'LORENZO GONZALEZ J.': nan,
 'ROBERTO VELASCO J.': 'R',
 'FRANCISCO FELIX J.': nan,
 'KING TURNER D.': 'R',
 'RABEEA MUHAMMAD A.': 'R',
 'DE BAKKER T.': 'R',
 'ANDRES GOMEZ J.': nan,
 'DER MERWE I. V.': 'R',
 'HAIDER MAURER A.': 'R',
 'CESAR CAMPOZANO J.': 'R',
 'MICHEL DURANGO J.': 'R',
 'CARLOS RAMIREZ J.': 'R',
 'MANUEL ELIZONDO J.': nan,
 'HERNANDEZ PEREZ E.': nan,
 'JOSE SURIANO B.': nan,
 'VAN ROSBERG N.': 'R',
 'SLETTING JOHNSEN F.': 'R',
 'PABLO BRZEZICKI J.': 'R',
 'HUTA GALUNG J.': 'R',
 'DORIA MEDINA M.': 'L',
 'AL NABHANI K.': 'R',
 'AL NABHANI M.': 'R',
 'HARI SASONGKO A.': nan,
 'TRUJILLO SOLER G.': 'R',
 'LOPEZ JAEN M. A.': 'R',
 'EL AMRANI R.': 'R',
 'CLAUDE SCHERRER J.': 'R',
 'SEBASTIAN CABAL J.': 'R',
 'HUA YANG T.': 'R',
 'CASEY ALCANTARA F.': nan,
 'VAN HAASTEREN M.': 'R',
 'DIAZ FIGUEROA C.': 'R',
 'WAI HUI C.': 'R',
 'OLIVER STATHAM M.': 'R',
 'CONRAD HUEY T.': 'L',
 'XIN GONG M.': 'R',
 'WAHYU TRIJATI S.': 'R',
 'AGUNG SUSANTO D.': nan,
 'KELVIN LAM S. F.': 'R',
 'DE OLIVEIRA A. R.': nan,
 'LA NAVA D. M. D.': 'L',
 'JOON KIM H.': 'L',
 'KYU LIM Y.': nan,
 'HAN LEE H.': 'R',
 'BIN ZAINUDDIN A. H.': 'R',
 'LOPEZ CASSACCIA D. A.': 'R',
 'YOUNG JEONG S.': 'R',
 'JAE CHO S.': 'R',
 'DUTRA SILVA R.': 'R',
 'ABDEL NOUR B.': nan,
 'VAN WYK C.': 'R',
 'FLORES RUIZ G.': nan,
 'DE VEIGY J. D.': 'L',
 'MARCEL STEBE C.': 'L',
 'LUDOVIC DUCLOS P.': 'R',
 'HYOEK CHO M.': 'R',
 'CHI HUANG L.': 'R',
 'MOHAMED MAAMOUN K.': 'R',
 'DE ALWIS V.': 'R',
 'DAVID MARTINEZ L.': nan,
 'BAUTISTA AGUT R.': 'R',
 'ADI NUGROHO W.': nan,
 'GUTIERREZ FERROL S.': 'R',
 'CERVANTES HUEGUN I.': 'R',
 'DE SCHEPPER K.': 'L',
 'SUNG NAM J.': 'R',
 'REYES VARELA M. A.': 'R',
 'PANTA HERREROS J. B.': nan,
 'AL TAWIL I.': 'R',
 'GASPAR MURTA A.': nan,
 'BRUGUES DAVI A.': 'L',
 'SEBASTIAN SCHWARTZMAN D.': 'R',
 'CARRENO BUSTA P.': 'R',
 'LENNARD STRUFF J.': 'R',
 'HUGUES HERBERT P.': 'R',
 'FERREIRA SILVA F.': 'L',
 'NGUYEN HOANG T.': 'R',
 'GIANG TRINH L.': nan,
 'QUAN DO M.': 'R',
 'CARBALLES BAENA R.': 'R',
 'PODLIPNIK CASTILLO H.': 'R',
 'CHEN HUNG J.': 'R',
 'FU WANG C.': nan,
 'DE GREEF A.': 'R',
 'HARRY FRITZ T.': 'R',
 'PATRICK SMITH J.': 'L',
 'KHAN AKBAR M. A. A.': nan,
 'CHAN HONG S.': 'R',
 'JACQUES RAKOTOHASY J.': nan,
 'CARLOS SAEZ J.': 'R',
 'GALAN RIVEROS D. E.': nan,
 'GOMEZ GB42 A.': nan,
 'MENENDEZ MACEIRAS A.': 'R',
 'HACH VERDUGO H.': nan,
 'ANGEL ESTE M.': nan,
 'MUIRHEAD HARRIS L. G.': 'R',
 'ASSRI MERZUKI M.': 'R',
 'PATINO SAMUDIO J. P. V.': 'R',
 'HOANG LY N.': 'R',
 'YI LEE K.': nan,
 'DE LOORE J.': 'R',
 'DE MINAUR A.': 'R',
 'BARRIOS VERA M. T.': nan,
 'MUNOZ ABREU J.': nan,
 'HESS OLESEN S.': nan,
 'SUNDE BRATHOLM S.': 'R',
 'REZA NADAF H.': 'R',
 'JACK WONG H. K.': nan,
 'OJEDA LARA R.': nan,
 'PEDRO SORGI J.': 'R',
 'ANDREA HUESLER M.': nan,
 'CHAVEZ VILLALPANDO L. D.': nan,
 'JACKIE TANG A.': nan,
 'HSIN TSENG C.': 'R',
 'DECASA OTICO J. B.': nan,
 'AUGER ALIASSIME F.': 'R',
 'NODSKOV RUNE H. V.': nan,
 'LOPEZ VILLASENOR G.': nan,
 'ZAPATA MIRALLES B.': 'R',
 'ROCA BATALLA O.': 'R',
 'IGNACIO LONDERO J.': 'R',
 'SEYBOTH WILD T.': 'R',
 'DE WITTS J.': 'R',
 'DE ZEEUW J.': 'R',
 'LOUIS THIEBAUT J.': nan,
 'DE TROYE B.': 'R',
 'CLAUDE MOLINARI J.': 'R',
 'SON LEE E.': nan,
 'RAHMAN BAKAR A.': nan,
 'ERIK ROSS J.': nan,
 'MCNAIR III F.': nan,
 'VAN LINGEN P.': nan,
 'AUGUSTO GARCIA L.': nan,
 'MARIA BLASI J.': 'R',
 'OQUENDO SR U.': nan,
 'CARLOS RODRIGUEZ J.': 'R',
 'KEAN TAN S.': nan,
 'VAN EYSDEN P.': nan,
 'VAN NOSTRAND K.': 'R',
 'ERIK LINDQUIST J.': nan,
 'YUAN LIN C.': nan,
 'SHUN TANG F.': nan,
 'MINH DUONG V.': nan,
 'EL KHOURY S.': nan,
 'ERIK NIELSEN K.': nan,
 'MERWE A A. V. D.': nan,
 'MERWE B A. V. D.': 'R',
 'D NEER J.': nan,
 'RENE CRUZ O.': nan,
 'ARIF ELAHI M.': nan,
 'SUTA WIBAWA A.': nan,
 'VAZ CARVALHAES R.': nan,
 'AKBAR BABA M.': nan,
 'CHING LEE W.': nan,
 'LUNG MA Y.': nan,
 'TUAN DINH Q.': nan,
 'MARTIN JR D.': 'R',
 'VAZQUEZ BARREIRA E.': nan,
 'SENG TAN P.': nan,
 'WEN LIN D.': nan,
 'YAN LIN Y.': nan,
 'PIVA NETO O.': nan,
 'CARLOS ENCK L.': 'R',
 'JANSE SIMS B.': 'R',
 'ERIC PALM J.': 'R',
 'DE SILVA E.': nan,
 'ALBERTO OLMEDO L.': nan,
 'EL GHANI A.': nan,
 'PIERRE RICHER J.': 'R',
 'KAMEL BOUDJEMLINE F.': nan,
 'ABDUL FATAH M.': nan,
 'FELIPE SILVA L.': nan,
 'MANUEL HIDALGO J.': 'R',
 'HONG NI C.': 'R',
 'LUC COTARD J.': 'R',
 'GONZALEZ G162 P.': 'R',
 'MUNCH SOEGAARD J.': nan,
 'VAN RENSBURG J.': 'R',
 'RUIZ BRY E.': 'R',
 'DE WET H.': 'R',
 'RYONG LEE W.': 'R',
 'YUEN PANG C.': nan,
 'BEN FARHAT R.': nan,
 'PEDERSEN JENTOFT G.': nan,
 'ANTONIO GARCIA J.': 'R',
 'CARLOS YUNIS J.': 'R',
 'RAHMAN RAMLAL A.': nan,
 'QIN LI S.': nan,
 'DE OCA D. M.': 'R',
 'WAH LIU S.': 'R',
 'DER MERWE M. V.': 'R',
 'WAH YEO K.': nan,
 'CASIE CHITTY N.': nan,
 'HALEM AZZI A.': nan,
 'VAN KAUVENBERGH M.': nan,
 'UKON U004 K.': 'R',
 'MONEM BORNAZ A.': nan,
 'EL RAGIG S.': nan,
 'NILO NATIVIDAD R.': 'R',
 'CARLOS ANDRADE J.': 'R',
 'DI MAURO F.': 'R',
 'AH PENG T.': nan,
 'DE PRETER J.': 'R',
 'ION NASTASE M.': 'R',
 'WELLS ROTH D.': 'R',
 'PABLO QUEIROLO J.': 'R',
 'CHUAN CHOW C.': nan,
 'AL ZUBAIDI A.': nan,
 'BEN ISMAIL M.': nan,
 'DE FOOR J.': 'R',
 'LELLI MAMI G.': 'R',
 'PETER BUDGE I.': 'R',
 'MIN KWON Y.': 'R',
 'CARLOS BIANCHI J.': 'R',
 'AL ASHWAK A. I.': nan,
 'AL KHALIL A.': nan,
 'KAHAR MIM A.': 'R',
 'RASHID BHUIYAN B.': nan,
 'LEONG WONG C.': nan,
 'HAKIM JTELI A.': nan,
 'DE JAGER J. L.': 'R',
 'AHMED SALEH M.': nan,
 'ABOU JABER A.': nan,
 'JONSSON J092 O.': 'R',
 'ABDUL ALI N.': nan,
 'SANJAYA WIJEMANNE M.': nan,
 'SO LEE J.': 'R',
 'HENRY TORRIENTE W.': nan,
 'GEORG RAABE A.': nan,
 'JU BAE N.': 'R',
 'CHENG LIU X.': nan,
 'ROBERTO PAEZ C.': nan,
 'HUSSAIN FITIANI K.': nan,
 'AL IBRAHIM T.': nan,
 'YIEP HO K.': nan,
 'ABDUL RAHIM M. R.': nan,
 'SYED HAQ F.': nan,
 'PABLO ETCHECOIN J.': 'R',
 'SUHENDAR DINATA D.': 'R',
 'KEUN SONG H.': 'R',
 'PEREZ HUBERT M.': 'R',
 'FONG CHANG C.': 'R',
 'AL SHATTI A.': nan,
 'AL MAHMEED A.': nan,
 'BEN HADJALI S.': nan,
 'GOMEZ BARRIO S.': 'R',
 'PETRE PORUMB C.': 'R',
 'DE BEER J.': 'R',
 'MIN LAM J.': nan,
 'AL SOMALI F.': nan,
 'WOONG YOON J.': 'R',
 'HADJ DIEDHIOU E.': nan,
 'NOEL SAID J.': nan,
 'NAVARRO VERGARA C. M.': nan,
 'HANSEN DENT B.': 'R',
 'HOON LEE S.': 'R',
 'KYU HAN M.': 'R',
 'RAIS ALI S.': nan,
 'DEL RIO D.': 'R',
 'WEI TAN E.': nan,
 'XIONG HUI Y.': nan,
 'SALVADOR ESTEPA D.': 'R',
 'HAMID MAKHKAMOV A.': 'R',
 'JOHN MISA M.': nan,
 'IVANOV SMOLENSKY K.': 'R',
 'AL HAJI K.': nan,
 'AL TOBAISHI M.': nan,
 'FRANCISCO BARRAGAN J.': nan,
 'MAX MANGONES J.': nan,
 'KOME LOGLO J.': nan,
 'SUNG CHUNG H.': 'R',
 'PISUTH ARNONTH E.': 'R',
 'DIEGO NUNEZ L.': nan,
 'LEON ZAMORA K.': nan,
 'FUZI NASRUDDIN M. N.': nan,
 'HARPER GRIFFITH L.': 'R',
 'HERM ZAHLAVA J.': 'R',
 'BOK BAEK S.': 'R',
 'SUNDERA KARUPPIAH M. R.': nan,
 'VAN GRICHEN A.': nan,
 'CARLOS GONZALEZ J.': nan,
 'PABLO BARBOZA J.': nan,
 'ENRIQUE CROSA J.': 'R',
 'AL KASIM Y.': nan,
 'FISER DULIC R.': 'R',
 'GARCIA SINTES J.': 'R',
 'HEIN BOEKEL P.': nan,
 'ALBERT FERRANDO M.': 'R',
 'REBAZA LOZANO J. C.': 'R',
 'TUILIER CURCO K.': nan,
 'ANTONIO VELAZQUEZ J.': nan,
 'BEN SOLTANE T.': nan,
 'FREYRE PERDOMO F. A.': nan,
 'NOOR NOORDIN M.': nan,
 'MATOS GIL I.': nan,
 'DER MEER N. V.': nan,
 'ALBERTO CAYO M.': nan,
 'BABA AISSA R.': nan,
 'RODRIGUEZ SANCHEZ O.': nan,
 'JOON SUK H.': 'R',
 'RICCIARDI CASTELLI A.': nan,
 'PAUL FRUTTERO J.': 'R',
 'DE LUNA J. A. S.': 'R',
 'BIN OTHMAN M. F.': nan,
 'DER DUIM A. V.': 'R',
 'HUAN YI C.': 'L',
 'EL KHOURY J.': 'R',
 'ABOU CHAHINE I.': 'R',
 'SALVA VIDAL B.': 'L',
 'LUQUE VELASCO D.': nan,
 'MARTIN ARANGUREN J.': 'R',
 'CUELLAR CONTRERAS L. J.': nan,
 'REDHA OUAHAB M.': nan,
 'MUMIN BABALOLA A.': 'L',
 'RIISE HANSEN P.': nan,
 'FORNELL MESTRES M.': 'R',
 'AL BALOUSHI M. N.': nan,
 'AL RAWAHI S.': nan,
 'ESCOBAR SERRANO C.': nan,
 'CHAO XU J.': nan,
 'DA SILVA D. D.': 'L',
 'ALI AKKAL S.': nan,
 'AL MOUSA H.': nan,
 'ELBERTO ANASTA V.': nan,
 'ALEXANDRU LUNCANU P.': 'L',
 'SAAVEDRA CORVALAN C.': 'R',
 'ANTONIO ROJAS M.': nan,
 'DEEN HESHAAM A. E.': 'R',
 'DIAS CONDUTO C.': nan,
 'FORBERG SKOGENG A.': nan,
 'ALVARADO LARIN A. E.': nan,
 'HOSSEIN ZADE M.': nan,
 'MARC BAZANNE J.': 'R',
 'RIVERA ARANGUIZ G.': 'R',
 'SEBASTIAN VIVANCO J.': 'R',
 'DIAZ BARRIGA L.': 'R',
 'AURELIO NUNEZ M.': 'L',
 'AL MUTAWA J.': nan,
 'NAN MA Y.': nan,
 'MIN SEOL J.': nan,
 'WOONG NA J.': nan,
 'FLORIN BRAGUSI D.': nan,
 'GOMEZ HERRERA C.': 'R',
 'SHANAN ZAYED M.': nan,
 'VIRALI MURUGESAN R.': nan,
 'AL OBAIDLY N.': nan,
 'DE KLERK J. C.': nan,
 'YIN PENG H.': nan,
 'ANDRES BOLANOS S.': nan,
 'ARTUNEDO MARTINAVARR A.': 'R',
 'HUY NGO Q.': 'R',
 'DE PAULA F.': 'R',
 'TZUF BOTZER B.': 'R',
 'SUNDAR PRASHANTH N. V.': 'R',
 'KOCEVAR DESMAN T.': 'R',
 'SAYED HASHIM D.': 'L',
 'VEGA HERNANDEZ D.': 'R',
 'VAN RIJTHOVEN T.': 'R',
 'AL HARRASI M.': nan,
 'YIM KIM F.': 'R',
 'ESCURRA ISNARDI H. J.': nan,
 'SYED NAGUIB S. M. A.': 'R',
 'SHENG KOAY H.': nan,
 'JOHN LOCK C.': 'R',
 'ORTEGA OLMEDO R.': nan,
 'SAMPER MONTANA J.': nan,
 'TIEN NGUYEN D.': nan,
 'LOPEZ PEREZ E.': 'R',
 'HEE LEE D.': 'R',
 'WOO KWON S.': 'R',
 'WILBERT MAJOR P.': 'L',
 'NIKLAS SALMINEN P.': nan,
 'ANDREW LI H. Y.': 'R',
 'SON KWIATKOWSKI T.': nan,
 'FOSTER ESTWICK M.': nan,
 'AUGUST ANKER P.': nan,
 'GONZALEZ RETANA R. E.': 'R',
 'HOSSEIN BADI A.': nan,
 'YU YU C.': nan,
 'ALTHAF DHAIFULLAH M.': 'R',
 'DE SILVA Y.': nan,
 'AYANDA SIBANDA M. D.': 'R',
 'HUN WONG C.': 'R',
 'EL MESBAHI S.': 'R',
 'MARTINEZ PORTERO P.': 'R',
 'SRIRAM BALAJI N.': 'R',
 'MINGJIE LIN J.': nan,
 nan: nan}

In [745]:
def set_hand_2():
    def get_hand(p):
        try:
            val = players_hands_dict[p]
        except:
            val = np.nan
        return val
    
    dataframe['HandA'].fillna(dataframe[dataframe['HandA'].isna()]['Winner'].apply(get_hand), inplace = True)
    dataframe['HandB'].fillna(dataframe[dataframe['HandB'].isna()]['Loser'].apply(get_hand), inplace = True)

In [746]:
set_hand_2()

In [747]:
dataframe[dataframe['HandA'].isna()]['Winner'].append(dataframe[dataframe['HandB'].isna()]['Loser']).unique().tolist()

['GAMBILL J.M.',
 'CHELA J.I.',
 'FERRERO J.C.',
 'MARIN J.A.',
 'VILOCA J.A.',
 'LISNARD J.R.',
 'GOELLNER M.K.',
 'LEE H.T.',
 'ANDERSEN J.F.',
 'ALVAREZ E.',
 'YOON Y.',
 'MATHIEU P.H.',
 'BACHELOT J.F',
 'BOGOMOLOV JR.A.',
 'HANTSCHEK M.',
 'SCHUTTLER P.',
 'BOGOMOLOV JR. A.',
 'YOUZHNY A.',
 'BOGOMOLOV A.',
 'ASCIONE A.',
 'KUCERA V.',
 'GUZMAN J.P.',
 'GARCIA-LOPEZ G.',
 'LU Y.H.',
 'ANCIC I.',
 'FLANAGAN I.',
 'VERDASCO M.',
 'VASSALLO-ARGUELLO M.',
 'BAGHDATIS M.',
 'TSONGA J.W.',
 'ROGER-VASSELIN E.',
 'ZHU B.Q.',
 'WANG Y.T.',
 'NAVARRO-PASTOR I.',
 'WANG Y. JR',
 'FAUREL J.C.',
 'GIMENO-TRAVER D.',
 'AL GHAREEB M.',
 'QUERRY S.',
 'HAIDER-MAURER A.',
 'ROBREDO R.',
 'STEPANEK M.',
 'BRZEZICKI J.P.',
 'QURESHI A.',
 'GUCCIONE A.',
 'TRUJILLO G.',
 'LOPEZ-JAEN M.A.',
 "DELL'ACQUA M.",
 'QURESHI A.U.H.',
 'JUN W.S.',
 'DE HEART R.',
 'SCHERRER J.C.',
 'VAN DER MERWE I.',
 'ZENG S.X.',
 'STATHAM J.',
 'RAMOS-VINOLAS A.',
 'MUNOZ DE LA NAVA D.',
 'KUZNETSOV AN.',
 'DASNIERES DE VEIGY J.',
 'OLASO G.',
 'STEBE C.M.',
 'DEL BONIS F.',
 'DUCLOS P.L.',
 'DUTRA DA SILVA R.',
 'ZHANG Z.',
 'BAUTISTA R.',
 'GUTIERREZ-FERROL S.',
 'CERVANTES I.',
 'REIX C.',
 'BRUGUES-DAVI A.',
 'SCHWARTZMAN D.',
 'STRUFF J.L.',
 'KUZNETSOV AL.',
 'ESTRELLA BURGOS V.',
 'HERBERT P.H.',
 'MILOJEVIC N.',
 'DAVYDENKO P.',
 'KOHLSCHREIBER P..',
 'FRITZ T.',
 'SMITH J.P.',
 'MENENDEZ-MACEIRAS A.',
 'GALAN D.E.',
 'GOMEZ A.',
 'MUNAR J.',
 'HERBERT P.H',
 'ZHANG ZH.',
 'ZHANG ZE',
 'OPELKA R.',
 'AHOUDA A.',
 'SILVA F.F.',
 'HANFMANN Y.',
 'BONZI B.',
 'ALTMAIER D.',
 'ZEKIC M.',
 'TRAVAGLIA S.',
 'MADEN Y.',
 'BERRETTINI M.',
 'OJEDA LARA R.',
 'AUGER-ALIASSIME F.',
 'VATUTIN A.',
 'HUESLER M.A.',
 'HARRIS L.',
 'WATANUKI Y.',
 'POPYRIN A.',
 'LONDERO J.I.',
 'SINNER J.',
 'DAVIDOVICH FOKINA A.',
 'BENCHETRIT E.',
 'CELIKBILEK A.',
 'SERDARUSIC N.',
 'KWON S.W.',
 'KING K.',
 'MORONI G.',
 'POLMANS M.',
 'LEE D.H.',
 'BROOKSBY J.',
 'AVIDZBA A.',
 'AL-ALAWI S.K.',
 "O'BRIEN A.",
 'BAHROUZYAN O.',
 'HERM-ZAHLAVA J.',
 'PFEIFFER K.',
 'HARSANYI P.',
 'HARPER-GRIFFITH L.',
 'WANG Y.',
 'GARCIA-SINTES J.',
 'AL KHULAIFI N.G.',
 'WILLMAN D.',
 'MARIN L.',
 'IVANOV-SMOLENSKY K.',
 'KUNITCIN I.',
 'MIYAO J.',
 'MATHIEU P.',
 'KODERISCH C.',
 'PRPIC A.',
 'LEVINE I.',
 'DAVLETSHIN V.',
 'GALLARDO M.',
 'MATOS-GIL I.',
 'VAN DER MEER N.',
 'LU Y.',
 'BENNETEAU A.',
 'GRUBER K.',
 'RASCON T.',
 'ABDULLA M.',
 'JONES G.D.',
 'MARCH O.',
 'DAILEY Z.',
 'CONDOR F.',
 'KORTELING S.',
 'FRUTTERO J.P.',
 'DO M.Q.',
 'SANCHEZ DE LUNA J.A.',
 'SULTAN-KHALFAN A.',
 'KING-TURNER D.',
 'VAN DER DIUM A.',
 'GRANOLLERS-PUJOL M.',
 'SALVA B.',
 'LUQUE D.',
 'VICENTE M.',
 'KUTAC R.',
 'DEV VARMAN S.',
 'YU X.Y.',
 'WANG Y. JR.',
 'ARANGUREN J.M.',
 'FISH A.',
 'JUN W.',
 'FORNELL M.',
 'CHAKI R.',
 'GUZMAN J.',
 'GORANSSON T.',
 'RUEVSKI P.',
 'NAM H.W.',
 'CHEKOV P.',
 'HAJI A.',
 'STATHAM R.',
 'PODLIPNIK H.',
 'NADER M.',
 'MARRAI M.',
 'KIM K',
 "O'NEAL J.",
 'XU J.C.',
 'HAJJI A.',
 'SILVA D.',
 'RIBA-MADRID P.',
 'LUNCANU P.A.',
 'GONG M.X.',
 'YANG T.H.',
 'IM K.T.',
 'SI Y.M.',
 'SABRY S.',
 'GRANOLLERS PUJOL G.',
 'WALTER L.',
 'AL MUTAWA J.',
 'VIOLA MAT.',
 'CABAL J.S.',
 'IDMBAREK Y.',
 'GOMEZ-HERRERA C.',
 'TRUSENDI W.',
 'MEISTER N.',
 'DEEN HESHAAM A.',
 'ALI MUTAWA J.M.',
 'ZAYED M. S.',
 'REYES-VARELA M.A.',
 'CORRIE E.',
 'WARD A.',
 'TOPIC J.',
 'BOGAERTS R.',
 'JEONG S.Y.',
 'NEDOVYESOV O.',
 'ARTUNEDO MARTINAVARRO A.',
 'HANK T.',
 'VAISSE M.',
 'SMETHURST D.',
 'PASHA N.',
 'GAO X.',
 'HERBERT P-H.',
 'PRASHANTH V.',
 'QUIGLEY E.',
 'SILVA F.',
 'SHANE R.',
 'NIKI T.',
 'ANDERSON O.',
 'LAZOV A.',
 'GOMEZ L.',
 'ORTEGA-OLMEDO R.',
 'SAMPER-MONTANA J.',
 'MOELLER M.',
 'BELLIER A.',
 'LOPEZ-PEREZ E.',
 'SMITH A.',
 "O'CONNELL C.",
 'MOTT B.',
 'ALAWADHI O.',
 'MULLER A.',
 'KWIATKOWSKI T.S.',
 'HERNANDEZ-FERNANDEZ J.',
 'LESHEM E.',
 'KYPSON P.',
 'TYURNEV E.',
 'TAKAHASHI Y.',
 'SAFIULLIN R.',
 'CARUANA L.',
 'DONSKI A.',
 'ANDREEV A.',
 'KORDA S.',
 'GASTON H.',
 'MARTINEZ P.',
 'PIROS Z.',
 'JANVIER M.',
 'PURCELL M.',
 'KOLAR Z.',
 'RODIONOV J.',
 'GOJO B.',
 'TSENG C.H.',
 'CERUNDOLO F.',
 'LIN J.M.',
 'LOPEZ VILLASENOR G.',
 'NAVA E.',
 'SAKAMOTO P.',
 'BASSO A.',
 'MORAING M.',
 'ARAGONE JC',
 'KIRKIN E.',
 'JUBB P.',
 'GRAY A.',
 'GROMLEY C.',
 'LENZ J.',
 'MONTEIRO J.',
 'SARMIENTO R.',
 'SVAJDA Z.',
 'ROUMANE R.',
 'ZHANG ZE.',
 'DUBRIVNYY A.',
 'KACHMAZOV A.']

In [748]:
players_hands = extradf[['winner_name3','winner_hand']].drop_duplicates().append(
    extradf[['loser_name3','loser_hand']].rename(columns = {'loser_name3': 'winner_name3',
                                                                             'loser_hand': 'winner_hand'}), 
    ignore_index = True).drop_duplicates()

In [749]:
import numpy as np
players_hands['winner_hand'] = players_hands['winner_hand'].apply(lambda x:np.nan if x == 'U' else x)
players_hands['winner_hand'].dropna(inplace = True, axis = 0)
players_hands['winner_name3'].dropna(inplace = True, axis = 0)

In [750]:
players_hands_dict = {p:np.nan for p in players_hands['winner_name3']}
for i in players_hands.itertuples():
    players_hands_dict[i.winner_name3] = i.winner_hand

In [751]:
set_hand_2()

In [752]:
len(dataframe[dataframe['HandA'].isna()]['Winner'].append(dataframe[dataframe['HandB'].isna()]['Loser']).unique().tolist())

235

In [753]:
players_hands = extradf[['winner_name4','winner_hand']].drop_duplicates().append(
    extradf[['loser_name4','loser_hand']].rename(columns = {'loser_name4': 'winner_name4',
                                                                             'loser_hand': 'winner_hand'}), 
    ignore_index = True).drop_duplicates()

import numpy as np
players_hands['winner_hand'] = players_hands['winner_hand'].apply(lambda x:np.nan if x == 'U' else x)
players_hands['winner_hand'].dropna(inplace = True, axis = 0)
players_hands['winner_name4'].dropna(inplace = True, axis = 0)

players_hands_dict = {p:np.nan for p in players_hands['winner_name4']}
for i in players_hands.itertuples():
    players_hands_dict[i.winner_name4] = i.winner_hand
    
set_hand_2()

In [754]:
len(dataframe[dataframe['HandA'].isna()]['Winner'].append(dataframe[dataframe['HandB'].isna()]['Loser']).unique().tolist())

219

In [755]:
dataframe[dataframe['HandA'].isna()]['Winner'].append(dataframe[dataframe['HandB'].isna()]['Loser']).unique().tolist()

['VILOCA J.A.',
 'ALVAREZ E.',
 'YOON Y.',
 'BACHELOT J.F',
 'BOGOMOLOV JR.A.',
 'HANTSCHEK M.',
 'SCHUTTLER P.',
 'BOGOMOLOV JR. A.',
 'YOUZHNY A.',
 'BOGOMOLOV A.',
 'ASCIONE A.',
 'KUCERA V.',
 'ANCIC I.',
 'FLANAGAN I.',
 'VERDASCO M.',
 'BAGHDATIS M.',
 'WANG Y.T.',
 'NAVARRO-PASTOR I.',
 'WANG Y. JR',
 'AL GHAREEB M.',
 'QUERRY S.',
 'ROBREDO R.',
 'STEPANEK M.',
 'QURESHI A.',
 'GUCCIONE A.',
 'TRUJILLO G.',
 'LOPEZ-JAEN M.A.',
 "DELL'ACQUA M.",
 'DE HEART R.',
 'VAN DER MERWE I.',
 'STATHAM J.',
 'RAMOS-VINOLAS A.',
 'MUNOZ DE LA NAVA D.',
 'KUZNETSOV AN.',
 'DASNIERES DE VEIGY J.',
 'OLASO G.',
 'DEL BONIS F.',
 'DUTRA DA SILVA R.',
 'ZHANG Z.',
 'BAUTISTA R.',
 'CERVANTES I.',
 'REIX C.',
 'SCHWARTZMAN D.',
 'KUZNETSOV AL.',
 'ESTRELLA BURGOS V.',
 'MILOJEVIC N.',
 'DAVYDENKO P.',
 'KOHLSCHREIBER P..',
 'FRITZ T.',
 'GALAN D.E.',
 'GOMEZ A.',
 'MUNAR J.',
 'HERBERT P.H',
 'ZHANG ZH.',
 'ZHANG ZE',
 'OPELKA R.',
 'AHOUDA A.',
 'HANFMANN Y.',
 'BONZI B.',
 'ALTMAIER D.',
 'ZEKIC M.',
 'TRAVAGLIA S.',
 'MADEN Y.',
 'BERRETTINI M.',
 'OJEDA LARA R.',
 'VATUTIN A.',
 'HUESLER M.A.',
 'HARRIS L.',
 'WATANUKI Y.',
 'POPYRIN A.',
 'SINNER J.',
 'DAVIDOVICH FOKINA A.',
 'BENCHETRIT E.',
 'CELIKBILEK A.',
 'SERDARUSIC N.',
 'KING K.',
 'MORONI G.',
 'POLMANS M.',
 'BROOKSBY J.',
 'AVIDZBA A.',
 'AL-ALAWI S.K.',
 "O'BRIEN A.",
 'BAHROUZYAN O.',
 'PFEIFFER K.',
 'HARSANYI P.',
 'WANG Y.',
 'AL KHULAIFI N.G.',
 'WILLMAN D.',
 'MARIN L.',
 'KUNITCIN I.',
 'MIYAO J.',
 'MATHIEU P.',
 'KODERISCH C.',
 'PRPIC A.',
 'LEVINE I.',
 'DAVLETSHIN V.',
 'GALLARDO M.',
 'MATOS-GIL I.',
 'VAN DER MEER N.',
 'LU Y.',
 'BENNETEAU A.',
 'GRUBER K.',
 'RASCON T.',
 'ABDULLA M.',
 'JONES G.D.',
 'MARCH O.',
 'DAILEY Z.',
 'CONDOR F.',
 'KORTELING S.',
 'SANCHEZ DE LUNA J.A.',
 'SULTAN-KHALFAN A.',
 'VAN DER DIUM A.',
 'GRANOLLERS-PUJOL M.',
 'SALVA B.',
 'LUQUE D.',
 'VICENTE M.',
 'KUTAC R.',
 'DEV VARMAN S.',
 'WANG Y. JR.',
 'FISH A.',
 'JUN W.',
 'FORNELL M.',
 'CHAKI R.',
 'GUZMAN J.',
 'GORANSSON T.',
 'RUEVSKI P.',
 'CHEKOV P.',
 'HAJI A.',
 'STATHAM R.',
 'PODLIPNIK H.',
 'NADER M.',
 'MARRAI M.',
 'KIM K',
 "O'NEAL J.",
 'XU J.C.',
 'HAJJI A.',
 'SILVA D.',
 'RIBA-MADRID P.',
 'SI Y.M.',
 'SABRY S.',
 'GRANOLLERS PUJOL G.',
 'WALTER L.',
 'AL MUTAWA J.',
 'VIOLA MAT.',
 'IDMBAREK Y.',
 'TRUSENDI W.',
 'MEISTER N.',
 'DEEN HESHAAM A.',
 'ALI MUTAWA J.M.',
 'ZAYED M. S.',
 'REYES-VARELA M.A.',
 'CORRIE E.',
 'WARD A.',
 'TOPIC J.',
 'BOGAERTS R.',
 'NEDOVYESOV O.',
 'ARTUNEDO MARTINAVARRO A.',
 'HANK T.',
 'VAISSE M.',
 'SMETHURST D.',
 'PASHA N.',
 'GAO X.',
 'HERBERT P-H.',
 'PRASHANTH V.',
 'QUIGLEY E.',
 'SILVA F.',
 'SHANE R.',
 'NIKI T.',
 'ANDERSON O.',
 'LAZOV A.',
 'GOMEZ L.',
 'ORTEGA-OLMEDO R.',
 'SAMPER-MONTANA J.',
 'MOELLER M.',
 'BELLIER A.',
 'SMITH A.',
 "O'CONNELL C.",
 'MOTT B.',
 'ALAWADHI O.',
 'MULLER A.',
 'KWIATKOWSKI T.S.',
 'HERNANDEZ-FERNANDEZ J.',
 'LESHEM E.',
 'KYPSON P.',
 'TYURNEV E.',
 'TAKAHASHI Y.',
 'SAFIULLIN R.',
 'CARUANA L.',
 'DONSKI A.',
 'ANDREEV A.',
 'KORDA S.',
 'GASTON H.',
 'MARTINEZ P.',
 'PIROS Z.',
 'JANVIER M.',
 'PURCELL M.',
 'KOLAR Z.',
 'RODIONOV J.',
 'GOJO B.',
 'CERUNDOLO F.',
 'LIN J.M.',
 'LOPEZ VILLASENOR G.',
 'NAVA E.',
 'SAKAMOTO P.',
 'BASSO A.',
 'MORAING M.',
 'ARAGONE JC',
 'KIRKIN E.',
 'JUBB P.',
 'GRAY A.',
 'GROMLEY C.',
 'LENZ J.',
 'MONTEIRO J.',
 'SARMIENTO R.',
 'SVAJDA Z.',
 'ROUMANE R.',
 'ZHANG ZE.',
 'DUBRIVNYY A.',
 'KACHMAZOV A.']

In [756]:
players_hands = extradf[['winner_name5','winner_hand']].drop_duplicates().append(
    extradf[['loser_name5','loser_hand']].rename(columns = {'loser_name5': 'winner_name5',
                                                                             'loser_hand': 'winner_hand'}), 
    ignore_index = True).drop_duplicates()

import numpy as np
players_hands['winner_hand'] = players_hands['winner_hand'].apply(lambda x:np.nan if x == 'U' else x)
players_hands['winner_hand'].dropna(inplace = True, axis = 0)
players_hands['winner_name5'].dropna(inplace = True, axis = 0)

players_hands_dict = {p:np.nan for p in players_hands['winner_name5']}
for i in players_hands.itertuples():
    players_hands_dict[i.winner_name5] = i.winner_hand
    
set_hand_2()

In [757]:
sorted((dataframe[dataframe['HandA'].isna()]['Winner'].append(dataframe[dataframe['HandB'].isna()]['Loser']).unique().tolist()))

['ABDULLA M.',
 'AHOUDA A.',
 'AL GHAREEB M.',
 'AL MUTAWA J.',
 'AL-ALAWI S.K.',
 'ALAWADHI O.',
 'ALI MUTAWA J.M.',
 'ALTMAIER D.',
 'ALVAREZ E.',
 'ANCIC I.',
 'ANDERSON O.',
 'ANDREEV A.',
 'ARAGONE JC',
 'ARTUNEDO MARTINAVARRO A.',
 'ASCIONE A.',
 'AVIDZBA A.',
 'BACHELOT J.F',
 'BAGHDATIS M.',
 'BAHROUZYAN O.',
 'BASSO A.',
 'BAUTISTA R.',
 'BELLIER A.',
 'BENCHETRIT E.',
 'BENNETEAU A.',
 'BERRETTINI M.',
 'BOGAERTS R.',
 'BOGOMOLOV A.',
 'BOGOMOLOV JR. A.',
 'BOGOMOLOV JR.A.',
 'BONZI B.',
 'BROOKSBY J.',
 'CARUANA L.',
 'CELIKBILEK A.',
 'CERUNDOLO F.',
 'CERVANTES I.',
 'CHAKI R.',
 'CHEKOV P.',
 'CONDOR F.',
 'CORRIE E.',
 'DAILEY Z.',
 'DASNIERES DE VEIGY J.',
 'DAVIDOVICH FOKINA A.',
 'DAVLETSHIN V.',
 'DAVYDENKO P.',
 'DE HEART R.',
 'DEEN HESHAAM A.',
 'DEL BONIS F.',
 "DELL'ACQUA M.",
 'DEV VARMAN S.',
 'DONSKI A.',
 'DUBRIVNYY A.',
 'DUTRA DA SILVA R.',
 'ESTRELLA BURGOS V.',
 'FISH A.',
 'FLANAGAN I.',
 'FORNELL M.',
 'FRITZ T.',
 'GALAN D.E.',
 'GALLARDO M.',
 'GAO X.',
 'GASTON H.',
 'GOJO B.',
 'GOMEZ A.',
 'GOMEZ L.',
 'GORANSSON T.',
 'GRANOLLERS PUJOL G.',
 'GRANOLLERS-PUJOL M.',
 'GRAY A.',
 'GROMLEY C.',
 'GRUBER K.',
 'GUCCIONE A.',
 'GUZMAN J.',
 'HAJI A.',
 'HAJJI A.',
 'HANFMANN Y.',
 'HANK T.',
 'HANTSCHEK M.',
 'HARRIS L.',
 'HARSANYI P.',
 'HERBERT P-H.',
 'HERBERT P.H',
 'HERNANDEZ-FERNANDEZ J.',
 'HUESLER M.A.',
 'IDMBAREK Y.',
 'JANVIER M.',
 'JONES G.D.',
 'JUBB P.',
 'JUN W.',
 'KACHMAZOV A.',
 'KIM K',
 'KING K.',
 'KIRKIN E.',
 'KODERISCH C.',
 'KOHLSCHREIBER P..',
 'KOLAR Z.',
 'KORDA S.',
 'KORTELING S.',
 'KUCERA V.',
 'KUNITCIN I.',
 'KUTAC R.',
 'KUZNETSOV AL.',
 'KUZNETSOV AN.',
 'KWIATKOWSKI T.S.',
 'KYPSON P.',
 'LAZOV A.',
 'LENZ J.',
 'LESHEM E.',
 'LEVINE I.',
 'LIN J.M.',
 'LOPEZ VILLASENOR G.',
 'LOPEZ-JAEN M.A.',
 'LU Y.',
 'LUQUE D.',
 'MADEN Y.',
 'MARCH O.',
 'MARIN L.',
 'MARRAI M.',
 'MARTINEZ P.',
 'MATHIEU P.',
 'MATOS-GIL I.',
 'MEISTER N.',
 'MILOJEVIC N.',
 'MIYAO J.',
 'MOELLER M.',
 'MONTEIRO J.',
 'MORAING M.',
 'MORONI G.',
 'MOTT B.',
 'MULLER A.',
 'MUNAR J.',
 'MUNOZ DE LA NAVA D.',
 'NADER M.',
 'NAVA E.',
 'NAVARRO-PASTOR I.',
 'NEDOVYESOV O.',
 'NIKI T.',
 "O'BRIEN A.",
 "O'CONNELL C.",
 "O'NEAL J.",
 'OJEDA LARA R.',
 'OLASO G.',
 'OPELKA R.',
 'ORTEGA-OLMEDO R.',
 'PASHA N.',
 'PFEIFFER K.',
 'PIROS Z.',
 'PODLIPNIK H.',
 'POLMANS M.',
 'POPYRIN A.',
 'PRASHANTH V.',
 'PRPIC A.',
 'PURCELL M.',
 'QUERRY S.',
 'QUIGLEY E.',
 'QURESHI A.',
 'RAMOS-VINOLAS A.',
 'RASCON T.',
 'REIX C.',
 'REYES-VARELA M.A.',
 'RIBA-MADRID P.',
 'ROBREDO R.',
 'RODIONOV J.',
 'ROUMANE R.',
 'RUEVSKI P.',
 'SABRY S.',
 'SAFIULLIN R.',
 'SAKAMOTO P.',
 'SALVA B.',
 'SAMPER-MONTANA J.',
 'SANCHEZ DE LUNA J.A.',
 'SARMIENTO R.',
 'SCHUTTLER P.',
 'SCHWARTZMAN D.',
 'SERDARUSIC N.',
 'SHANE R.',
 'SI Y.M.',
 'SILVA D.',
 'SILVA F.',
 'SINNER J.',
 'SMETHURST D.',
 'SMITH A.',
 'STATHAM J.',
 'STATHAM R.',
 'STEPANEK M.',
 'SULTAN-KHALFAN A.',
 'SVAJDA Z.',
 'TAKAHASHI Y.',
 'TOPIC J.',
 'TRAVAGLIA S.',
 'TRUJILLO G.',
 'TRUSENDI W.',
 'TYURNEV E.',
 'VAISSE M.',
 'VAN DER DIUM A.',
 'VAN DER MEER N.',
 'VAN DER MERWE I.',
 'VATUTIN A.',
 'VERDASCO M.',
 'VICENTE M.',
 'VILOCA J.A.',
 'VIOLA MAT.',
 'WALTER L.',
 'WANG Y.',
 'WANG Y. JR',
 'WANG Y. JR.',
 'WANG Y.T.',
 'WARD A.',
 'WATANUKI Y.',
 'WILLMAN D.',
 'XU J.C.',
 'YOON Y.',
 'YOUZHNY A.',
 'ZAYED M. S.',
 'ZEKIC M.',
 'ZHANG Z.',
 'ZHANG ZE',
 'ZHANG ZE.',
 'ZHANG ZH.']

Info prese da:
https://www.ultimatetennisstatistics.com/

In [758]:
filling_players_hand = {
 'ABDULLA M.': 'R',
 'AHOUDA A.': 'R',
 'AL GHAREEB M.': 'R',
 'AL MUTAWA J.': 'R',
 'AL-ALAWI S.K.': 'R',
 'ALAWADHI O.': 'R',
 'ALI MUTAWA J.M.': 'R',
 'ALTMAIER D.': 'R',
 'ALVAREZ E.': 'R',
 'ANCIC I.': 'R',
 'ANDERSON O.': 'R',
 'ANDREEV A.': 'R',
 'ARAGONE JC': 'R',
 'ARTUNEDO MARTINAVARRO A.': 'R',
 'ASCIONE A.': 'R',
 'AVIDZBA A.': 'R',
 'BACHELOT J.F': 'R',
 'BAGHDATIS M.': 'R',
 'BAHROUZYAN O.': 'R',
 'BASSO A.': 'L',
 'BAUTISTA R.': 'R',
 'BELLIER A.': 'L',
 'BENCHETRIT E.': 'R',
 'BENNETEAU A.': 'R',
 'BERRETTINI M.': 'R',
 'BOGAERTS R.': 'L',
 'BOGOMOLOV A.': 'R',
 'BOGOMOLOV JR. A.': 'R',
 'BOGOMOLOV JR.A.': 'R',
 'BONZI B.': 'R',
 'BROOKSBY J.': 'R',
 'CARUANA L.': 'R',
 'CELIKBILEK A.': 'R',
 'CERUNDOLO F.': 'R',
 'CERVANTES I.': 'R',
 'CHAKI R.': 'R',
 'CHEKOV P.': 'R',
 'CONDOR F.': 'R',
 'CORRIE E.': 'R',
 'DAILEY Z.': 'R',
 'DASNIERES DE VEIGY J.': 'L',
 'DAVIDOVICH FOKINA A.': 'R',
 'DAVLETSHIN V.': 'R',
 'DAVYDENKO P.': 'R',
 'DE HEART R.': 'L',
 'DEEN HESHAAM A.': 'R',
 'DEL BONIS F.': 'L',
 "DELL'ACQUA M.": 'R',
 'DEV VARMAN S.': 'R',
 'DONSKI A.': 'R',
 'DUBRIVNYY A.': 'R',
 'DUTRA DA SILVA R.': 'R',
 'ESTRELLA BURGOS V.': 'R',
 'FISH A.': 'R',
 'FLANAGAN I.': 'R',
 'FORNELL M.': 'R',
 'FRITZ T.': 'R',
 'GALAN D.E.': 'R',
 'GALLARDO M.': 'R',
 'GAO X.': 'R',
 'GASTON H.': 'L',
 'GOJO B.': 'R',
 'GOMEZ A.': 'R',
 'GOMEZ L.': 'L',
 'GORANSSON T.': 'L',
 'GRANOLLERS PUJOL G.': 'R',
 'GRANOLLERS-PUJOL M.': 'R',
 'GRAY A.': 'R',
 'GROMLEY C.': 'R',
 'GRUBER K.': 'R',
 'GUCCIONE A.': 'R',
 'GUZMAN J.': 'R',
 'HAJI A.': 'R',
 'HAJJI A.': 'R',
 'HANFMANN Y.': 'R',
 'HANK T.': 'L',
 'HANTSCHEK M.': 'R',
 'HARRIS L.': 'R',
 'HARSANYI P.': 'R',
 'HERBERT P-H.': 'R',
 'HERBERT P.H': 'R',
 'HERNANDEZ-FERNANDEZ J.': 'R',
 'HUESLER M.A.': 'L',
 'IDMBAREK Y.': 'R',
 'JANVIER M.': 'R',
 'JONES G.D.': 'R',
 'JUBB P.': 'R',
 'JUN W.': 'R',
 'KACHMAZOV A.': 'R',
 'KIM K': 'R',
 'KING K.': 'L',
 'KIRKIN E.': 'R',
 'KODERISCH C.': 'R',
 'KOHLSCHREIBER P..': 'R',
 'KOLAR Z.': 'R',
 'KORDA S.': 'R',
 'KORTELING S.':'R',
 'KUCERA V.': 'R',
 'KUNITCIN I.': 'R',
 'KUTAC R.': 'R',
 'KUZNETSOV AL.': 'R',
 'KUZNETSOV AN.': 'R',
 'KWIATKOWSKI T.S.': 'R',
 'KYPSON P.': 'R',
 'LAZOV A.': 'L',
 'LENZ J.': 'R',
 'LESHEM E.': 'R',
 'LEVINE I.': 'R',
 'LIN J.M.': 'R',
 'LOPEZ VILLASENOR G.': 'R',
 'LOPEZ-JAEN M.A.': 'R',
 'LU Y.': 'R',
 'LUQUE D.': 'R',
 'MADEN Y.': 'R',
 'MARCH O.': 'R',
 'MARIN L.': 'R',
 'MARRAI M.': 'R',
 'MARTINEZ P.': 'R',
 'MATHIEU P.': 'R',
 'MATOS-GIL I.': 'R',
 'MEISTER N.': 'R',
 'MILOJEVIC N.': 'R',
 'MIYAO J.': 'R',
 'MOELLER M.': 'R',
 'MONTEIRO J.': 'R',
 'MORAING M.': 'L',
 'MORONI G.': 'R',
 'MOTT B.': 'R',
 'MULLER A.': 'R',
 'MUNAR J.': 'R',
 'MUNOZ DE LA NAVA D.': 'L',
 'NADER M.': 'R',
 'NAVA E.': 'R',
 'NAVARRO-PASTOR I.': 'R',
 'NEDOVYESOV O.': 'R',
 'NIKI T.': 'R',
 "O'BRIEN A.": 'R',
 "O'CONNELL C.": 'R',
 "O'NEAL J.": 'R',
 'OJEDA LARA R.': 'R',
 'OLASO G.': 'R',
 'OPELKA R.': 'R',
 'ORTEGA-OLMEDO R.': 'R',
 'PASHA N.': 'R',
 'PFEIFFER K.': 'R',
 'PIROS Z.': 'R',
 'PODLIPNIK H.': 'R',
 'POLMANS M.': 'R',
 'POPYRIN A.': 'R',
 'PRASHANTH V.': 'R',
 'PRPIC A.': 'R',
 'PURCELL M.': 'R',
 'QUERRY S.': 'R',
 'QUIGLEY E.': 'R',
 'QURESHI A.': 'R',
 'RAMOS-VINOLAS A.': 'L',
 'RASCON T.': 'R',
 'REIX C.': 'R',
 'REYES-VARELA M.A.': 'R',
 'RIBA-MADRID P.': 'R',
 'ROBREDO R.': 'R',
 'RODIONOV J.': 'L',
 'ROUMANE R.': 'R',
 'RUEVSKI P.': 'R',
 'SABRY S.': 'R',
 'SAFIULLIN R.': 'R',
 'SAKAMOTO P.': 'R',
 'SALVA B.': 'R',
 'SAMPER-MONTANA J.': 'R',
 'SANCHEZ DE LUNA J.A.': 'R',
 'SARMIENTO R.': 'R',
 'SCHUTTLER P.': 'R',
 'SCHWARTZMAN D.': 'R',
 'SERDARUSIC N.': 'R',
 'SHANE R.': 'R',
 'SI Y.M.': 'R',
 'SILVA D.': 'R',
 'SILVA F.': 'L',
 'SINNER J.': 'R',
 'SMETHURST D.': 'R',
 'SMITH A.': 'R',
 'STATHAM J.': 'R',
 'STATHAM R.': 'R',
 'STEPANEK M.': 'R',
 'SULTAN-KHALFAN A.': 'R',
 'SVAJDA Z.': 'R',
 'TAKAHASHI Y.': 'R',
 'TOPIC J.': 'R',
 'TRAVAGLIA S.':'R',
 'TRUJILLO G.': 'R',
 'TRUSENDI W.': 'R',
 'TYURNEV E.': 'R',
 'VAISSE M.': 'R',
 'VAN DER DIUM A.': 'R',
 'VAN DER MEER N.': 'R',
 'VAN DER MERWE I.': 'R',
 'VATUTIN A.': 'R',
 'VERDASCO M.': 'R',
 'VICENTE M.': 'R',
 'VILOCA J.A.': 'R',
 'VIOLA MAT.': 'R',
 'WALTER L.': 'R',
 'WANG Y.': 'R',
 'WANG Y. JR': 'R',
 'WANG Y. JR.': 'R',
 'WANG Y.T.': 'R',
 'WARD A.': 'R',
 'WATANUKI Y.': 'R',
 'WILLMAN D.': 'R',
 'XU J.C.': 'R',
 'YOON Y.': 'R',
 'YOUZHNY A.': 'R',
 'ZAYED M. S.': 'R',
 'ZEKIC M.': 'R',
 'ZHANG Z.': 'R',
 'ZHANG ZE': 'R',
 'ZHANG ZE.': 'R',
 'ZHANG ZH.': 'R'
}

In [759]:
def set_hand_filled():
    def get_hand(p):
        return filling_players_hand[p]
    
    dataframe['HandA'].fillna(dataframe[dataframe['HandA'].isna()]['Winner'].apply(lambda x: filling_players_hand[x]), inplace = True)
    dataframe['HandB'].fillna(dataframe[dataframe['HandB'].isna()]['Loser'].apply(lambda x: filling_players_hand[x]), inplace = True)

In [760]:
set_hand_filled()

In [762]:
len((dataframe[dataframe['HandA'].isna()]['Winner'].append(dataframe[dataframe['HandB'].isna()]['Loser']).unique().tolist()))

0